Explain how to pass the configuration to the UDW
ezsystems/developer-documentation pull request #1134
Opened 2020-08-26 20:02 UTC by Plopix

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | 
| Versions      |

2020-08-31 10:19 UTC, dew326 requested changes

2020-08-31 10:19 UTC, dew326 commented on docs/extending/extending_udw.md
> +//const config = JSON.parse(somewhere.dataset.udwConfig);
I would write something like this:
```suggestion
//const config = JSON.parse(document.querySelector('.btn-udw-trigger).dataset.udwConfig);
```

And I would add this class to the button above to show which udwConfig should be passed to the React component

2020-08-31 10:19 UTC, dew326 commented on docs/extending/extending_udw.md
> +    {...config}
```suggestion
    ...config
```

2020-08-31 10:19 UTC, dew326 commented on docs/extending/extending_udw.md
> +> `simple` configuration is one of the default configuration provided. You can also do your [own configuration](#Adding-new-configuration).
`simple` or `single`?

2020-09-16 12:30 UTC, dabrt requested changes

2020-09-16 12:30 UTC, dabrt commented on docs/extending/extending_udw.md
> +UDW requires configuration that you can provide using the `ez_udw_config` Twig helper. This configuration must be spread to the props of the component itself.
```suggestion
UDW requires that you provide configuration by using the `ez_udw_config` Twig helper. This configuration must be spread to the properties of the component itself.
```
Also - what do you mean by "spread" - is it "distributed" or "populated"?

2020-09-22 05:22 UTC, dew326 approved these changes

2020-09-22 07:03 UTC, dabrt approved these changes

2020-10-16 11:55 UTC, merged