EZP-31912: [3.1] Fixed static server example and related pieces of File Management doc
ezsystems/developer-documentation pull request #1148
Opened 2020-09-23 12:39 UTC by alongosz

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | [EZP-31740](https://jira.ez.no/browse/EZP-31740), [EZP-31912](https://jira.ez.no/browse/EZP-31912)
| Relates to | ezsystems/ezplatform-kernel#110, #1142
| Versions      | 3.1+

This is a port of #1142 to 3.1 and higher. Public directory path has changed in Symfony 5.

2020-09-24 08:02 UTC, dabrt requested changes

2020-09-24 08:02 UTC, dabrt commented on docs/guide/file_management.md
> +    For security reasons it is recommended not to map `/path/to/ezplatform/public/` as a static server
```suggestion
    For security reasons, do not map `/path/to/ezplatform/public/` as
```

2020-09-24 08:02 UTC, dabrt commented on docs/guide/file_management.md
> +    Document Root. `/var/` directory should be mapped to `/path/to/ezplatform/public/var` directly instead.
```suggestion
    Document Root of the static server.
    Map the `/var/` directory directly to `/path/to/ezplatform/public/var` instead.
```

2020-09-28 12:32 UTC, alongosz commented
Cherry-picked the changes from the review of #1142 as acb08d1. Seems they cover all the requested here.

2020-09-28 12:34 UTC, dabrt approved these changes

2020-10-16 12:11 UTC, merged