Combine OSS, Enterprise and Commerce installation guides
ezsystems/developer-documentation pull request #1151
Opened 2020-09-24 13:54 UTC by DominikaK

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | n/a
| Versions      | 3.1, master

Companion PR to https://github.com/ezsystems/developer-documentation/pull/1147

This combines the OSS, Enterprise and Commerce installation guides into one page, plus some general cleanup.

For reviewers: the `=== "eZ Platform"` syntax is rendered as tabs, for example:
![image](https://user-images.githubusercontent.com/13621049/94154160-e421aa00-fe7d-11ea-9a1a-21e9cfa858c7.png)

2020-10-06 10:09 UTC, dabrt requested changes

2020-10-06 10:09 UTC, dabrt commented on docs/getting_started/install_ez_platform.md
>  (edit your profile, go to Developer settings > Personal access tokens and Generate new token with default settings).
```suggestion
(edit your profile and go to **Developer settings** > **Personal access tokens** > **Generate new token with default settings**).
```

2020-10-06 10:09 UTC, dabrt commented on docs/getting_started/install_ez_platform.md
> +Directories `var` and `public/var` need to be writable by CLI and the web server user.
```suggestion
Directories `var` and `public/var` must be writable by CLI and the web server user.
```

2020-10-06 10:09 UTC, dabrt commented on docs/getting_started/install_ez_platform.md
> +    For security reasons, in production, the web server should not have write access to other directories than `var`. Skip the step above and follow the link below for production needs instead.
```suggestion
    For security reasons, in production, the web server cannot have write access to other directories than `var`. 
    Skip the step above and follow the link below for production needs instead.
```

2020-10-06 10:09 UTC, dabrt commented on docs/getting_started/install_ez_platform.md
> +    You must also make sure that the web server cannot interpret files in the `var` directory through PHP.
```suggestion
    You must also make sure that the web server cannot interpret the files in the `var` directory through PHP.
```

2020-10-06 10:09 UTC, dabrt commented on docs/getting_started/install_ez_platform.md
> +    To enable delayed publishing of Content using the Date-based Publisher, you need to set up cron to run the command `bin/console ezplatform:scheduled:run` periodically.
```suggestion
    To enable delayed publishing of Content using the Date-based Publisher, you must set up cron to run the `bin/console ezplatform:scheduled:run` command periodically.
```

2020-10-06 10:11 UTC, DominikaK commented on docs/getting_started/troubleshooting.md
> +## Configuration required to communicate with ERP
Not clear yet, will be verified after reviewing the ERP section of commerce doc

2020-10-06 10:13 UTC, DominikaK commented on docs/getting_started/install_ez_platform.md
>  Before getting started, make sure you review the [requirements](requirements.md) page to see the systems we support and use for testing.
The reqs in this page are actually a subset of those on the Requirements page, so this makes more sense:
```suggestion
Before getting started, make sure you review other [requirements](requirements.md) to see the systems we support and use for testing.
```

2020-10-06 10:14 UTC, DominikaK commented on docs/getting_started/install_ez_platform.md
> +        Composer will ask to do this for you on updates.
```suggestion
        Composer will ask you to provide a token every time you perform an update.
```

2020-10-06 10:16 UTC, DominikaK commented on docs/getting_started/install_ez_platform.md
> +        Composer will ask to do this for you on updates.
```suggestion
        Composer will ask whether you want to save the token every time you perform an update.
```

2020-10-06 10:16 UTC, DominikaK commented on docs/getting_started/install_ez_platform.md
> +        If you decline, you can create an `auth.json` file manually in one of the following ways:
```suggestion
        If you prefer, you can decline and create an `auth.json` file manually in one of the following ways:
```

2020-10-06 10:18 UTC, DominikaK commented on docs/getting_started/install_ez_platform.md
> +        - A: Store your credentials in the project directory (for security reasons do not check it in to git):
On this page VCS is only used as part of commands. In other places, I'd rather change VCS to git, as we're using a specific one and one less acronym is always better.

2020-10-06 10:19 UTC, DominikaK commented on docs/getting_started/install_ez_platform.md
> +There are two ways to get eZ Platform. The result is the same, so you can use the way you prefer:
```suggestion
There are two ways to get an instance of eZ Platform. 
The result is the same, so you can use the way you prefer:
```

2020-10-06 10:20 UTC, DominikaK commented on docs/getting_started/install_ez_platform.md
> +    git clone https://github.com/ezsystems/ezplatform .
Cloning to the current repository avoids having to add `cd <your directory>`, which people are likely to forget.

2020-10-06 10:24 UTC, DominikaK commented on docs/getting_started/install_ez_platform.md
> +    If you have several projects set up on your machine,
```suggestion
    If you configure several projects on one machine, make sure that
```

2020-10-06 10:26 UTC, DominikaK commented on docs/getting_started/install_ez_platform.md
>  (edit your profile, go to Developer settings > Personal access tokens and Generate new token with default settings).
```suggestion
(edit your profile and go to **Developer settings** > **Personal access tokens** > **Generate new token** with default settings).
```

2020-10-08 08:17 UTC, dabrt approved these changes

2020-10-09 06:57 UTC, merged