Added explanation on what QueryType is when it's introduced
ezsystems/developer-documentation pull request #1159
Opened 2020-10-05 11:34 UTC by Steveb-p

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | N/A
| Versions      | 3.0, 3.1, master

Added explanation on what `QueryType` is when it's introduced for the first time in tutorial docs.
I found that this chapter was confusing as to what exactly a new developer is doing and why a new class is needed, what it's purpose is. Before this moment developer was already using built-in types, but it was never explicitly said.

2020-10-21 13:38 UTC, DominikaK commented
@Steveb-p, I've had to modify branch history, can you please rebase this PR against the current 3.0 branch?

2020-10-28 00:05 UTC, dabrt requested changes
Please answer my questions. I also think that the "QueryType overview" section could be combined with the next section and probabyly shortened.

2020-10-28 00:05 UTC, dabrt commented on docs/tutorials/platform_beginner/5_display_a_list_of_content_items.md
> +You can read more about them [here](../../guide/controllers/#creating-custom-query-types)
```suggestion
For more information about QueryTypes, see [Built-In Query Types](../../guide/controllers/#built-in-query-types)
```

2020-10-28 00:05 UTC, dabrt commented on docs/tutorials/platform_beginner/5_display_a_list_of_content_items.md
> +In our case we want to display `ride` objects that have been published (are visible).
```suggestion
Here, you want to display `ride` objects that have been published (are visible).
```

2020-10-28 07:58 UTC, Steveb-p commented on docs/tutorials/platform_beginner/5_display_a_list_of_content_items.md
> +They can also define parameters to dynamically control them, allowing changing the resultset based on external factors.
Changed "they" to "QueryTypes", removed the second part about control.

2020-10-28 08:41 UTC, dabrt approved these changes

2020-10-28 08:53 UTC, merged