EZEE-3224: Segmentation API
ezsystems/developer-documentation pull request #1172
Opened 2020-10-12 11:58 UTC by DominikaK

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://jira.ez.no/browse/EZEE-3224
| Versions      | master (3.2)

Targeting block and managing segments in the Back Office will be covered in a separate PR.

To do:
- [ ] Verify examples after all parts of the feature are merged

2020-10-15 08:54 UTC, webhdx approved these changes
One minor remark

2020-10-15 08:54 UTC, webhdx commented on docs/api/public_php_api_managing_users.md
> +        'group' => $newSegmentGroup,
```suggestion
        'group' => $segmentGroup,
```

It should indicate that you need to pass existing group.

2020-10-20 15:08 UTC, dabrt requested changes

2020-10-20 15:08 UTC, dabrt commented on docs/api/public_php_api_managing_users.md
> +    or `SegmentGroupUpdateStruct` respectively.
```suggestion
    or `SegmentGroupUpdateStruct`, respectively.
```

2020-10-20 15:08 UTC, dabrt commented on docs/api/public_php_api_managing_users.md
> +    or `SegmentationService::removeSegmentGroup()` respectively:
```suggestion
    or `SegmentationService::removeSegmentGroup()`, respectively:
```

2020-10-20 15:08 UTC, dabrt commented on docs/guide/admin_panel.md
> +Segments are used to display specific content to specific Users.
We might consider going for the active voice here:
"You use segments to display ..."

2020-10-20 15:08 UTC, dabrt commented on docs/guide/limitation_reference.md
> +A Limitation to specify if the User has access Segments within a specific Segment Group.
```suggestion
A Limitation to specify whether the User has access Segments within a specific Segment Group.
```

2020-10-20 15:08 UTC, dabrt commented on docs/guide/limitation_reference.md
> +|`<Segment_group_id>`|`<Segment_group_name>`|All valid Segment Group IDs can be set as value(s)|
```suggestion
|`<Segment_group_id>`|`<Segment_group_name>`|All valid Segment Group IDs can be set as value(s).|
```

2020-10-20 15:09 UTC, DominikaK commented on docs/api/public_php_api_managing_users.md
> +    ### Checking assignation
Good point

2020-10-20 15:10 UTC, DominikaK commented on docs/api/public_php_api_managing_users.md
> +    ### Checking assignation
```suggestion
    ### Checking assignment
```

2020-10-20 15:10 UTC, DominikaK commented on docs/guide/admin_panel.md
> +Segments are used to display specific content to specific Users.
```suggestion
You can use Segments to display specific content to specific Users.
```

2020-10-20 15:28 UTC, dabrt approved these changes

2020-10-20 15:28 UTC, merged