EZEE-3303 - search engine comparison
ezsystems/developer-documentation pull request #1176
Opened 2020-10-13 15:48 UTC by dabrt

| Question | Answer |
| ------------- | --- |
| JIRA Ticket   | EZEE-3303 |
| Versions      | master |

Add a table with search engine comparison to developer's guide.

2020-10-13 15:50 UTC, dabrt commented on docs/guide/search/search.md
> +## Install
```suggestion
```

2020-10-13 16:56 UTC, adamwojs approved these changes

2020-10-14 06:57 UTC, DominikaK requested changes

2020-10-14 06:57 UTC, DominikaK commented on docs/guide/search/search.md
> +| **Feature** | **Elasticsearch** | **Apache Solr** | **Legacy Search Engine** _**(SQL)**_ |
```suggestion
| Feature | Elasticsearch | Apache Solr | Legacy Search Engine (SQL) |
```

2020-10-14 06:57 UTC, DominikaK commented on docs/guide/search/search.md
> +| Filtering | Yes | Yes | Yes, but limited\* |
```suggestion
| Filtering | Yes | Yes | Yes, limited\* |
```

2020-10-14 06:57 UTC, DominikaK commented on docs/guide/search/search.md
> +| Query _(filter with scoring)_ | Yes | Yes | Only filters, no scoring |
```suggestion
| Query (filter with scoring) | Yes | Yes | Only filters, no scoring |
```

2020-10-14 06:57 UTC, DominikaK commented on docs/guide/search/search.md
> +| Fulltext | Yes | Yes, incl. advanced features | Partly\*\* |
```suggestion
| Fulltext | Yes | Yes, incl. advanced features | Partial support \*\* |
```

2020-10-14 06:57 UTC, DominikaK commented on docs/guide/search/search.md
> +| Faceting | Partly (deprecated) | [Partly as of v1.4](https://doc.ezplatform.com/en/latest/api/public_php_api_browsing/#performing-a-faceted-search) | No |
```suggestion
| Faceting (deprecated)  | Partial support | Partial support | No |
```
The oldest supported version uses the solr bundle > v1.4, so this is irrelevant.
Also remember to remove the "deprecated" note for faceting when merging to other versions (it is only deprecated in v3.2).

2020-10-14 06:57 UTC, DominikaK commented on docs/guide/search/search.md
> +| Highlighting | Planned _(TBD when)_ | Planned _(TBD when)_ | No |
```suggestion
| Spellchecking | No | No | No |
| Highlighting | No | No | No |
```
Let's deal with what is in the product now, not in the future. Or you could just remove those two lines altogether

2020-10-14 06:57 UTC, DominikaK commented on docs/guide/search/search.md
> +| Index time boosting | ?\*\*\*\* | [Yes, in \&gt;= v1.4,\&lt; v2.0](https://github.com/ezsystems/ezplatform-solr-search-engine/releases/tag/v1.4.0)\*\*\* | No |
```suggestion
| Index time boosting | \*\*\*\* | Yes | No |
```
AFAIK this means it is supported in v3, but not in earlier versions. Please indicate it when merging to relevant branches.

2020-10-14 06:57 UTC, DominikaK commented on docs/guide/search/search.md
> +_* Usage of Criterion and SortClause for Fields does not perform well on medium to larger
```suggestion
* Usage of Criteria and Sort Clauses for Fields does not perform well on medium to larger 
```

2020-10-14 06:57 UTC, DominikaK commented on docs/guide/search/search.md
> +amount of data with Legacy Search Engine (SQL), use Solr for this._
```suggestion
amounts of data with Legacy Search Engine (SQL), use Solr for this.
```

2020-10-14 06:57 UTC, DominikaK commented on docs/guide/search/search.md
> +full text capabilities such as `word "phrase" (group) +mandatory -prohibited AND && OR || NOT !`._
```suggestion
** Does not cover all full text features including: scoring/ranking (Solr performs sorting on scoring by default)
```
Please double check, but I think all the warnings in this point referred to versions of the solr bundle that are not used in any supported version of Platform (v1.13 uses solr bundle v1.5)

2020-10-14 06:57 UTC, DominikaK commented on docs/guide/search/search.md
> +_*** As of Solr 7, index-time boosting is no longer available. Query time boosting is planned to be introduced instead in future 2.x and 3.x release.
```suggestion
*** As of Solr 7, index-time boosting is no longer available.
```

2020-10-14 06:57 UTC, DominikaK commented on docs/guide/search/search.md
> +See [Major changes in Solr 7](https://lucene.apache.org/solr/guide/7_2/major-changes-in-solr-7.html) for more information._
```suggestion
See [Major changes in Solr 7](https://lucene.apache.org/solr/guide/7_2/major-changes-in-solr-7.html) for more information.
```

2020-10-14 06:57 UTC, DominikaK commented on docs/guide/search/search.md
> +_**** Elasticsearch offers query time boosting instead._
```suggestion
**** Elasticsearch offers query time boosting instead.
```

2020-10-15 11:29 UTC, DominikaK approved these changes

2020-10-15 11:29 UTC, DominikaK commented on docs/guide/search/search.md
> +| Fulltext | Yes | Yes, incl. advanced features | Partial support |
```suggestion
| Fulltext search | Yes | Yes, incl. advanced features | Partial support |
```

2020-10-15 11:35 UTC, merged