[Update 2.5] Add mention of powered by header and how to configure it
ezsystems/developer-documentation pull request #1223
Opened 2020-11-07 08:29 UTC by andrerom

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://github.com/ezsystems/ez-support-tools/pull/52
| Versions      | 2.5+

This also drop Password expiry step as it is covered in database schema steps above.

2020-11-07 08:30 UTC, andrerom commented
@DominikaK There was mention by @mnocon of also finding a place to document this in general, any suggestions on where this would fit?

2020-11-09 07:48 UTC, DominikaK requested changes

2020-11-09 07:48 UTC, DominikaK commented on docs/updating/4_update_2.5.md
> +### Powered By Header
```suggestion
### Powered-By header
```

2020-11-09 07:48 UTC, DominikaK commented on docs/updating/4_update_2.5.md
> +In order to be able to promote use of eZ Platform, `ezsystems/ez-support-tools` v1.0.9 adds capability to set powered by header.
```suggestion
In order to promote use of eZ Platform, `ezsystems/ez-support-tools` v1.0.9 sets the Powered-By header.
```
Or maybe, as we shouldn't expect users know which package has which version in which release:
```suggestion
In order to promote use of eZ Platform, `ezsystems/ez-support-tools` as of eZ Platform v2.5.15 sets the Powered-By header.
```

2020-11-09 07:48 UTC, DominikaK commented on docs/updating/4_update_2.5.md
> +By default this is enabed, and will generate a header like `Powereed-By: eZ Platform Enterprise 2.5`.
```suggestion
It is enabled by default and generates a header like `Powered-By: eZ Platform Enterprise 2.5`.
```

2020-11-09 07:48 UTC, DominikaK commented on docs/updating/4_update_2.5.md
> +If you'd like to ommit version number, for instance if you are stuck on a fast track release beyond it's maintenance window:
```suggestion
To omit the version number, for instance if you are stuck on a fast track release beyond its maintenance window,
use the following configuration:
```

2020-11-09 07:48 UTC, DominikaK commented on docs/updating/4_update_2.5.md
> +If you however want to ommit the whole feature, you can likewise do that by disabling it:
```suggestion
To opt out of the whole feature, by disabling it with the following configuration:

```

2020-11-09 07:48 UTC, DominikaK commented
The best place we have for documenting the settings outside the upgrade section would be https://doc.ibexa.co/en/master/guide/config_repository/

2020-11-24 08:42 UTC, DominikaK approved these changes

2020-11-25 08:58 UTC, andrerom commented
@DominikaK Updated to reflect change in code PR where default is now only showing major version, also update to target 2.5.16 as 2.5.15 is out already.

2020-11-27 07:28 UTC, merged