EC-218: Checkout revision
ezsystems/developer-documentation pull request #1224
Opened 2020-11-10 09:30 UTC by DominikaK

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/EC-218
| Versions      | 3.1, 3.2, master

2020-11-13 13:14 UTC, dabrt requested changes

2020-11-13 13:14 UTC, dabrt commented on docs/guide/checkout/order_confirmation.md
> +For a logged-in customer the address is taken from customer profile data.
```suggestion
For a logged-in customer, the address is taken from customer profile data.
```

2020-11-13 13:14 UTC, dabrt commented on docs/guide/checkout/order_confirmation.md
> +This address is also stored in the basket object next to the customer's address. The behavior is configurable:
```suggestion
This address is also stored in the basket object, next to the customer's address. 
The behavior is configurable:
```

2020-11-13 13:14 UTC, dabrt commented on docs/guide/checkout/order_confirmation.md
> +- `email_shop_owner_intro_text` (textmodule inside the backend)
```suggestion
- `email_shop_owner_intro_text` (text module inside the backend)
```
Also - what does it mean "inside the backend"?

2020-11-13 13:14 UTC, dabrt commented on docs/guide/checkout/return_process.md
> +The goal is to inform the user about the cancellation policies and give them the possible to return their goods, including online returns.
```suggestion
The goal is to inform the user about the cancellation policies and give them the possibility to return their goods, including online returns.
```

2020-11-13 13:44 UTC, DominikaK commented on docs/guide/checkout/local_orders.md
> +The response has the same structure as a response returned from ERP, so no additional changes in the template are required.
```suggestion
The response has the same structure as the response returned from ERP, so no additional changes in the template are required.
```
As this is a specific response (referred to by "returns an order ID" in the previous line)

2020-11-13 13:45 UTC, DominikaK commented on docs/guide/checkout/order_confirmation.md
> +Both the customer and a sales contact (if configured) receive confirmation emails.
How about:
```suggestion
Both the customer and a sales contact (if configured) should receive confirmation emails.
```

2020-11-13 13:47 UTC, DominikaK commented on docs/guide/checkout/order_confirmation.md
> +- `email_shop_owner_intro_text` (textmodule inside the backend)
```suggestion
 `email_shop_owner_intro_text` (text module in the Back Office)
```

2020-11-13 15:27 UTC, dabrt commented on docs/guide/checkout/order_confirmation.md
> +Both the customer and a sales contact (if configured) receive confirmation emails.
ok

2020-11-20 09:50 UTC, dabrt approved these changes

2020-11-20 09:51 UTC, merged