EC-218: Quick order, vouchers, payment revision
ezsystems/developer-documentation pull request #1225
Opened 2020-11-13 10:45 UTC by DominikaK

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/EC-218
| Versions      | 3.1, 3.2, master

2020-11-13 15:22 UTC, dabrt requested changes

2020-11-13 15:22 UTC, dabrt commented on docs/guide/quick_order/quick_order_configuration.md
> +The `ses_variant_*` fields are additional fields indexed in the Solr.
```suggestion
The `ses_variant_*` fields are additional fields that are indexed in Solr.
```

2020-11-13 15:22 UTC, dabrt commented on docs/guide/vouchers/voucher_templates.md
> +Vouchers are rendered in the `vouchers` Twig block included in `Silversolutions/Bundle/EshopBundle/Resources/views/Basket/show.html.twig`.
```suggestion
Vouchers are rendered in the `vouchers` Twig block that is included in `Silversolutions/Bundle/EshopBundle/Resources/views/Basket/show.html.twig`.
```

2020-11-13 15:22 UTC, dabrt commented on docs/guide/vouchers/vouchers.md
> +Voucher data is sent to ERP in `PriceRequest` and `CreateOrderRequest`.
```suggestion
Voucher data is sent to the ERP in `PriceRequest` and `CreateOrderRequest`.
```

2020-11-13 15:22 UTC, dabrt commented on docs/guide/vouchers/vouchers.md
> +The ERP can send a message that the voucher is invalid. In that case this message is displayed in the basket.
```suggestion
The ERP can send a message that the voucher is invalid. 
When this happens, a message is displayed in the basket.
```

2020-11-13 15:22 UTC, dabrt commented on docs/guide/vouchers/vouchers.md
> +Using the `send_vouchers_as_lines` setting you can configure whether the voucher is sent to ERP as additional line with negative quantity (`true`)
```suggestion
With the `send_vouchers_as_lines` setting, you can configure whether the voucher is sent to ERP as an additional line with negative quantity (`true`)
```

2020-11-16 07:19 UTC, DominikaK commented on docs/guide/payment/payment.md
> +The respective options are registered in the checkout form by a DIC compiler pass and must fulfill some requirements:
```suggestion
The respective options are registered in the checkout form and must fulfill some requirements:
```

2020-11-16 07:19 UTC, DominikaK commented on docs/guide/payment/payment.md
> +The respective options are registered in the checkout form by a DIC compiler pass and must fulfill some requirements:
Good point

2020-11-20 09:49 UTC, dabrt approved these changes

2020-11-20 09:52 UTC, merged