EC-220: User management revision
ezsystems/developer-documentation pull request #1243
Opened 2020-12-02 13:05 UTC by DominikaK

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/EC-220
| Versions      | 3.1, 3.2, master

2020-12-07 12:28 UTC, dabrt requested changes

2020-12-07 12:28 UTC, dabrt commented on docs/guide/user_management/token.md
> +You can use the token in the built-in token controller to call a service and method, or in a custom controller or service.
```suggestion
You can use the token to call a service and method in the built-in token controller, or in a custom controller or service.
```
Is it 
"... in the built-in token controller that calls a service and method..."
or
"the token to call a service and method in the built-in token controller, or in a custom controller or service"
?

2020-12-07 12:28 UTC, dabrt commented on docs/guide/user_management/token.md
> +The token can be checked using `TokenService`. It returns the parameters stored when the token was created:
```suggestion
The token can be checked with the `TokenService`. It returns the parameters that were stored when the token was created: 
```

2020-12-07 12:28 UTC, dabrt commented on docs/guide/user_management/token.md
> +You can use the token to distribute unique links to customers.
```suggestion
You can use the token to deliver unique links to customers.
```

2020-12-07 12:28 UTC, dabrt commented on docs/guide/user_management/token.md
> +`TokenController` is called to process a token, e.g. after user registration when the user clicks the activation link.
```suggestion
`TokenController` is called to process a token, for example, after user registration when the user clicks the activation link.
```

2020-12-07 12:28 UTC, dabrt commented on docs/guide/user_management/token.md
> +This controller loads the token from the database, activates the user account and invalidates the token.
```suggestion
The controller loads the token from the database, activates the user account and invalidates the token.
```

2020-12-07 12:28 UTC, dabrt commented on docs/guide/user_management/token.md
> +Each token has the following attributes to process the token-specific logic:
```suggestion
Each token has the following attributes that are processed by the token-specific logic:
```

2020-12-07 12:49 UTC, DominikaK commented on docs/guide/newsletter/newsletter.md
> +To send additional data to the newsletter provider, you need to implement an event listener
```suggestion
To send additional data to the newsletter provider, implement an event listener
```

2020-12-07 12:51 UTC, DominikaK commented on docs/guide/user_management/login_and_registration.md
> +To adapt the success message of the private registration, change the text module with the identifier `success_register_private`.
```suggestion
To adapt the success message of the private registration, modify the text module with the identifier `success_register_private`.
```

2020-12-07 12:52 UTC, DominikaK commented on docs/guide/user_management/token.md
> +You can use the token in the built-in token controller to call a service and method, or in a custom controller or service.
```suggestion
You can use the token in the built-in token controller when calling a service and method, or in a custom controller or service.
```

2020-12-10 12:35 UTC, dabrt approved these changes

2020-12-10 12:43 UTC, merged