EZP-31616: Event reference
ezsystems/developer-documentation pull request #1289
Opened 2021-01-21 13:52 UTC by DominikaK

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/EZP-31616
| Versions      | 3.x, master

2021-01-22 13:26 UTC, alongosz requested changes

2021-01-22 13:26 UTC, alongosz commented on docs/guide/repository/event_reference/event_reference.md
> +    public function onEvent(CopyContentEvent $event)
CS & best practices:
```suggestion
    public function onCopyContent(CopyContentEvent $event): void
```

2021-01-22 13:26 UTC, alongosz commented on docs/guide/repository/event_reference/event_reference.md
> +            CopyContentEvent::class => ['onEvent', 0],
Best practices / naming: it's easier to debug an app if method name is self-commenting, e.g:
```suggestion
            CopyContentEvent::class => ['onCopyContent', 0],
```

2021-01-22 15:51 UTC, alongosz approved these changes

2021-01-26 09:42 UTC, dabrt approved these changes

2021-01-26 09:42 UTC, dabrt commented on docs/guide/repository/event_reference/other_events.md
> +The following events are dispatched adding Content items to bookmarks.
```suggestion
The following events are dispatched when adding Content items to bookmarks.
```

2021-01-26 09:42 UTC, dabrt commented on docs/guide/repository/event_reference/site_events.md
> +The following events are dispatched when managing [Sites](../../site_factory.md):
```suggestion
The following events are dispatched when managing [Sites](../../site_factory.md).
```

2021-01-26 09:42 UTC, dabrt commented on docs/guide/repository/event_reference/trash_events.md
> +The following events are dispatched when managing Trash:
```suggestion
The following events are dispatched when managing Trash.
```

2021-01-26 09:42 UTC, dabrt commented on docs/guide/repository/event_reference/url_events.md
> +The following events are dispatched when creating and managing [URL aliases](../../url_management.md#url-aliases):
```suggestion
The following events are dispatched when creating and managing [URL aliases](../../url_management.md#url-aliases).
```

2021-01-26 09:42 UTC, dabrt commented on docs/guide/repository/event_reference/url_events.md
> +The following events are dispatched when creating and managing [URL wildcards](../../url_management.md#url-wildcards):
```suggestion
The following events are dispatched when creating and managing [URL wildcards](../../url_management.md#url-wildcards).
```

2021-01-26 09:42 UTC, dabrt commented on docs/guide/repository/event_reference/user_events.md
> +## Update User data
```suggestion
## Updating User data
```

2021-01-26 09:42 UTC, dabrt commented on docs/guide/repository/event_reference/role_events.md
> +
```suggestion
```

2021-01-26 13:31 UTC, merged