EZP-32239: Data providers and eContent revision
ezsystems/developer-documentation pull request #1305
Opened 2021-02-11 10:24 UTC by DominikaK

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/EZP-32239
| Versions      | 3.x, master

Note: "Content model data provider" (ez5 data provider in code) renamed to "Repository data provider" after consultation with @alongosz 

To do: 
- [ ] Verify the status of Catalog Segmentation feature

2021-02-16 10:42 UTC, dabrt requested changes

2021-02-16 10:42 UTC, dabrt commented on docs/guide/econtent/econtent.md
> +The model itself has to be defined using SQL. The tab **eContent types** shows an overview of:
```suggestion
The model itself has to be defined by using SQL. 
The **eContent types** tab shows an overview of:
```

2021-02-16 10:42 UTC, dabrt commented on docs/guide/econtent/econtent.md
> +- defined eContent types (e.g. `product_group`, `product`)
```suggestion
- the defined eContent types (for example, `product_group` or `product`)
```

2021-02-16 10:42 UTC, dabrt commented on docs/guide/econtent/indexing_econtent_data.md
> +|`--siteaccess=import`|Informs the indexer to take the product data from the temporary tables.|
```suggestion
|`--siteaccess=import`|Instructs the indexer to take the product data from the temporary tables.|
```

2021-02-16 10:42 UTC, dabrt commented on docs/guide/econtent/indexing_econtent_data.md
> +|`--live-core`|Indexes directly on the live core (and not on the back core).</br>If you use `-r` together `--live-core`, the delete operation takes place before starting the indexer, so the full inde
```suggestion
|`--live-core`|Indexes directly on the live core (and not on the back core).</br>If you use `-r` together `--live-core`, the delete operation takes place before the indexer starts, so the full indexed content is not be available while indexing.|
```

2021-02-16 10:42 UTC, dabrt commented on docs/guide/econtent/indexing_econtent_data.md
> +|`siso_search.default.solr_spellcheck`|Enables or disables Solr spellcheck (aka "Did you mean?" functionality).|
```suggestion
|`siso_search.default.solr_spellcheck`|Enables or disables the Solr spellchecker (aka the "Did you mean?" functionality).|
```

2021-02-16 10:42 UTC, dabrt commented on docs/guide/econtent/staging_system.md
> +eContent supports a staging area. The product catalog can exist either as a live version which is used for the customer,
```suggestion
eContent supports a staging area. 
The product catalog can exist either as a live version which is used for the customer,
```

2021-02-16 10:42 UTC, dabrt commented on docs/guide/econtent/staging_system.md
> +After the import, switch the database tables and Solr cores. Execute the following commands:
```suggestion
After the import, switch the database tables and Solr cores. 
Execute the following commands:
```

2021-02-16 10:42 UTC, dabrt commented on docs/guide/econtent/staging_system.md
> +Depending on the project, you should purge the HTTP cache for the product catalog.
"Depending on the project" suggest choice while "You should" suggests neccessity. 

How about 
"Depending on the project, you might want to purge the HTTP cache for the product catalog."

When would I want to do this? What kind of project might require doing so?

2021-02-16 10:42 UTC, dabrt commented on docs/guide/shop_features/catalog.md
> +You can use one of two data providers: the Repository data provider and the eContent data provider.
```suggestion
You can use one of the following data providers: the Repository data provider and the eContent data provider.
```

2021-02-16 11:00 UTC, DominikaK commented on docs/guide/econtent/staging_system.md
> +Depending on the project, you should purge the HTTP cache for the product catalog.
```suggestion
Depending on the project, you might want to purge the HTTP cache for the product catalog.
```

2021-02-18 13:53 UTC, dabrt commented on docs/guide/econtent/indexing_econtent_data.md
> +|`siso_search.default.solr_spellcheck`|Enables or disables the Solr spellchecker (aka the "Did you mean?" functionality).|
I am thinking whether the "aka" is not overly colloqial. I could be used in legal documents or criminal records but in tech doc I think "i.e." could fit better. WDYT?

2021-02-18 13:53 UTC, dabrt approved these changes
Please see one comment

2021-02-18 13:55 UTC, DominikaK commented on docs/guide/econtent/indexing_econtent_data.md
> +|`siso_search.default.solr_spellcheck`|Enables or disables the Solr spellchecker (aka the "Did you mean?" functionality).|
```suggestion
|`siso_search.default.solr_spellcheck`|Enables or disables the Solr spellchecker (the "Did you mean?" functionality).|
```

2021-02-19 12:53 UTC, merged