EZP-32239: ERP revision
ezsystems/developer-documentation pull request #1307
Opened 2021-02-15 12:53 UTC by DominikaK

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/EZP-32239
| Versions      | 3.x, master

2021-02-16 14:03 UTC, dabrt requested changes

2021-02-16 14:03 UTC, dabrt commented on docs/guide/shop_features/erp.md
> +[[= product_name =]] can be connected to ERP systems. Out of the box it offers connection for the Microsoft Dynamics ERP.
```suggestion
[[= product_name =]] can be connected to ERP systems. 
Out of the box, it offers connection for the Microsoft Dynamics ERP.
```

2021-02-16 14:03 UTC, dabrt commented on docs/guide/shop_features/erp.md
> +Existing ERP customers can automatically create an account in the shop without waiting for confirmation from the administrator.
```suggestion
Existing ERP customers can automatically create an account in the shop without waiting for a confirmation from the administrator.
```

2021-02-16 14:03 UTC, dabrt commented on docs/guide/shop_features/erp.md
> +[[= product_name =]] requests real-time stock information from the ERP
```suggestion
[[= product_name =]] requests real-time stock information from the ERP system
```

2021-02-16 14:03 UTC, dabrt commented on docs/guide/shop_features/erp.md
> +A fallback price provider (e.g. using imported prices) can be configured. It is used if ERP is not available.
```suggestion
A fallback price provider can be configured (for example, one that uses imported prices). 
It is used if ERP is not available.
```

2021-02-16 14:18 UTC, DominikaK commented on docs/guide/erp_integration/erp_communication.md
> +A response sent to the shop from ERP can contain more information about a product than was requested.
```suggestion
A response that ERP sends to the shop can contain more information about a product than was requested.
```

2021-02-16 14:20 UTC, DominikaK commented on docs/guide/erp_integration/erp_logging.md
> +You can use a command to check which messages were exchanged with the ERP system.
```suggestion
You can use a command to check the messages that were exchanged with the ERP system.
```

2021-02-16 14:21 UTC, DominikaK commented on docs/guide/erp_integration/erp_logging.md
> +The mapping step is optional and depends on the concrete implementation of the transport and the configuration of the message.
"concrete implementation" is a functioning term, see for example https://en.wikipedia.org/wiki/Abstract_factory_pattern

2021-02-16 14:23 UTC, DominikaK commented on docs/guide/erp_integration/remotepriceprovider.md
> +If they are not set, it uses the numbers set in the BuyerParty.
```suggestion
If they are not set, it uses the numbers set in the Buyer Party.
```

2021-02-16 14:24 UTC, DominikaK commented on docs/guide/erp_integration/remotepriceprovider.md
> +If neither customer nor contact number are set, and template debitor is enabled in the configuration,
"template debitor", unfortunately, is a domain term, see https://doc.ibexa.co/en/latest/guide/pricing/price_api/standardtemplatedebitorservice

2021-02-18 16:54 UTC, dabrt approved these changes

2021-02-19 13:14 UTC, merged