EZP-32195 - Perso API documentation rewrite pt. 2
ezsystems/developer-documentation pull request #1323
Opened 2021-03-03 09:52 UTC by dabrt

| Question      | Answer |
| ------------- | --- |
| JIRA Ticket   | EZP-32195 |
| Versions      | 3.x, master |

Let's make just a little bit better. Not perfect but better. And then let's come back and make it top notch.

2021-03-03 11:54 UTC, DominikaK requested changes

2021-03-03 11:54 UTC, DominikaK commented on docs/guide/personalization/best_practices/tracking_integration.md
> +# Tracking integration
Change name on mkdocs.yml as well

2021-03-03 11:54 UTC, DominikaK commented on docs/guide/personalization/best_practices/tracking_integration.md
> +The simplest way is to generate code of a tiny image and put it on the webpage where the event must be sent (pixel tracking).
```suggestion
The simplest way is to generate code of a tiny image and put it on the webpage where the event must be sent
(this is called pixel tracking).
```

2021-03-03 11:54 UTC, DominikaK commented on docs/guide/personalization/best_practices/tracking_integration.md
> +The most important drawback is an increase in the request time by the time of the event request.
```suggestion
The most important drawback is that the event request increases the general request time. 
```
to misleading double meaning of "by the time"

2021-03-03 11:54 UTC, DominikaK commented on docs/guide/personalization/best_practices/tracking_integration.md
> +could grow and lead to a stalled and finally crashing HTTP service.
```suggestion
If the network is overloaded or the recommendation engine is not available,
the number of requests could grow and lead to a stalled and finally crashing HTTP service. 
```

2021-03-03 11:54 UTC, DominikaK commented on docs/guide/personalization/best_practices/tracking_integration.md
> +the client just before sending the events.
```suggestion
You can place the code at the very end of the generating script
and flush the output buffer to the client just before sending the events. 
```

2021-03-03 11:54 UTC, DominikaK commented on docs/guide/personalization/best_practices/tracking_integration.md
> +for the end customer.
```suggestion
The connection to the browser might remain open for the time of processing,
but it will be transparent for the end customer.
```

2021-03-03 11:54 UTC, DominikaK commented on docs/guide/personalization/best_practices/tracking_integration.md
> +The server merely forwards requests to the recommendation engine.
```suggestion
The server only forwards requests to the recommendation engine. 
```

2021-03-03 11:54 UTC, DominikaK commented on docs/guide/personalization/best_practices/tracking_integration.md
> +It can be a simple implemented Apache proxy module, an independent daemon (like “netcat”), or a PHP script.
```suggestion
It can be a simple implemented Apache proxy module, an independent daemon (like "netcat"), or a PHP script.
```

2021-03-03 11:54 UTC, DominikaK commented on docs/guide/personalization/best_practices/tracking_integration.md
> +    An Ibexa-recommended solution is to use pixel tracking for non-complex events, or where every page is generated on the server side without any caching logic. For hints about preloading image URLs
```suggestion
    An Ibexa-recommended solution is to use pixel tracking for non-complex events,
    or where every page is generated on the server side without any caching logic.
    For hints about preloading image URLs with JavaScript elements (`var img = new Image(); img.src="uri"`)
    or without them (`&lt;img src="uri"... /&gt;`), see [How to Preload Images](https://www.mediacollege.com/internet/javascript/image/preload.html).
```

2021-03-03 11:54 UTC, DominikaK commented on docs/guide/personalization/best_practices/tracking_integration.md
> +    If you plan to implement caching mechanisms and more complex events like consume (depending on viewing time of the page), basket (which is usually an in-page event) or custom in-page events that
```suggestion
    If you plan to implement caching mechanisms and more complex events like consume
    (depending on the viewing time of the page), basket (which is usually an in-page event)
    or custom in-page events that take place on the client side,
    a JavaScript implementation is strongly encouraged.
    For a sample script and instructions, see [Tracking with yct.js](../developer_guide/tracking_with_yct.md).
```

2021-03-03 11:54 UTC, DominikaK commented on docs/guide/personalization/developer_guide/tracking_api.md
> +- Clickrecommended - When a user click a recommendation
```suggestion
- Clickrecommended - When a user clicks a recommendation
```

2021-03-03 11:54 UTC, DominikaK commented on docs/guide/personalization/developer_guide/tracking_api.md
> +eCcommerce mostly uses the term "product", whereas the Publisher domain widely uses the terms "content",
```suggestion
eCommerce mostly uses the term "product", whereas the Publisher domain widely uses the terms "content", 
```

2021-03-03 11:54 UTC, DominikaK commented on docs/guide/personalization/developer_guide/tracking_api.md
> +This document is intended for use in eCommerce and content publishing scenarios.
Aren't these the only two scenarios? ATM it sound like here were some others tat a documented elsewhere, so maybe like this:
```suggestion
You can use the tracking API both in eCommerce and content publishing scenarios. 
```

2021-03-03 11:54 UTC, DominikaK commented on docs/guide/personalization/developer_guide/tracking_api.md
> +    Even if item ids cannot overlap in a customer's system, we strongly recommend using different item
```suggestion
    Even if item IDs cannot overlap in a customer's system, we strongly recommend using different item 
```

2021-03-03 11:54 UTC, DominikaK commented on docs/guide/personalization/developer_guide/tracking_api.md
> +If there's a login mechanism, the user is usually tracked with a temporary identifier before the login.
```suggestion
If there is a login mechanism, the user is usually tracked with a temporary identifier before the login. 
```

2021-03-03 11:54 UTC, DominikaK commented on docs/guide/personalization/developer_guide/tracking_api.md
> +At this point a pseudonymous user ID, for example, a system's internal registration id, must be used. 
I think "pseudonymous" needs an explanation.

2021-03-03 11:54 UTC, DominikaK commented on docs/guide/personalization/developer_guide/tracking_api.md
> +People responsible for the sales policy in place in your organiation must decide what should be presented as recommendations on the website.
```suggestion
Persons responsible for the sales policy in place in your organization must decide what should be presented as recommendations on the website. 
```

2021-03-03 11:54 UTC, DominikaK commented on docs/guide/personalization/developer_guide/tracking_api.md
> +By default, it is not possible to track SKUs but recommend MIIs.
MII could use an explanation (SKU is used throughout commerce doc anyway nad is a bit clearer, I think)

2021-03-03 11:54 UTC, DominikaK commented on docs/guide/personalization/developer_guide/tracking_api.md
> +The following example discusses a decision making situation that is typical for eCommerce business:
```suggestion
The following use case is typical for eCommerce business:
```

2021-03-03 11:54 UTC, DominikaK commented on docs/guide/personalization/developer_guide/tracking_api.md
> +End users who browse through the shop **probably get recommendations of the same item that is
```suggestion
End users who browse through the shop *probably get recommendations of the same item that is 
```

2021-03-03 11:54 UTC, DominikaK commented on docs/guide/personalization/developer_guide/tracking_api.md
> +currently displayed but in a different size and/or color, a so-called "variant"**.
```suggestion
currently displayed but in a different size and/or color, a so-called "variant"*. 
```

2021-03-03 11:54 UTC, DominikaK commented on docs/guide/personalization/developer_guide/tracking_api.md
> +This results in recommendations **that do not contain variations of the currently shown item**.
```suggestion
This results in recommendations *that do not contain variations of the currently shown item*. 
```

2021-03-03 11:54 UTC, DominikaK commented on docs/guide/personalization/developer_guide/tracking_api.md
> +nd parameter "quantity" to 4.
```suggestion
and parameter "quantity" to 4.
```

2021-03-03 11:54 UTC, DominikaK commented on docs/guide/personalization/developer_guide/tracking_api.md
> +It is highly desirable to correlate both IDs to correlate the buy events (account ID) with
```suggestion
It is highly recommended to correlate both IDs to correlate the buy events (account ID) with 
```

```suggestion
You should correlate both IDs to correlate the buy events (account ID) with 
```

2021-03-03 11:54 UTC, DominikaK commented on docs/guide/personalization/developer_guide/tracking_api.md
> +    Based on feedback of our customers and to make the purpose a bit clearer, we renamed the formerly named 'transfer' event to 'login'. As the name implies, it should be used when a user logs in. It
To consider in future: when was the "former" name used? Is it still relevant for the current audience, that it, could they have encountered the old name at all?

2021-03-03 11:54 UTC, DominikaK commented on docs/guide/personalization/developer_guide/tracking_api.md
> +This can also be used for explicit ratings like a five-star rating or any other liquor scale-based rating.
Liquor? That sound like a leftover from some example that vanished in the meantime.

2021-03-03 11:54 UTC, DominikaK commented on docs/guide/personalization/developer_guide/tracking_api.md
> +Sending Rendered Events causes as much requests as recommendations to be displayed,
```suggestion
Sending Rendered Events causes as many requests as recommendations to be displayed, 
```

2021-03-09 07:32 UTC, DominikaK commented on docs/guide/personalization/developer_guide/tracking_api.md
>  |Domain||Item ID|Item Type|
```suggestion
|Domain|Item ID|Item Type|
```
as it's three columns below

2021-03-09 07:33 UTC, DominikaK approved these changes

2021-03-09 07:53 UTC, miklas-ez approved these changes

2021-03-09 09:36 UTC, merged