Extending the Image Editor
ezsystems/developer-documentation pull request #1332
Opened 2021-03-11 13:02 UTC by dabrt

| Question      | Answer |
| ------------- | --- |
| JIRA Ticket   |  |
| Versions      | master, 3.x |

Describe how developers can extend the image editor

2021-03-11 14:38 UTC, dabrt commented on docs/extending/extending_image_editor.md
> +In `assets/random-dot/`, create the `random-dot.js` file with the following code of the React component:
```suggestion
In `assets/random_dot/`, create the `random-dot.js` file with the following code of the React component:
```

2021-03-11 14:43 UTC, dew326 requested changes

2021-03-11 14:43 UTC, dew326 commented on code_samples/back_office/image_editor/config/webpack.config.js
> +eZConfigManager.add({
This should be somewhere before the `module.exports = [ eZConfig, ...customConfigs, projectConfig ];`

2021-03-11 14:43 UTC, dew326 commented on code_samples/back_office/image_editor/config/webpack.config.js
> +  newItems: [ path.resolve(__dirname, './assets/js/dot-action.js'), ],
```suggestion
  newItems: [ path.resolve(__dirname, './assets/random_dot/random-dot.js'), ], 
```

2021-03-11 14:51 UTC, dabrt commented on code_samples/back_office/image_editor/config/webpack.config.js
> +  newItems: [ path.resolve(__dirname, './assets/js/dot-action.js'), ],
```suggestion
  newItems: [ path.resolve(__dirname, './assets/random_dot/random_dot.js'), ], 
```

2021-03-11 14:52 UTC, dabrt commented on code_samples/back_office/image_editor/config/webpack.config.js
> +  newItems: [ path.resolve(__dirname, './assets/random_dot/random_dot.js'), ],
```suggestion
  newItems: [ path.resolve(__dirname, './assets/random_dot/random-dot.js'), ], 
```

2021-03-12 07:32 UTC, DominikaK requested changes

2021-03-12 07:32 UTC, DominikaK commented on code_samples/back_office/image_editor/config/packages/image_editor.yaml
> +                            (...)
```suggestion
                            # ...
```
Otherwise copy-paste will cause errors.

2021-03-12 07:32 UTC, DominikaK commented on docs/extending/extending_image_editor.md
> +Learn how to do this by following the steps below.
As the scenario here is not really a real-life use case (I think?), how about emphasising that it's just an example?:
```suggestion

The following example shows how to extend the Image Editor
by adding a button that draws a dot at a random location on the image.
```

2021-03-12 07:32 UTC, DominikaK commented on docs/extending/extending_image_editor.md
> +The code does not perform any action, you add the action in the following steps.
```suggestion
The code does not perform any action yet, you add the action in the following steps.
```
or
```suggestion
The code itself does not perform any action, you add the action in the following steps.
```
?

2021-03-12 07:32 UTC, DominikaK commented on docs/extending/extending_image_editor.md
> +Depending on whether and where you [modified the default settings](../guide/image_editor.md#configuration), in `config/packages`, either modify the `ezplatform.yaml` file or create the `image_editor.
```suggestion
Depending on whether you [modified the default settings](../guide/image_editor.md#configuration), and where you did it,
in `config/packages` either modify the `ezplatform.yaml` file, or create the `image_editor.yaml`
by adding settings similar to the following example:
```

2021-03-12 07:32 UTC, DominikaK commented on docs/extending/extending_image_editor.md
> +# Extending the Image Editor
```suggestion
# Extending Image Editor
```

2021-03-12 07:32 UTC, DominikaK commented on docs/extending/extending_image_editor.md
> +    Before you restart [[= product_name_exp =]], run `php bin/console cache:clear` and `yarn encore <dev|prod>` to regenerate the assets.
```suggestion
    Before you restart [[= product_name =]], run `php bin/console cache:clear` and `yarn encore <dev|prod>` to regenerate the assets.
```

2021-03-12 07:32 UTC, DominikaK commented on docs/extending/extending_image_editor.md
> +- TechnicalCanvasContext - Stores a canvas, which you can use to draw elements that help modify the image, for example, a crop area or a grid, without interrupting with the actual image
```suggestion
- CanvasContext - stores a canvas that displays the image, on which you can modify the image
- ImageHistoryContext - stores the image history used by the Undo/Redo feature
- AdditionalDataContext - stores additional data that is attached to the image, for example, focal point coordinates
- TechnicalCanvasContext - stores a canvas, which you can use to draw elements that help modify the image, for example, a crop area or a grid, without interrupting with the actual image
```

2021-03-12 07:32 UTC, DominikaK commented on docs/extending/extending_image_editor.md
> +The last context is not used it in this example.
```suggestion
The last context is not used in this example.
```

2021-03-12 07:32 UTC, DominikaK commented on docs/extending/extending_image_editor.md
> +<summary>Complete controller code</summary>
```suggestion
<summary>Complete component code</summary>
```
is it a component?

2021-03-12 07:32 UTC, DominikaK commented on code_samples/back_office/image_editor/config/webpack.config.js
> +});`
```suggestion
});
```
maybe a typo?

2021-03-12 07:32 UTC, DominikaK commented on code_samples/back_office/image_editor/config/packages/image_editor.yaml
> +        <siteaccess>:
How about:
```suggestion
        site:
```
so we can test the file instantly, without modifications

2021-03-12 11:00 UTC, DominikaK approved these changes

2021-03-12 11:04 UTC, merged

2021-03-12 11:05 UTC, dew326 approved these changes

2021-03-12 12:44 UTC, GrabowskiM approved these changes