EZEE-3003: Database update script
ezsystems/developer-documentation pull request #1347
Opened 2021-04-07 09:07 UTC by DominikaK

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/EZEE-3003
| Versions      | all

Note: merge after relevant releases are out.

2021-04-07 09:17 UTC, webhdx requested changes

2021-04-07 09:17 UTC, webhdx commented on docs/updating/4_update_2.5.md
> +ALTER TABLE ezpage_attributes MODIFY value LONGTEXT;
It should probably clearly state that query is only meant for MySQL.

2021-04-07 09:17 UTC, webhdx commented on docs/updating/4_update_3.2.md
> +ALTER TABLE ezpage_attributes MODIFY value LONGTEXT;
In 3.2 you should run queries from the *.sql file: `upgrade/db/mysql/ezplatform-3.2.5-to-3.2.6.sql`

2021-04-07 09:17 UTC, webhdx commented on docs/updating/updating_to_3.3.md
> +ALTER TABLE ezpage_attributes MODIFY value LONGTEXT;
In 3.3 we moved upgrade scripts to `vendor/ibexa/installer/upgrade/db/` so developers should run scripts like in 3.2:
`mysql -u <username> -p <password> <database_name> < vendor/ibexa/installer/upgrade/db/mysql/ibexa-3.3.1-to-3.3.2.sql`

2021-04-07 11:53 UTC, mnocon approved these changes

2021-04-15 14:04 UTC, dabrt approved these changes

2021-04-15 14:04 UTC, dabrt commented on docs/updating/4_update_2.5.md
> +To update to v2.5.18, additionally run the following update script, if you are using MySQL:
```suggestion
To update to v2.5.18, if you are using MySQL, additionally run the following update script:
```

2021-04-15 14:04 UTC, dabrt commented on docs/updating/4_update_3.2.md
> +To update to v3.2.6, additionally run the following update script, if you are using MySQL:
```suggestion
To update to v3.2.6, if you are using MySQL, additionally run the following update script:
```

2021-04-15 14:04 UTC, dabrt commented on docs/updating/updating_to_3.3.md
> +To update to v3.3.2, additionally run the following update script, if you are using MySQL:
```suggestion
To update to v3.3.2, if you are using MySQL, additionally run the following update script:
```

2021-04-16 08:32 UTC, webhdx approved these changes

2021-05-06 10:38 UTC, merged