IBX-297: Allow random sorting in ES
ezsystems/developer-documentation pull request #1371
Opened 2021-05-13 09:06 UTC by DominikaK

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-297
| Versions      | master

2021-05-13 09:16 UTC, adamwojs approved these changes

2021-05-19 09:47 UTC, juskora requested changes

2021-05-19 09:47 UTC, juskora commented on docs/guide/search/sort_clause_reference/random_sort_clause.md
> +In Elastic search engine, you cannot combine the `Random` Sort Clause with any other Sort Clause.
```suggestion
In Elasticsearch engine, you cannot combine the `Random` Sort Clause with any other Sort Clause.
```

2021-05-19 10:21 UTC, juskora approved these changes

2021-05-19 11:32 UTC, merged