IBX-118: Create reusable Commerce JS components
ezsystems/developer-documentation pull request #1373
Opened 2021-05-13 13:44 UTC by DominikaK

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-118
| Versions      | master

2021-05-13 13:58 UTC, DominikaK commented on docs/guide/quick_order/quick_order_templates.md
> +| `ShopFrontendBundle/Resources/views/themes/standard/QuickOrder/quick_order_empty_line.html.twig` | An empty line innthe quick order form. |
```suggestion
| `ShopFrontendBundle/Resources/views/themes/standard/QuickOrder/quick_order_empty_line.html.twig` | An empty line in the quick order form. |
```

2021-05-13 13:59 UTC, lucasOsti approved these changes

2021-05-17 06:56 UTC, juskora commented on docs/guide/basket/wishlist_and_stored_baskets.md
> +|`src/Siso/Bundle/ShopFrontendBundle/Resources/views/themes/standard/Basket/stored_baskets_list.html.twig`|List of all stored baskets|
```suggestion
|`src/Siso/Bundle/ShopFrontendBundle/Resources/views/themes/standard/Basket/stored_baskets_list.html.twig`|List of all stored baskets.|
```

2021-05-17 06:57 UTC, juskora commented on docs/guide/basket/wishlist_and_stored_baskets.md
> +|`ShopFrontendBundle/Resources/views/themes/standard/Basket/show_stored_basket.html.twig`|Entry page for both wishlists and stored baskets. Based on the basket type, it loads one of the templates lis
```suggestion
|`ShopFrontendBundle/Resources/views/themes/standard/Basket/show_stored_basket.html.twig`|Entry page for both wishlists and stored baskets. Based on the basket type, it loads one of the templates listed below.|
```

2021-05-17 06:57 UTC, juskora commented on docs/guide/basket/wishlist_and_stored_baskets.md
> +|`ShopFrontendBundle/Resources/views/themes/standard/Basket/show_stored_basket_part.html.twig`|Partial page responsible for rendering a stored basket page|
```suggestion
|`ShopFrontendBundle/Resources/views/themes/standard/Basket/show_stored_basket_part.html.twig`|Partial page responsible for rendering a stored basket page.|
```

2021-05-17 07:03 UTC, juskora requested changes

2021-05-18 06:18 UTC, juskora approved these changes

2021-05-18 06:21 UTC, merged