IBX-386: Extended DAM configuration
ezsystems/developer-documentation pull request #1390
Opened 2021-05-31 07:47 UTC by juskora

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-386
| Versions      |

2021-06-08 08:13 UTC, mateuszbieniek requested changes

2021-06-09 07:37 UTC, mateuszbieniek approved these changes

2021-06-11 14:30 UTC, dabrt requested changes

2021-06-11 14:30 UTC, dabrt commented on docs/guide/config_connector.md
> +Next, define the created custom template for embed viewType matched for the DAM Image Content Type. For more information about displaying content, see [Content rendering](../guide/content_rendering.m
```suggestion
Next, in `config/packages/ezplatform.yaml`, set the `dam.html.twig` template for the `embed` view type that is matched for the Content Type, which you created for DAM images. 
For more information about displaying content, see [Content rendering](../guide/content_rendering.md).
```
"for the Content Type that you create for DAM images" - unless DXP comes with a built-in content type for DAM images?

2021-06-11 14:30 UTC, dabrt commented on docs/guide/config_connector.md
> +In the `config/packages/ezplatform.yaml` add the following configuration:
```suggestion
In the same YAML file, add the following configuration:
```

2021-06-11 14:30 UTC, dabrt commented on docs/guide/config_connector.md
> +You can customize the parameters according to your needs. For more information about supported parameters, see the [Unsplash documentation](https://unsplash.com/documentation#dynamically-resizable-im
```suggestion
You can customize the parameters according to your needs. 
For more information about supported parameters, see the [Unsplash documentation](https://unsplash.com/documentation#dynamically-resizable-images).
```

2021-06-11 14:30 UTC, dabrt commented on docs/guide/config_connector.md
> +In the Back Office go to **Admin** > **Content Types** and in the **Content** group create a Content Type with the Image Asset Field.
```suggestion
In the Back Office, go to **Admin** > **Content Types**.
In the **Content** group, create a Content Type for DAM images, which includes the ImageAsset Field. 
```
Image Asset or ImageAsset?

Shouldn't the content type be created beforehands if we are supposed to provide the <dam_image_content_type_identifier> above?

2021-06-11 14:30 UTC, dabrt commented on docs/guide/config_connector.md
> +For more information about blocks customization (defined templates, variations), see [Create custom block](../tutorials/enterprise_beginner/4_create_a_custom_block.md).
```suggestion
For more information about block customization (defined templates, variations), see [Create custom block](../tutorials/enterprise_beginner/4_create_a_custom_block.md).
```

2021-06-15 12:11 UTC, juskora commented on docs/guide/config_connector.md
> +The `770px` parameter in the template above is used to render the DAM image. It is the `unsplash` specific image variation and must be defined separately.
In that case, the term should stay as it is -> parameter, not value. I'm aware of this term but here it should be also used as the image variation but with the note that it is specific for the unsplash.

2021-06-16 12:13 UTC, dabrt approved these changes

2021-06-17 08:38 UTC, merged