IBX-401 - Adding custom page block validators
ezsystems/developer-documentation pull request #1396
Opened 2021-06-15 14:48 UTC by dabrt

| Question      | Answer |
| ------------- | --- |
| JIRA Ticket   | IBX-401 |
| Versions      | 2.5 and up |

Modify
https://doc.ibexa.co/en/latest/extending/extending_page/
to describe adding custom page block validators

2021-06-16 10:25 UTC, Nattfarinn requested changes

2021-06-16 10:25 UTC, Nattfarinn commented on docs/extending/extending_page.md
> +In `src/Validator`, create a `AlphaOnly.php` class that performs the validation.
```suggestion
In `src/Validator`, create a `AlphaOnlyValidator.php` class that performs the validation.
```

2021-06-16 11:37 UTC, dabrt commented on docs/extending/extending_page.md
> +    my_custom_validator: 'Symfony\Component\Validator\Constraint\AlphaOnly'
```suggestion
    my_custom_validator: 'App\Validator\AlphaOnly'
```

2021-06-16 11:38 UTC, Nattfarinn approved these changes

2021-06-16 11:43 UTC, dabrt commented on docs/extending/extending_page.md
> +|`validators`|`not_blank` and `regexp` validators are readily available. You can add [custom validators](#custom_validators), if necessary.|
```suggestion
|`validators`|`not_blank` and `regexp` validators are readily available. You can add [custom validators](#custom-validators), if necessary.|
```

2021-06-17 07:43 UTC, juskora approved these changes

2021-06-17 11:14 UTC, merged