Http cache redesign
ezsystems/developer-documentation pull request #1403
Opened 2021-06-29 07:41 UTC by juskora

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-400
| Versions      | 2.5+

Most of the content from https://github.com/ezsystems/ezplatform-http-cache/tree/master/docs/ is included in the documentation. 
Files: parameters.vcl and varnish5.vcl need to be relocated to be able to delete the docs folder.

2021-06-29 08:25 UTC, dabrt reviewed
At a first glance, the article seems very long. Can we split it into several articles under a common top level article?
Something like:
- HTTP Cache
-- HTTP Cache Configuration
-- Symfony reverse proxy and its replacements (this one might require further atomization into "tasks" or "master tasks"
-- Context-aware HTTP cache
-- Content-aware HTTP cache

Once split, I'd add links between articles to definitions of terms that have been presented earlier (like "purge" for example, which might appear in various places but has been explained early)

I'd add an explanation of TLAs and other terms that might occur throughout the article but have no definition, like VCL or FOS. (Expand them in each first occurrence in the resulting sub-articles.

2021-07-07 09:35 UTC, ViniTou reviewed
I would just say that some filenames are kinda not related to whats inside as those docs from cache repo were kinda all mashed together.
Mostly in `symfony_reverse_proxy.md` where we have reverse proxy, fastly and captcha

2021-07-07 09:35 UTC, ViniTou commented on mkdocs.yml
> +              - 'Content-aware HTTP cache': 'guide/cache/content_aware_cache.md'
this is twice here.

2021-07-14 10:03 UTC, DominikaK requested changes

2021-07-15 05:05 UTC, DominikaK approved these changes

2021-07-16 06:50 UTC, ViniTou approved these changes

2021-07-16 09:25 UTC, merged