IBX-459: Add customer view matcher
ezsystems/developer-documentation pull request #1423
Opened 2021-07-19 13:14 UTC by DominikaK

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-459
| Versions      | master, 3.3

2021-07-19 13:16 UTC, DominikaK commented
Note for dev review: the original code this was partially based on registers the matcher as a service with `tags: ['ezplatform.view.matcher']`, but I'm not sure if that's strictly necessary (the example worked as provided).

2021-07-20 16:00 UTC, adriendupuis requested changes
There is easier way to get the $contentInfo

2021-07-20 16:00 UTC, adriendupuis commented on code_samples/front/view_matcher/src/View/Matcher/Owner.php
> +        return $this->hasOwner($this->getRepository()->getContentService()->loadContentInfo($location->getContent()->id));
```suggestion
        return $this->hasOwner($location->getContentInfo());
```

2021-07-20 16:00 UTC, adriendupuis commented on code_samples/front/view_matcher/src/View/Matcher/Owner.php
> +        return $this->hasOwner($location);
```suggestion
        return $this->hasOwner($contentInfo);
```

2021-07-20 16:21 UTC, adriendupuis commented
> Note for dev review: the original code this was partially based on registers the matcher as a service with `tags: ['ezplatform.view.matcher']`, but I'm not sure if that's strictly necessary (the example worked as provided).

@DominikaK  It is not necessary with this example. It is used when the matcher is a service instead of a simple class. It is a bit advanced. An example of a service used as a matcher can be found on https://doc.ibexa.co/en/latest/guide/content_rendering/queries_and_controllers/content_queries/#content-view-configuration (and the tag usage itself is at https://github.com/ezsystems/ezplatform-query-fieldtype/blob/v2.3.1/src/Symfony/Resources/config/services/ezplatform.yaml#L37). If this must be exposed in the doc, a new example must be written or the query field type used as the example but this is a new subject.

2021-07-21 07:32 UTC, adriendupuis commented on docs/guide/content_rendering/templates/custom_view_matcher.md
> +- `match` - matches the view against a set of matchers.
```suggestion
- `match` - checks if the View object matches.
```

2021-07-21 07:35 UTC, adriendupuis commented on docs/guide/content_rendering/templates/custom_view_matcher.md
> +    If you use a matcher that is a service instead of a simple class,
👍

2021-07-21 07:46 UTC, adriendupuis approved these changes
This looks good.

2021-07-27 16:55 UTC, dabrt approved these changes

2021-07-27 16:55 UTC, dabrt commented on docs/guide/content_rendering/templates/custom_view_matcher.md
> +To apply the matcher in view configuration, indicate it by its fully qualified class name, preceded by `\`.
```suggestion
To apply the matcher in view configuration, indicate the matcher by its fully qualified class name, preceded by `\`.
```

2021-07-27 16:55 UTC, dabrt commented on docs/guide/content_rendering/templates/custom_view_matcher.md
> +    you need to tag the service with `ezplatform.view.matcher`.
```suggestion
    tag the service with `ezplatform.view.matcher`.
```

2021-07-28 06:52 UTC, DominikaK commented on docs/guide/content_rendering/templates/custom_view_matcher.md
> +To do it, create a matcher class that extends `eZ\Publish\Core\MVC\Symfony\Matcher\ContentBased\MultipleValued`.
Presumably yes, but that will be handled together with the rest of the rebranding, and this PR goes to 3.3 as well, which will not be affected.

2021-07-28 13:26 UTC, merged