IBX-704: LocationChildrenTermAggregation
ezsystems/developer-documentation pull request #1430
Opened 2021-08-03 13:11 UTC by DominikaK

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-704
| Versions      | 3.3, master

2021-08-03 13:16 UTC, mateuszbieniek requested changes

2021-08-03 13:16 UTC, mateuszbieniek commented on docs/guide/search/aggregation_reference/locationchildrenterm_aggregation.md
> +$query = new Query();
I think it should be:
```suggestion
$query = new LocationQuery();
```
As this is a Location Aggregation (only supported for Location Queries)

2021-08-03 13:20 UTC, mateuszbieniek approved these changes

2021-08-03 13:23 UTC, adamwojs approved these changes

2021-08-04 11:53 UTC, dabrt approved these changes

2021-08-04 13:16 UTC, merged