IBX-154 - Oprional alt text for Image FT
ezsystems/developer-documentation pull request #1433
Opened 2021-08-04 14:52 UTC by dabrt

| Question      | Answer |
| ------------- | --- |
| JIRA Ticket   | IBX-154 |
| Versions      | 2.5 and up |

Alternative text is optional by default, it can be set as required when adding an FT to content type.

2021-08-12 15:37 UTC, dabrt commented
@adamwojs Please find 5 minutes to look at this PR

2021-08-13 06:08 UTC, adamwojs approved these changes

2021-08-13 06:08 UTC, adamwojs commented on docs/tutorials/enterprise_beginner/1_get_a_starter_website.md
> +
Selecting alternative text as mandatory should be our recommendation here. It's usually (and by default) used as `alt` attribute value and it's its value must not be empty. 

Ref. https://html.spec.whatwg.org/multipage/images.html#general-guidelines

2021-08-13 10:36 UTC, dabrt commented on docs/api/field_types_reference/imagefield.md
> +|`alternativeText`|string|`Picture of an apple.`|The alternative text, as entered in the Field's properties. This property is optional. You can require the alternative text for an image when you add
```suggestion
|`alternativeText`|string|`Picture of an apple.`|The alternative text, as entered in the Field's properties. This property is optional. It is recommended that you require the alternative text for an image when you add the Image Field to a Content Type, by toggling the "Alternative text is required" checkbox.|
```

2021-08-13 10:36 UTC, dabrt commented on docs/tutorials/enterprise_beginner/1_get_a_starter_website.md
> +    In some cases you might want to require an alternative text for the image.
```suggestion
    It is recommended that you require an alternative text for the image. 
```

2021-08-13 10:53 UTC, juskora requested changes

2021-08-13 10:53 UTC, juskora commented on docs/api/field_types_reference/imagefield.md
> +|`alternativeText`|string|`Picture of an apple.`|The alternative text, as entered in the Field's properties. This property is optional. It is recommended that you require the alternative text for an
```suggestion
|`alternativeText`|string|`Picture of an apple.`|The alternative text, as entered in the Field's properties. This property is optional. It is recommended that you require the alternative text for an image when you add the Image Field to a Content Type, by selecting the "Alternative text is required" checkbox.|
```

2021-08-13 10:58 UTC, juskora approved these changes

2021-08-13 11:10 UTC, merged