IBX-972: ImageAsset and ContentTypeGroupLimition doesn't work for already created content
ezsystems/developer-documentation pull request #1456
Opened 2021-09-22 09:52 UTC by vidarl

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | [IBX-972](https://jira.ez.no/browse/IBX-972)
| Versions      | 3.3

2021-09-23 08:31 UTC, alongosz approved these changes

2021-09-24 09:36 UTC, DominikaK requested changes

2021-09-24 09:36 UTC, DominikaK commented on docs/updating/updating_to_3.3.md
> +    ```
```suggestion
    ``` sql
```

2021-09-24 09:36 UTC, DominikaK commented on docs/updating/updating_to_3.3.md
> +    ```
```suggestion
    ``` sql
```

2021-09-24 09:36 UTC, DominikaK commented on docs/updating/updating_to_3.3.md
> +Apply the following database update script:
```suggestion
To update to v3.3.9, additionally run the following update script:
```
That's just to be consistent with earlier sections.

2021-09-24 10:54 UTC, DominikaK approved these changes

2021-09-29 06:06 UTC, merged