EZP-32155: Add a custom limitation example
ezsystems/developer-documentation pull request #1461
Opened 2021-09-28 17:19 UTC by adriendupuis

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | [EZP-32155](https://issues.ibexa.co/browse/EZP-32155)
| Versions      | 3.3

* Custom Limitation example
* Custom Policy adjustment

TODO:
* TODOs in the .md
* Enhance explanations
* Use XLIFF for translations

2021-09-28 17:20 UTC, adriendupuis commented on docs/guide/custom_policies.md
> -If you want to completely override the way of rendering custom Limitation values in the role view,
This is not optional but mandatory

`An exception has been thrown during the rendering of a template ("Could not find a block for CustomLimitation: ez_limitation_customlimitation_value.").`

2021-09-28 17:22 UTC, adriendupuis commented on docs/guide/custom_policies.md
> -    If you skip this part, Limitation values will be rendered using an [`ez_limitation_value_fallback`](https://github.com/ezsystems/repository-forms/blob/master/bundle/Resources/views/limitation_val
Have a better look to this. Maybe useful when using `MultipleSelectionBasedMapper`.

2021-09-29 09:53 UTC, adriendupuis commented on docs/guide/custom_policies.md
> -    If you skip this part, Limitation values will be rendered using an [`ez_limitation_value_fallback`](https://github.com/ezsystems/repository-forms/blob/master/bundle/Resources/views/limitation_val
https://github.com/ezsystems/repository-forms/blob/2.5/bundle/Resources/views/limitation_values.html.twig#L1
TODO: try if this fallback is used when there is no CustomLimitationValueMapper service.

2023-10-30 09:43 UTC, adriendupuis commented on docs/guide/custom_policies.md
> -    If you skip this part, Limitation values will be rendered using an [`ez_limitation_value_fallback`](https://github.com/ezsystems/repository-forms/blob/master/bundle/Resources/views/limitation_val
The fallback is used when the CustomLimitationValueMapper service is commented out.

2023-10-30 09:44 UTC, adriendupuis commented on docs/guide/custom_policies.md
> -If you want to completely override the way of rendering custom Limitation values in the role view,
As soon as a value mapper exist, the template is mandatory.

2023-10-30 14:43 UTC, adriendupuis commented on docs/guide/custom_policies.md
> +Any bundle can expose available Policies via a `PolicyProvider` which can be added to EzPublishCoreBundle's [service container](../api/public_php_api.md#service-container) extension.
```suggestion
Any bundle can expose available Policies via a `PolicyProvider` which can be added to EzPublishCoreBundle's [service container](public_php_api.md#service-container) extension.
```

2023-10-30 14:45 UTC, adriendupuis commented on docs/guide/custom_policies.md
> +- `getFormTemplate` returns the path to the template to use for rendering the limitation form. Here it use [`form_label`](https://symfony.com/doc/5.4/form/form_customization.html#reference-forms-twig
```suggestion
- `getFormTemplate` returns the path to the template to use for rendering the limitation form. Here it use [`form_label`]([[= symfony_doc =]]/form/form_customization.html#reference-forms-twig-label) and [`form_widget`]([[= symfony_doc =]]/form/form_customization.html#reference-forms-twig-widget) to do so.
```

2023-10-30 14:50 UTC, adriendupuis commented on docs/guide/custom_policies.md
> +- Each module can provide *functions* (For example, in `content/read`, "content" is the module, and "read" is the function)
```suggestion
- Each module can provide *functions* (for example, in `content/read`, "content" is the module, and "read" is the function)
```

2023-10-30 14:54 UTC, adriendupuis commented on docs/guide/custom_policies.md
> +<?php
```suggestion
<?php declare(strict_types=1);
```

2023-10-30 14:54 UTC, adriendupuis commented on docs/guide/custom_policies.md
> +<?php
```suggestion
<?php declare(strict_types=1);
```

2023-10-30 15:19 UTC, adriendupuis commented on docs/guide/custom_policies.md
> +Some abstract Limitation type form mapper classes are provided to help implementing common complexe Limitations.
```suggestion
Some abstract Limitation type form mapper classes are provided to help implementing common complex Limitations.
```

2023-10-30 16:05 UTC, adriendupuis commented
TODO: Update #2195, the equivalent for 4.5+, after review and merge.

2023-10-31 08:57 UTC, adamwojs approved these changes
+1 by please remember about code re-branding during merge up

2023-10-31 09:10 UTC, adriendupuis commented
> +1 by please remember about code re-branding during merge up

@adamwojs I'm pretty sure I forgot nothing in #2195 but will send it to review for being sure 😉

2023-11-06 17:23 UTC, adriendupuis commented on code_samples/back_office/limitation/translations/forms.en.yaml
> +role.policy.custom_module.custom_function_2: 'Custom module / Function #2'
TODO: Study #2205 for an example allowing `translation:extract` to generate this file (something like `php bin/console translation:extract en --domain=forms --dir=src --output-dir=translations`)

2023-11-08 09:24 UTC, MagdalenaZuba requested changes

2023-11-08 09:24 UTC, MagdalenaZuba commented on docs/guide/custom_policies.md
> +The value class extends `eZ\Publish\API\Repository\Values\User\Limitation` and says for which limitation it's used:
```suggestion
The value class extends `eZ\Publish\API\Repository\Values\User\Limitation` and specifies the limitation for which it's used:
```

2023-11-08 09:24 UTC, MagdalenaZuba commented on docs/guide/custom_policies.md
> +- `accept`, `validate` and `buildValue` implement the value class usage logic.
```suggestion
- `accept`, `validate` and `buildValue` implement the logic for using the value class.
```

2023-11-08 09:24 UTC, MagdalenaZuba commented on docs/guide/custom_policies.md
> +- `evaluate` challenges a limitation value against the current user, the subject object and other context objects to return if the limitation is satisfied or not. `evaluate` is, among others, used by
```suggestion
- `evaluate` assesses a limitation value against the current user, the subject object, and other context objects to determine if the limitation is satisfied or not. `evaluate` is used, among others places, by `PermissionResolver::canUser` (to check if a user with access to a function can use it in its limitations) and `PermissionResolver::lookupLimitations`.
```

2023-11-08 09:24 UTC, MagdalenaZuba commented on docs/guide/custom_policies.md
> +The type class is set as a service tagged `ezpublish.limitationType` with an alias to identify it, and to link it to the value.
```suggestion
The type class is registered as a service tagged with `ezpublish.limitationType` and given an alias to identify it, as well as to link it to the value.
```

2023-11-08 09:24 UTC, MagdalenaZuba commented on docs/guide/custom_policies.md
> +- `getFormTemplate` returns the path to the template to use for rendering the limitation form. Here it use [`form_label`]([[= symfony_doc =]]/form/form_customization.html#reference-forms-twig-label)
```suggestion
- `getFormTemplate` returns the path to the template to use for rendering the limitation form. Here it uses [`form_label`]([[= symfony_doc =]]/form/form_customization.html#reference-forms-twig-label) and [`form_widget`]([[= symfony_doc =]]/form/form_customization.html#reference-forms-twig-widget) to do so.
```

2023-11-08 09:24 UTC, MagdalenaZuba commented on docs/guide/custom_policies.md
> +- `MultipleSelectionBasedMapper` is mapper to build form for Limitation based on checkbox list where multiple items can be chosen. For example, it's used to build forms for [Content Type Limitation](
```suggestion
- `MultipleSelectionBasedMapper` is a mapper used to build forms for Limitation based on checkbox lists, where multiple items can be chosen. For example, it's used to build forms for [Content Type Limitation](limitation_reference.md#content-type-limitation), [Language Limitation](limitation_reference.md#language-limitation) or [Section Limitation](limitation_reference.md#section-limitation).
```

2023-11-08 09:24 UTC, MagdalenaZuba commented on docs/guide/custom_policies.md
> +- `UDWBasedMapper` is to build Limitation form where a Content/Location must be selected. For example, it's used by the [Subtree Limitation](limitation_reference.md#subtree-of-location-limitation) fo
```suggestion
- `UDWBasedMapper` is used to build Limitation form where a Content/Location must be selected. For example, it's used by the [Subtree Limitation](limitation_reference.md#subtree-of-location-limitation) form.
```

2023-11-08 09:24 UTC, MagdalenaZuba commented on docs/guide/custom_policies.md
> +To customize the rendering, a value mapper eventually transforms the Limitation value and send it to a custom template.
```suggestion
To customize the rendering, a value mapper eventually transforms the Limitation value and sends it to a custom template.
```

2023-11-08 09:24 UTC, MagdalenaZuba commented on docs/guide/custom_policies.md
> +Its `mapLimitationValue` function returns the Limitation value transformed for the needs of the template.
```suggestion
Its `mapLimitationValue` function returns the Limitation value adjusted to the needs of the template.
```
OR
```suggestion
Its `mapLimitationValue` function returns the Limitation value transformed to meet the requirements of the the template.
```

2023-11-08 09:24 UTC, MagdalenaZuba commented on docs/guide/custom_policies.md
> +When a value mapper exists for a Limitation, the rendering uses a Twig block named `ez_limitation_<lower_case_identifier>_value` where `<lower_case_identifier>` is the Limitation identifier in lower
```suggestion
When a value mapper exists for a Limitation, the rendering uses a Twig block named `ez_limitation_<lower_case_identifier>_value` where `<lower_case_identifier>` is the Limitation identifier in a lower case.
```

2023-11-08 09:24 UTC, MagdalenaZuba commented on docs/guide/custom_policies.md
> +In this example, block name is `ez_limitation_customlimitation_value` as the identifier is `CustomLimitation`.
```suggestion
In this example, `ez_limitation_customlimitation_value` is a block name and  `CustomLimitation` is an identifier.
```

2023-11-08 09:24 UTC, MagdalenaZuba commented on docs/guide/custom_policies.md
> +To check if current user has this custom limitation set to true from a custom controller:
```suggestion
To check if the current user has this custom limitation set to true from a custom controller:

```

2023-11-08 09:34 UTC, adriendupuis commented on docs/guide/custom_policies.md
> +In this example, block name is `ez_limitation_customlimitation_value` as the identifier is `CustomLimitation`.
@MagdalenaZuba 
```suggestion
In this example, `ez_limitation_customlimitation_value` is the block name, and `CustomLimitation` is the identifier.
```

2023-11-08 09:51 UTC, MagdalenaZuba approved these changes

2023-11-09 08:56 UTC, merged