IBX-816 - Revise Image and RichText exntensibility doc
ezsystems/developer-documentation pull request #1465
Opened 2021-10-06 09:53 UTC by dabrt

| Question      | Answer |
| ------------- | --- |
| JIRA Ticket   | IBX-816  |
| Versions      | 3.3, master |

2021-11-02 09:17 UTC, DominikaK requested changes

2021-11-02 09:17 UTC, DominikaK commented on docs/extending/online_editor_plugin.md
> +The following code implements an `InsertDate` command and attaches it to the editor:
```suggestion
The following code implements an `InsertDate` method and attaches it to the editor:
```
I think?

2021-11-02 09:17 UTC, DominikaK commented on docs/extending/richtext_block.md
> +also create a custom blocks.
```suggestion
also create custom blocks. 
```

2021-11-02 09:17 UTC, DominikaK commented on docs/extending/richtext_block.md
> +In addition to existing blocks that you can use when creating a Page, you can
Do you need to repeat the info from the main Page block page? Maybe instead link to that page and indicate that this is just one specific case of a block?

2021-11-02 09:17 UTC, DominikaK commented on docs/extending/richtext_block.md
> +Then, create a subscriber that converts a string of data into an XML code.
```suggestion
Then, create a subscriber that converts a string of data into XML code.
```

2021-11-02 11:27 UTC, DominikaK approved these changes

2021-11-03 08:39 UTC, damianz5 approved these changes

2021-11-03 08:39 UTC, damianz5 commented on code_samples/back_office/online_editor/config/packages/custom_buttons.yaml
> +                                    priority: 50
```suggestion
                    toolbar:
                        group1:
                            priority: 60
                            buttons:
                                ibexaMoveUp:
                                    priority: 30
                                ibexaMoveDown:
                                    priority: 20
                                    visible: false
                                heading:
                                    priority: 10
```

those changes needs to be added on 4.x

2021-11-03 08:43 UTC, merged