IBX-1130: Add language argument to translatable fields
ezsystems/developer-documentation pull request #1485
Opened 2021-11-08 09:33 UTC by DominikaK

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-1130
| Versions      | 3.3, master

2021-11-16 10:56 UTC, bdunogier approved these changes

2021-11-22 08:28 UTC, juskora requested changes

2021-11-22 08:28 UTC, juskora commented on docs/api/graphql_queries.md
> +When you don't specify a language, the response contains the most prioritized translation.
```suggestion
When you do not specify a language, the response contains the most prioritized translation.
```

2021-11-22 09:57 UTC, juskora approved these changes

2021-11-23 07:22 UTC, merged