Updated personalization section
ezsystems/developer-documentation pull request #1519
Opened 2022-01-14 11:56 UTC by juskora

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | 
| Versions      | 4.0

- Updated diagrams with new domain names
- Deleted recommendation_client.md
- Name corrections and domain name changes across the docs.

2022-01-14 14:02 UTC, DominikaK commented on docs/guide/personalization/enabling_personalization.md
> +See [`Event/Subscriber/RecommendationEventSubscriber.php`](https://github.com/ibexa/personalization-client/blob/main/src/lib/Event/Subscriber/RecommendationEventSubscriber.php) for example:
```suggestion
See [`Event/Subscriber/RecommendationEventSubscriber.php`](https://github.com/ibexa/personalization-client/blob/main/src/lib/Event/Subscriber/RecommendationEventSubscriber.php) for an example:
```

2022-01-14 14:07 UTC, DominikaK commented on docs/guide/personalization/enabling_personalization.md
> +Displaying image variations is not readily supported yet.
```suggestion
Displaying image variations is not supported out of the box.
```
Maybe, to avoid the unavoidable "yet"?

2022-01-14 14:07 UTC, DominikaK commented on docs/guide/personalization/enabling_personalization.md
> +Wjen you enable the Personalization, you can go back to the Back Office,
```suggestion
When you enable the Personalization, you can go back to the Back Office, 
```

2022-03-28 12:42 UTC, ciastektk requested changes

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/importing_historical_user_tracking_data.md
> +    **valid**: `https://https://event.perso.ibexa.co/api/00000/buy/johndoe/1/11?fullprice=19.99EUR&overridetimestamp=2012-01-01T11%3A00%3A00&quantity=1&signature=d0026f017ae823f19530d93318c5a2f6`
```suggestion
    **valid**: `https://event.perso.ibexa.co/api/00000/buy/johndoe/1/11?fullprice=19.99EUR&overridetimestamp=2012-01-01T11%3A00%3A00&quantity=1&signature=d0026f017ae823f19530d93318c5a2f6`
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/importing_historical_user_tracking_data.md
> +    **invalid**: `https://https://event.perso.ibexa.co/api/00000/buy/johndoe/1/11?fullprice=19.99EUR&overridetimestamp=2012-01-01T11%3A00%3A00&quantity=&signature=d0026f017ae823f19530d93318c5a2f6`
```suggestion
    **invalid**: `https://event.perso.ibexa.co/api/00000/buy/johndoe/1/11?fullprice=19.99EUR&overridetimestamp=2012-01-01T11%3A00%3A00&quantity=&signature=d0026f017ae823f19530d93318c5a2f6`
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/importing_historical_user_tracking_data.md
> +https://https://event.perso.ibexa.co/api/00000/buy/johndoe/1/11?fullprice=19.99EUR&overridetimestamp=2012-01-01T11%3A00%3A00&quantity=1&signature=d0026f017ae823f19530d93318c5a2f6
```suggestion
https://event.perso.ibexa.co/api/00000/buy/johndoe/1/11?fullprice=19.99EUR&overridetimestamp=2012-01-01T11%3A00%3A00&quantity=1&signature=d0026f017ae823f19530d93318c5a2f6
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/importing_historical_user_tracking_data.md
> +https://https://event.perso.ibexa.co/api/00000/buy/johndoe/1/94?fullprice=23.99EUR&overridetimestamp=2012-01-02T11%3A00%3A00&quantity=5&signature=53ae5744879d5a3ae833f3ef34109b44
```suggestion
https://event.perso.ibexa.co/api/00000/buy/johndoe/1/94?fullprice=23.99EUR&overridetimestamp=2012-01-02T11%3A00%3A00&quantity=5&signature=53ae5744879d5a3ae833f3ef34109b44
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/importing_historical_user_tracking_data.md
> +https://https://event.perso.ibexa.co/api/00000/buy/johndoe/1/78?fullprice=7.59EUR&overridetimestamp=2012-01-03T11%3A00%3A00&quantity=1&signature=d73e76754fb333e9733936bbd11bb5cd
```suggestion
https://event.perso.ibexa.co/api/00000/buy/johndoe/1/78?fullprice=7.59EUR&overridetimestamp=2012-01-03T11%3A00%3A00&quantity=1&signature=d73e76754fb333e9733936bbd11bb5cd
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/tracking_api.md
> +`GET https://https://event.perso.ibexa.co/api/[customerid]/click/[userid]/[itemtypeid]/[itemid]`
```suggestion
`GET https://event.perso.ibexa.co/api/[customerid]/click/[userid]/[itemtypeid]/[itemid]`
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/tracking_api.md
> +`GET https://https://event.perso.ibexa.co/api/[customerid]/click/[userid]/[itemtypeid]/[itemid]?parameter1=value1&parameter2=value2`
```suggestion
`GET https://event.perso.ibexa.co/api/[customerid]/click/[userid]/[itemtypeid]/[itemid]?parameter1=value1&parameter2=value2`
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/tracking_api.md
> +`GET https://https://event.perso.ibexa.co/api/[customerid]/consume/[userid]/[itemtypeid]/[itemid]`
```suggestion
`GET https://event.perso.ibexa.co/api/[customerid]/consume/[userid]/[itemtypeid]/[itemid]`
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/tracking_api.md
> +`GET https://https://event.perso.ibexa.co/api/[customerid]/buy/[userid]/[itemtypeid]/[itemid]?fullprice=2.50EUR&quantity=4`
```suggestion
`GET https://event.perso.ibexa.co/api/[customerid]/buy/[userid]/[itemtypeid]/[itemid]?fullprice=2.50EUR&quantity=4`
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/tracking_api.md
> +`GET https://https://event.perso.ibexa.co/api/[customerid]/login/[sourceuserid]/[targetuserid]`
```suggestion
`GET https://event.perso.ibexa.co/api/[customerid]/login/[sourceuserid]/[targetuserid]`
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/tracking_api.md
> +`GET https://https://event.perso.ibexa.co/api/[customerid]/basket/[userid]/[itemtypeid]/[itemid]`
```suggestion
`GET https://event.perso.ibexa.co/api/[customerid]/basket/[userid]/[itemtypeid]/[itemid]`
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/tracking_api.md
> +`GET https://https://event.perso.ibexa.co/api/[customerid]/rate/[userid]/[itemtypeid]/[itemid]?rating=50`
```suggestion
`GET https://event.perso.ibexa.co/api/[customerid]/rate/[userid]/[itemtypeid]/[itemid]?rating=50`
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/tracking_api.md
> +`GET https://https://event.perso.ibexa.co/api/[customerid]/blacklist/[userid]/[itemtypeid]/[itemid]`
```suggestion
`GET https://event.perso.ibexa.co/api/[customerid]/blacklist/[userid]/[itemtypeid]/[itemid]`
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/tracking_api.md
> +`GET https://https://event.perso.ibexa.co/api/[customerid]/clickrecommended/[userid]/[itemtypeid]/[itemid]?scenario=<scenarioid>`
```suggestion
`GET https://event.perso.ibexa.co/api/[customerid]/clickrecommended/[userid]/[itemtypeid]/[itemid]?scenario=<scenarioid>`
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/tracking_api.md
> +`GET https://https://event.perso.ibexa.co/api/[customerid]/rendered/[userid]/[itemtypeid]/[itemid[,itemid]]`
```suggestion
`GET https://event.perso.ibexa.co/api/[customerid]/rendered/[userid]/[itemtypeid]/[itemid[,itemid]]`
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/tracking_api.md
> +`GET https://https://event.perso.ibexa.co/api/00000/click/Js79009234YU7/1/123?categorypath=%2FShoes%2FChildren`
```suggestion
`GET https://event.perso.ibexa.co/api/00000/click/Js79009234YU7/1/123?categorypath=%2FShoes%2FChildren`
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/tracking_api.md
> +`GET https://https://event.perso.ibexa.co/api/00000/rendered/Js79009234YU7/1/128,129,155`
```suggestion
`GET https://event.perso.ibexa.co/api/00000/rendered/Js79009234YU7/1/128,129,155`
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/tracking_api.md
> +`GET https://https://event.perso.ibexa.co/api/00000/clickrecommended/Js79009234YU7/1/155?scenario=also_bought`
```suggestion
`GET https://event.perso.ibexa.co/api/00000/clickrecommended/Js79009234YU7/1/155?scenario=also_bought`
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/tracking_api.md
> +`GET https://https://event.perso.ibexa.co/api/00000/consume/Js79009234YU7/3/452`
```suggestion
`GET https://event.perso.ibexa.co/api/00000/consume/Js79009234YU7/3/452`
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/user_api.md
> +`GET: https://https://import.perso.ibexa.co/api/00000/facebook/user/CUSTOMER_1234?allSources=true`
```suggestion
`GET: https://import.perso.ibexa.co/api/00000/facebook/user/CUSTOMER_1234?allSources=true`
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/user_api.md
> +`POST: https://https://import.perso.ibexa.co/api/[customerid]/[source]/user`
```suggestion
`POST: https://import.perso.ibexa.co/api/[customerid]/[source]/user`
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/user_api.md
> +`GET: https://https://import.perso.ibexa.co/api/[customerid]/[source]/user/[userid[,userid[...]]]`
```suggestion
`GET: https://import.perso.ibexa.co/api/[customerid]/[source]/user/[userid[,userid[...]]]`
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/tracking_api.md
> +`GET https://https://event.perso.ibexa.co/api/00000/buy/johndoe/1/129?quantity=2&fullprice=4.44EUR`
```suggestion
`GET https://event.perso.ibexa.co/api/00000/buy/johndoe/1/128?quantity=1&fullprice=19.99EUR`
`GET https://event.perso.ibexa.co/api/00000/buy/johndoe/1/129?quantity=2&fullprice=4.44EUR`
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/tracking_api.md
> +`GET https://https://event.perso.ibexa.co/api/00000/consume/Js79009234YU7/3/452?percentage=60`
```suggestion
`GET https://event.perso.ibexa.co/api/00000/consume/Js79009234YU7/3/452?percentage=60`
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/tracking_api.md
> +`GET https://https://event.perso.ibexa.co/api/00000/basket/Js79009234YU7/1/128`
```suggestion
`GET https://event.perso.ibexa.co/api/00000/basket/Js79009234YU7/1/128`
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/tracking_api.md
> +`GET https://https://event.perso.ibexa.co/api/00000/basket/Js79009234YU7/1/129`
```suggestion
`GET https://event.perso.ibexa.co/api/00000/basket/Js79009234YU7/1/129`
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/tracking_api.md
> +`GET https://https://event.perso.ibexa.co/api/00000/login/Js79009234YU7/johndoe`
```suggestion
`GET https://event.perso.ibexa.co/api/00000/login/Js79009234YU7/johndoe`
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/basic_integration.md
> +`<img href="https://https://event.perso.ibexa.co/ebl/00000/click/<user_ID>/<content_type_ID>/<content_ID>" width="1" height="1">`
```suggestion
`<img href="https://event.perso.ibexa.co/ebl/00000/click/<user_ID>/<content_type_ID>/<content_ID>" width="1" height="1">`
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/best_practices/tracking_integration.md
> +img.src = "https://https://event.perso.ibexa.co/ebl/00000/click/johndoe/1/100?categorypath=/a/ab/abc";
```suggestion
img.src = "https://event.perso.ibexa.co/ebl/00000/click/johndoe/1/100?categorypath=/a/ab/abc";
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/best_practices/tracking_integration.md
> +<img href="https://https://event.perso.ibexa.co/ebl/00000/click/johndoe/1/100?categorypath=/a/ab/abc" width="1" height="1">
```suggestion
<img href="https://event.perso.ibexa.co/ebl/00000/click/johndoe/1/100?categorypath=/a/ab/abc" width="1" height="1">
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/basic_integration.md
> +$server = '//https://event.perso.ibexa.co';
```suggestion
$server = '//event.perso.ibexa.co';
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/basic_integration.md
> +var server = '//https://event.perso.ibexa.co';
```suggestion
var server = '//event.perso.ibexa.co';
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/basic_integration.md
> +$server = '//https://event.perso.ibexa.co';
```suggestion
$server = '//event.perso.ibexa.co';
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/basic_integration.md
> +            "rendered":"//https://event.perso.ibexa.co/api/00000/rendered/user/1/555?scenario=landing_page&modelid=5768"
```suggestion
            "clickRecommended":"//event.perso.ibexa.co/api/00000/clickrecommended/user/1/555?scenario=landing_page&modelid=5768",
            "rendered":"//event.perso.ibexa.co/api/00000/rendered/user/1/555?scenario=landing_page&modelid=5768"
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/basic_integration.md
> +            "rendered":"//https://event.perso.ibexa.co/api/00000/rendered/user/1/444?scenario=landing_page&modelid=5768"
```suggestion
            "clickRecommended":"//event.perso.ibexa.co/api/00000/clickrecommended/user/1/444?scenario=landing_page&modelid=5768",
            "rendered":"//event.perso.ibexa.co/api/00000/rendered/user/1/444?scenario=landing_page&modelid=5768"
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/recommendation_api.md
> +         "rendered" : "//https://event.perso.ibexa.co/..." // A link used to inform the engine that this recommendation was shown to the user
```suggestion
         "clickRecommended" : "//event.perso.ibexa.co/api/[customerID]/clickrecommended/[someuser]/[itemtype]/[itemid]?scenario=<scenario>&...", // A link that is provided if User ID is available. Link is fired when this recommendation is clicked.
         "rendered" : "//event.perso.ibexa.co/..." // A link used to inform the engine that this recommendation was shown to the user
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/recommendation_api.md
> +         "rendered" : "//https://event.perso.ibexa.co/..."
```suggestion
         "clickRecommended" : "//event.perso.ibexa.co/api/[customerID]/clickrecommended/[someuser]/[itemtype]/[itemid]?scenario=<scenario>&...",
         "rendered" : "//event.perso.ibexa.co/..."
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/tracking_with_yct.md
> +It activates the YOOCHOOSE tracking by inserting <https://cdn.perso.ibexa.co/ibexa-tracker-test.js>
```suggestion
It activates the YOOCHOOSE tracking by inserting <https://cdn.perso.ibexa.co/ibexa-tracker.js> 
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/tracking_api.md
> +`GET https://https://event.perso.ibexa.co/api/00000/rate/Js79009234YU7/1/133?rating=5`
```suggestion
`GET https://event.perso.ibexa.co/api/00000/rate/Js79009234YU7/1/133?rating=5`
```

2022-03-28 12:42 UTC, ciastektk commented on docs/guide/personalization/developer_guide/tracking_with_yct.md
> +    yc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.perso.ibexa.co/ibexa-tracker-test.js';
```suggestion
    yc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.perso.ibexa.co/ibexa-tracker.js';
```

2022-03-28 12:45 UTC, ciastektk commented
REST Url's on diagrams should be also changed from `/api/ezp/v2/ibexa_personalization` to `/api/ibexa/v2/personalization`

2022-03-30 07:56 UTC, juskora commented on docs/guide/personalization/enabling_personalization.md
> +occurs in the Back Office.
With any method, the info will be added.

2022-03-30 09:45 UTC, DominikaK approved these changes

2022-03-30 09:45 UTC, DominikaK commented on docs/guide/personalization/enabling_personalization.md
> +occurs (using any method that trigers the event).
```suggestion
occurs (using any method that triggers the event).
```

2022-04-20 11:21 UTC, ciastektk commented on docs/guide/personalization/developer_guide/tracking_api.md
> +         "rendered" : "//https://event.perso.ibexa.co/rendered/johndoe/1/100175717"
```suggestion
         "clickRecommended" : "//event.perso.ibexa.co/clickrecommended/johndoe/1/100175717?scenario=also_clicked&modelId=37",
         "rendered" : "//event.perso.ibexa.co/rendered/johndoe/1/100175717"
```

2022-04-20 11:33 UTC, ciastektk approved these changes

2022-04-20 12:29 UTC, merged