IBX-1868: Documentation for migration has been supplemented
ezsystems/developer-documentation pull request #1534
Opened 2022-02-10 13:35 UTC by mateuszdebinski

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | [IBX-1868](https://issues.ibexa.co/browse/IBX-1868)
| Versions      | v3, v4

2022-02-14 07:23 UTC, DominikaK requested changes

2022-02-14 07:23 UTC, DominikaK commented on docs/guide/data_migration/data_migration.md
> +You can find examples of using migrations with actions in the folder **vendor/ibexa/migrations/tests/bundle/Command/MigrateCommand/migrate-command-fixtures**
```suggestion
```

Given we don't mention actions in this page yet, I'd move it to the dedicated page.

2022-02-14 07:23 UTC, DominikaK commented on docs/guide/data_migration/data_migration_actions.md
> +
```suggestion

You can find examples of using migrations with actions in your project's 
`vendor/ibexa/migrations/tests/bundle/Command/MigrateCommand/migrate-command-fixtures` folder.

```

2022-02-14 07:23 UTC, DominikaK commented on docs/guide/data_migration/data_migration_actions.md
> +## Examples of how to use actions
```suggestion
## Action usage examples
```

2022-02-14 07:23 UTC, DominikaK commented on docs/guide/data_migration/data_migration_actions.md
> +### Actions for Content
```suggestion
### Content
```
```suggestion
### Actions for Content
```

2022-02-14 07:23 UTC, DominikaK commented on docs/guide/data_migration/data_migration_actions.md
> +### Actions for Content Type
```suggestion
### Content Types
```

2022-02-14 07:23 UTC, DominikaK commented on docs/guide/data_migration/data_migration_actions.md
> +### Actions for Role
```suggestion
### Roles
```

2022-02-14 07:23 UTC, DominikaK commented on docs/guide/data_migration/data_migration_actions.md
> +### Actions for User
```suggestion
### Users

2022-02-14 07:23 UTC, DominikaK commented on docs/guide/data_migration/data_migration_actions.md
> +### Actions for User Group
```suggestion
### User Groups
```

2022-02-14 09:36 UTC, DominikaK approved these changes

2022-02-25 13:07 UTC, Steveb-p approved these changes

2022-02-25 13:58 UTC, merged