IBX-23: Taxonomy
ezsystems/developer-documentation pull request #1556
Opened 2022-03-11 12:42 UTC by juskora

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-23
| Versions      | master, 4.0

2022-03-14 10:30 UTC, webhdx approved these changes

2022-03-28 12:00 UTC, DominikaK requested changes

2022-03-29 08:51 UTC, DominikaK commented on docs/guide/taxonomy/taxonomy.md
> +## Customize taxonony structure
```suggestion
## Customize taxonomy structure
```

2022-03-29 09:43 UTC, DominikaK approved these changes
+1 with this left: https://github.com/ezsystems/developer-documentation/pull/1556/files#r837224007

2022-03-29 11:12 UTC, merged