View matching
ezsystems/developer-documentation pull request #1571
Opened 2022-03-29 13:54 UTC by adriendupuis

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | N/A
| Versions      | 2.5, 3.3, 4.x

2022-03-29 13:55 UTC, adriendupuis commented on docs/guide/content_rendering/templates/view_matcher_reference.md
> +    Each matcher can has a scalar value or an array of scalar values. When an array is passed, it matches on one of the values.
TODO:
- [ ]  Validate that this is effectively true for each matcher.

2023-09-06 13:17 UTC, adriendupuis commented
To test my example, I wrote the following files on top of a clean 4.6.0-beta1.
I do not see the interest of including those complete examples in the documentation.

* `config/packages/views.yaml`
  ```yaml
  ibexa:
      system:
          site_group:
              content_view:
                  full:
                      welcome_page:
                          template: "@ibexadesign/full/welcome_page.html.twig"
                          match:
                              Id\Location: 2
                          params:
                              project_dir: '%kernel.project_dir%'
                      no_full_view:
                          controller: App\Controller\ViewController:noFullViewAction
                          template: '@ibexadesign/full/no_full_view.html.twig'
                          match: ~
  ```
* `src/Controller/ViewController.php`
  ```php
  <?php

  namespace App\Controller;

  use Ibexa\Contracts\Core\Repository\Repository;
  use Ibexa\Contracts\Core\Repository\Values\Content\Relation;
  use Ibexa\Core\MVC\Symfony\Controller\Controller;
  use Ibexa\Core\MVC\Symfony\Security\Authorization\Attribute;
  use Ibexa\Core\MVC\Symfony\View\View;
  use Symfony\Component\HttpFoundation\Response;

  class ViewController extends Controller
  {
      public function noFullViewAction(View $view)
      {
          $view->setResponse((new Response())->setStatusCode(404));

          $allReverseRelations = $this->getRepository()->sudo(function (Repository $repository) use ($view) {
              return $repository->getContentService()->loadReverseRelations($repository->getContentService()->loadContentInfo($view->getParameter('contentId')));
          });
          $filteredReverseRelationLocations = [];
          /** @var Relation $reverseRelation */
          foreach ($allReverseRelations as $reverseRelation) {
              $content = $this->getRepository()->getContentService()->loadContent($reverseRelation->sourceContentInfo->id);
              $location = $this->getRepository()->getLocationService()->loadLocation($reverseRelation->sourceContentInfo->mainLocationId);
              if ($this->isGranted(new Attribute('content', 'read', ['valueObject' => $content, 'targets' => [$location]]))) {
                  $filteredReverseRelationLocations[] = $location;
              }
          }
          $parameters = $view->getParameters();
          $parameters['reverse_relation_locations'] = $filteredReverseRelationLocations;
          $view->setParameters($parameters);

          return $view;
      }
  }
  ```
*`templates/themes/standard/full/no_full_view.html.twig`
  ```twig
  {% extends '@ibexadesign/pagelayout.html.twig' %}

  {% block content %}
      <h1>Page not found.</h1>

      {% if 1 == reverse_relation_locations|length %}
          <p>Did you mean <a href="{{ ibexa_path(reverse_relation_locations.0) }}">{{ ibexa_content_name(reverse_relation_locations.0.contentInfo) }}</a>?</p>
      {% elseif 1 < reverse_relation_locations|length %}
          <p>Did you mean one the following?</p>
          <ul>
              {% for location in reverse_relation_locations %}
                  <li><a href="{{ ibexa_path(location) }}">{{ ibexa_content_name(location.contentInfo) }}</a></li>
              {% endfor %}
          </ul>
      {% endif %}
  {% endblock %}
  ```

2023-10-31 08:51 UTC, adamwojs approved these changes

2023-10-31 08:51 UTC, adamwojs commented on docs/templating/templates/template_configuration.md
> +                    controller: App\Controller\ViewController:noFullViewAction
```suggestion
                    controller: App\Controller\ViewController::noFullViewAction
```

Syntax with one `:` is deprecated in SF

2023-10-31 09:24 UTC, MagdalenaZuba requested changes

2023-10-31 09:24 UTC, MagdalenaZuba commented on docs/templating/templates/template_configuration.md
> +    For example, you can prevent every Content item not having a dedicated template to be seen in `full` view but sent to a custom controller.
```suggestion
    For example, you can ensure that any Content item lacking a dedicated template isn't displayed in `full` view but is instead sent to a custom controller.
```

2023-10-31 09:24 UTC, MagdalenaZuba commented on docs/templating/templates/template_configuration.md
> +    Still for example, this custom controller could set the response status code as 404 (`$view->setResponse((new Response())->setStatusCode(404));`) and fetch some reverse relations to make suggesti
```suggestion
    This custom controller can also set the response status code to 404 using the following code: `$view->setResponse((new Response())->setStatusCode(404));`, and fetch reverse relations to provide suggestions on the error page.
```

2023-10-31 09:24 UTC, MagdalenaZuba commented on docs/templating/templates/view_matcher_reference.md
> +    Each matcher can has a scalar value or an array of scalar values. When an array is passed, it matches on one of its values.
```suggestion
    Each matcher has a scalar value or an array of scalar values. When an array is passed, it matches on one of its values.
```

2023-10-31 09:38 UTC, MagdalenaZuba approved these changes

2023-11-02 08:05 UTC, julitafalcondusza approved these changes

2023-11-08 13:08 UTC, reithor approved these changes

2023-11-08 14:08 UTC, merged

2023-11-08 14:28 UTC, adriendupuis commented on docs/templating/templates/view_matcher_reference.md
> +    Each matcher has a scalar value or an array of scalar values. When an array is passed, it matches on one of its values.
Already there in 2.5: https://doc.ibexa.co/en/2.5/guide/content_rendering/#matcher-value