Product catalog rendering and translational system
ezsystems/developer-documentation pull request #1600
Opened 2022-04-26 12:06 UTC by DominikaK

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-495, https://github.com/ibexa/product-catalog/pull/342
| Versions      | 4.1, master

Note: for 4.2 replace the custom controller for product list rendering with a Query Type, ref. https://github.com/ibexa/product-catalog/pull/480

Also: removes the "Embed product" page, which is irrelevant now that overriding templates for product is the same as with regular content.

2022-04-26 12:06 UTC, DominikaK commented on docs/guide/catalog/set_up_products.md
> +# Set up product for purchasing
For doc reviewers: not quite satisfied with the title, happy to hear better alternatives

2022-05-04 08:53 UTC, adamwojs requested changes

2022-05-04 08:53 UTC, adamwojs commented on docs/guide/catalog/set_up_products.md
> +you need to use `CurrencyResolverInterface` and `RegionResolverInterface` in you customization.
```suggestion
To implement a different logic, for example a switcher for preferred currencies and regions,
you need to use `CurrencyResolverInterface` and `RegionResolverInterface` in you customization.
```

`\Ibexa\Contracts\ProductCatalog\Events\CurrencyResolveEvent` and `\Ibexa\Contracts\ProductCatalog\Events\RegionResolveEvent` should be subscribed in order to customize this logic. 

Mentioned services are meet to be used to read current currency / region.

2022-05-04 08:53 UTC, adamwojs commented on code_samples/front/shop/list_products/src/Controller/ProductListController.php
> +class ProductListController
```suggestion
final class ProductListController
```

2022-05-04 08:53 UTC, adamwojs commented on code_samples/front/shop/list_products/src/Controller/ProductListController.php
> +use Ibexa\ProductCatalog\Local\Repository\ProductService;
\\Ibexa\\Contracts\\ProductCatalog\\ProductServiceInterface should be used here.

2022-05-04 08:53 UTC, adamwojs commented on code_samples/front/shop/list_products/src/Controller/ProductListController.php
> +    private $productService;
```suggestion
    private ProductServiceInterface $productService;
```

2022-05-04 08:53 UTC, adamwojs commented on code_samples/front/shop/list_products/src/Controller/ProductListController.php
> +    public function __construct(ProductService $productService)
```suggestion
    public function __construct(ProductServiceInterface $productService)
```

2022-05-04 08:53 UTC, adamwojs commented on code_samples/front/shop/list_products/src/Controller/ProductListController.php
> +    public function showProductsAction(View $view)
```suggestion
    public function showProductsAction(View $view): View
```

2022-05-04 09:47 UTC, DominikaK commented on code_samples/front/shop/list_products/src/Controller/ProductListController.php
> +use Ibexa\ProductCatalog\Local\Repository\ProductService;
```suggestion
use Ibexa\Contracts\ProductCatalog\ProductServiceInterface;
```

2022-05-04 09:50 UTC, DominikaK commented on docs/guide/catalog/set_up_products.md
> +you need to use `CurrencyResolverInterface` and `RegionResolverInterface` in you customization.
```suggestion
To implement a different logic, for example a switcher for preferred currencies and regions,
you need to subscribe to `Ibexa\Contracts\ProductCatalog\Events\CurrencyResolveEvent`
and `Ibexa\Contracts\ProductCatalog\Events\RegionResolveEvent` in your customization.
```

2022-05-12 09:51 UTC, juskora requested changes

2022-05-12 09:51 UTC, juskora commented on docs/guide/catalog/set_up_products.md
> +- [availability with positive or infinite stock for the product](#product-availability)
How about adding direct links to Product price and Product availability. Currently there is one more click to get to the point, maybe we could reduce it to only one :)

2022-05-12 11:23 UTC, juskora approved these changes

2022-05-12 12:05 UTC, merged