Add custom product catalog attribute type
ezsystems/developer-documentation pull request #1608
Opened 2022-05-04 08:28 UTC by DominikaK

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-2326
| Versions      | 4.1, master

2022-05-04 08:32 UTC, adamwojs reviewed
It's good starting point however we need to cover the following extension points in this page:
* `\Ibexa\Contracts\ProductCatalog\Local\Attribute\OptionsFormMapperInterface`
* `\Ibexa\Contracts\ProductCatalog\Local\Attribute\OptionsValidatorInterface`
* `\Ibexa\Contracts\ProductCatalog\Local\Attribute\ValueValidatorInterface`

2022-05-04 08:35 UTC, adamwojs commented on code_samples/catalog/custom_attribute_type/config/custom_services.yaml
> +                type: date
```suggestion
    app.product_catalog.attribute_type.date:
        class: Ibexa\ProductCatalog\Local\Repository\Attribute\AttributeType
        arguments:
            $identifier: 'date'
        tags:
            -   name: ibexa.product_catalog.attribute_type
                alias: date
    
    App\Attribute\Date\Form\DateValueFormMapper:
        tags:
            -   name: ibexa.product_catalog.attribute.form_mapper.value
                type: date
    
    
    App\Attribute\Date\DateValueFormatter:
        tags:
            -   name: ibexa.product_catalog.attribute.formatter.value
                type: date
```

2022-05-04 08:35 UTC, adamwojs commented on code_samples/catalog/custom_attribute_type/src/Attribute/Date/Form/DateValueFormMapper.php
> +        array $context = []
IMHO $context requires a little bit explanation here

2022-05-06 12:38 UTC, adamwojs requested changes
Article is still missing explenation/example of `\Ibexa\Contracts\ProductCatalog\Local\Attribute\OptionsValidatorInterface

2022-05-10 06:12 UTC, adamwojs approved these changes

2022-05-12 06:57 UTC, juskora approved these changes

2022-05-12 06:57 UTC, juskora commented on docs/guide/catalog/create_custom_attribute_type.md
> +Next, create a `PercentOptionsFormMapper` that maps the information that the user input in the form into attribute definition.
```suggestion
Next, create a `PercentOptionsFormMapper` that maps the information that the user inputs in the form into attribute definition.
```

2022-05-12 07:31 UTC, merged