IBX-2429: Example of UDW extensibility
ezsystems/developer-documentation pull request #1617
Opened 2022-05-13 09:30 UTC by juskora

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-2429
| Versions      | master, 4.0+

2022-05-13 09:42 UTC, dew326 requested changes

2022-05-13 09:42 UTC, dew326 commented on code_samples/back_office/udw/assets/js/image-tab/components/images.list.js
> +import { RestInfoContext } from '../../../../vendor/ibexa/admin-ui/src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module';
Now you can use just:
```suggestion
import { RestInfoContext } from '@ibexa-admin-ui/src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module';
```

2022-05-13 09:42 UTC, dew326 commented on code_samples/back_office/udw/assets/js/image-tab/image.tab.module.js
> +import Tab from '../../../vendor/ibexa/admin-ui/src/bundle/ui-dev/src/modules/universal-discovery/components/tab/tab';
```suggestion
import Tab from '@ibexa-admin-ui/src/bundle/ui-dev/src/modules/universal-discovery/components/tab/tab';
```

2022-05-13 09:42 UTC, dew326 commented on code_samples/back_office/udw/assets/js/image-tab/components/images.list.js
> +                    <use xlinkHref="/bundles/ibexaadminui/img/ibexa-icons.svg#caret-back"></use>
```suggestion
                    <use xlinkHref={window.ibexa.helpers.icon.getIconPath('caret-back')}></use>
```

2022-05-13 09:42 UTC, dew326 commented on code_samples/back_office/udw/assets/js/image-tab/components/images.list.js
> +                    <use xlinkHref="/bundles/ibexaadminui/img/ibexa-icons.svg#caret-next"></use>
```suggestion
                    <use xlinkHref={window.ibexa.helpers.icon.getIconPath('caret-next')}></use>
```

2022-05-13 09:42 UTC, dew326 commented on docs/extending/add_udw_tab.md
> +In `webpack.config.js`, add the following key:
```suggestion
In `webpack.config.js`, add the following declaration:
```

2022-05-13 09:42 UTC, dew326 commented on docs/extending/add_udw_tab.md
> +    Encore.reset();
```suggestion

    Encore.reset();
```

2022-05-13 09:42 UTC, dew326 commented on docs/extending/add_udw_tab.md
> +    });
```suggestion
    ibexaConfigManager.add({
        ibexaConfig,
        entryName: 'ibexa-admin-ui-udw-tabs-js',
        newItems: [path.resolve(__dirname, './assets/js/image-tab/image.tab.module.js')],
    });
```

2022-05-13 09:42 UTC, dew326 commented on code_samples/back_office/udw/assets/js/image-tab/image.tab.module.js
> +'adminUiConfig.universalDiscoveryWidget.tabs',
```suggestion
    'adminUiConfig.universalDiscoveryWidget.tabs',
```

2022-05-13 10:14 UTC, dew326 commented on code_samples/back_office/udw/assets/js/image-tab/components/images.list.js
> +                <svg className="ez-icon">
```suggestion
                <svg className="ibexa-icon">
```

2022-05-13 10:14 UTC, dew326 commented on docs/extending/add_udw_tab.md
> +    });
```suggestion
    ibexaConfigManager.add({
        ibexaConfig,
        entryName: 'ibexa-admin-ui-layout-css',
    });
```

2022-05-13 10:14 UTC, dew326 commented on docs/extending/add_udw_tab.md
> +    module.exports = [ ibexaConfig, ...customConfigs, projectConfig ];
```suggestion
    module.exports = [ ibexaConfig, ...customConfigs ];
```

2022-05-13 11:31 UTC, dew326 approved these changes

2022-05-16 10:20 UTC, DominikaK requested changes

2022-05-16 10:20 UTC, DominikaK commented on code_samples/back_office/udw/assets/js/image-tab/image.tab.module.js
> +import ImagesList from './components/image.list';
```suggestion
import ImagesList from './components/images.list';
```
This actually worked forme only as `images`

2022-05-16 10:20 UTC, DominikaK commented on docs/extending/add_udw_tab.md
> +    newItems: [path.resolve(__dirname, './assets/css/image.css'), path.resolve(__dirname, './assets/css/images.list.css')],
```suggestion
    newItems: [path.resolve(__dirname, './assets/css/image.css'), path.resolve(__dirname, './assets/css/image.list.css')],
```

2022-05-16 10:20 UTC, DominikaK commented on docs/extending/add_udw_tab.md
> +In the Back Office go to **Content** -> **Content structure**. On the left panel, click **Browse**.
There is not more "Browse" in left panel, that's leftover from v3. The quickest way I can think of to get to UDW is to create an article and in Richtext field go to embed.

2022-05-16 10:20 UTC, DominikaK commented on docs/extending/add_udw_tab.md
> +    Remember, after any change of css/js file you should always run `yarn encore dev` in the terminal.
```suggestion
    Remember, after any change of css/js files you should always run `yarn encore dev` in the terminal.
```

2022-05-17 08:19 UTC, DominikaK commented on docs/extending/add_udw_tab.md
> +In the Back Office go to **Content** -> **Dashboard**. On the left panel, click the **Create content** button.
```suggestion
In the Back Office go to **Content** -> **Dashboard**. On the top right, click the **Create content** button.
```

2022-05-17 08:19 UTC, DominikaK approved these changes

2022-05-17 08:38 UTC, merged