IBX-2879: Improvements to GraphQL attribute querying
ezsystems/developer-documentation pull request #1629
Opened 2022-05-26 08:33 UTC by DominikaK

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-2863
| Versions      | master

2022-05-26 08:35 UTC, konradoboza approved these changes

2022-06-13 13:14 UTC, MagdalenaZuba requested changes

2022-06-13 13:14 UTC, MagdalenaZuba commented on docs/api/graphql_queries.md
> +    You need to use use aliases (for example, `sizeValue`) when querying attributes by using the attribute type
```suggestion
    You need to use aliases (for example, `sizeValue`) when querying attributes by the attribute type
```

2022-06-13 13:14 UTC, MagdalenaZuba commented on docs/api/graphql_queries.md
> +
```suggestion
```

2022-06-14 07:07 UTC, MagdalenaZuba approved these changes

2022-06-14 10:17 UTC, merged