IBX-2895 - edition labels
ezsystems/developer-documentation pull request #1637
Opened 2022-06-03 09:49 UTC by dabrt

| Question      | Answer |
| ------------- | --- |
| JIRA Ticket   | IBX-2895 |
| Versions      | all |

Add flavor labels to content to make it clear what feature goes where

2022-06-14 11:17 UTC, DominikaK requested changes

2022-06-14 11:17 UTC, DominikaK commented on docs/releases/ibexa_dxp_v3.2.md
> +### Searching in Ibexa Commerce with Elasticsearch [[% include 'snippets/commerce_badge.md' %]]
In v3.2 Elastic was part of https://github.com/ezsystems/ezplatform-ee/blob/v3.2.8/composer.json#L36

2022-06-14 11:17 UTC, DominikaK commented on docs/tutorials/enterprise_beginner/1_get_a_starter_website.md
> +To begin the tutorial, you need a clean installation of [[= product_name_exp =]] or [[= product_name_com =]].
Using Commerce in the tutorial will probably backfire for beginner users, due to different front page, let's not suggest this.

2022-06-14 11:17 UTC, DominikaK commented on docs/releases/ibexa_dxp_v4.0.md
> +For more information, see [Enabling Commerce features](https://doc.ibexa.co/en/4.0/guide/config_back_office/#enable-commerce-features).
Watch out when merging to earlier branches: you're removing the section linked here in this PR.

2022-06-21 17:44 UTC, dabrt commented on docs/guide/multisite/multisite_configuration.md
> +#### SiteAccess switching in Page Builder
It is a lower level paragraph than "SiteAccesses and Page Builder", which is already marked as Experience/Commerce.

2022-06-21 18:13 UTC, dabrt commented on docs/tutorials/enterprise_beginner/1_get_a_starter_website.md
> +To begin the tutorial, you need a clean installation of [[= product_name_exp =]] or [[= product_name_com =]].
```suggestion
To begin the tutorial, you need a clean installation of [[= product_name_exp =]].
```

2022-06-22 05:50 UTC, DominikaK commented on docs/releases/ibexa_dxp_v3.2.md
> +### Searching in Ibexa Commerce with Elasticsearch [[% include 'snippets/commerce_badge.md' %]]
True, you're right.

2022-06-22 05:52 UTC, DominikaK commented on docs/releases/ibexa_dxp_v4.0.md
> +For more information, see [Enabling Commerce features](https://doc.ibexa.co/en/4.0/guide/config_back_office/#enable-commerce-features).
https://github.com/ezsystems/developer-documentation/pull/1637/files#diff-ee2c7e1cf422bdfac9c8a1035acd8fdbeecebab1dbb8aa03a292d49f2041d56bL209 removes this section, so after this is merged do 4.0, the link above will not work

2022-06-22 05:54 UTC, DominikaK commented on docs/guide/customers/customer_api/configuration_for_customer_data.md
> +You can configure those groups in YAML files with shop configuration, by using `user_group_location.business` and `user_group_location.private`:
I agree as a rule, but then we would have to be consistent: either mention it everywhere we refer to config files (which is a lot of places), or only in introductory topics.

2022-06-22 05:55 UTC, DominikaK approved these changes
Note: you can forgo merging this to 2.5, that version uses a different system of indicating product editions.

2022-06-22 16:24 UTC, merged