Add description metadata
ezsystems/developer-documentation pull request #1659
Opened 2022-06-23 11:25 UTC by DominikaK

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | 
| Versions      |

2022-07-01 10:20 UTC, MagdalenaZuba requested changes

2022-07-01 10:20 UTC, MagdalenaZuba commented on docs/tutorials/platform_beginner/8_enable_account_registration.md
> +description: Se how you can enable external users to register and contribute to your site.
```suggestion
description: See how you can enable external users to register and contribute to your site.
```

2022-07-01 10:20 UTC, MagdalenaZuba commented on docs/updating/from_1.x_2.x/update_from_1.x_2.x.md
> +description: Update your installation to the latest v2.5 version from v1.13 or earlier v2 versions.
```suggestion
description: Update your installation to the latest v2.5 version from v1.13 or earlier v2 version.
```

2022-07-04 05:50 UTC, DominikaK commented on docs/community_resources/release_process.md
> +description: "Ibexa DXP releases new versions periodically in three flavors: Ibexa Content, Ibexa Experience and Ibexa Commerce, plus open-source Ibexa OSS."
```suggestion
description: "Ibexa DXP releases new versions periodically in different flavors: Ibexa Content, Ibexa Experience and Ibexa Commerce, plus open-source Ibexa OSS."
```
Forgot to add in PR decription: quotation marks are required when description contains a colon, otherwite the yaml formatting is broken

2022-07-04 05:51 UTC, DominikaK commented on docs/guide/content_model.md
> +description: Ibexa DXP's content model relies on Content items based on Content Types, containing different content Fields.
```suggestion
description: Ibexa DXP's content model relies on Content items that are instances of Content Types and contain content Fields.
```

2022-07-04 05:53 UTC, DominikaK commented on docs/guide/search/search.md
> +description: Ibexa DXP search functionalities allows working with three search engines and using search API to run complex and precise question of content and products.
```suggestion
description: Ibexa DXP search functionalities allow working with three search engines and using search API to run complex and precise queries about content and products.
```
should have been 'queries' from the start, not sure how 'questions' got there

2022-07-04 07:11 UTC, MagdalenaZuba approved these changes

2022-07-06 06:04 UTC, merged