IBX-2829: Added option to configure fields for register form
ezsystems/developer-documentation pull request #1663
Opened 2022-06-29 06:44 UTC by MagdalenaZuba

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | <https://github.com/ibexa/user/pull/40>
| Versions      | master, 4.2

Described added option to configure fields for register form

2022-06-30 12:44 UTC, MagdalenaZuba commented on docs/guide/content_rendering/layout/add_register_user_template.md
> +You must also define if you are creating a backend user `user` or a frontend user `customer`under `user_type_identifier`.
@ViniTou corrected

2022-07-04 08:28 UTC, MagdalenaZuba commented on docs/guide/content_rendering/layout/add_register_user_template.md
> +You must also define what kind of user you want to create under `user_type_identifier` e.g. frontend user.
```suggestion
You can also define what kind of user you want to create under `user_type_identifier` e.g. frontend user.
```

2022-07-06 06:45 UTC, DominikaK requested changes

2022-07-06 06:45 UTC, DominikaK commented on docs/guide/content_rendering/layout/add_register_user_template.md
> +In the `config/packages/views.yaml` file specify the fields that should be part of your registration form under `allowed_field_definitions_identifiers`.
```suggestion
In the `config/packages/views.yaml` file, under `allowed_field_definitions_identifiers`, specify the fields that should be part of your registration form.
```

2022-07-06 06:45 UTC, DominikaK commented on docs/guide/content_rendering/layout/add_register_user_template.md
> +You can also define what kind of user you want to create under `user_type_identifier` e.g. frontend user.
Link to the user types listed in the next page.

2022-07-06 06:45 UTC, DominikaK commented on docs/guide/user_management/user_management.md
> +Currently, there are two user types defined: `users` and `customers`.
```suggestion
There are two user types defined: `users` and `customers`.
```

2022-07-06 06:45 UTC, DominikaK commented on docs/guide/user_management/user_management.md
> +To decide to what workspace the user should be registered to, you need to specify their user type under `user_type_identifier`.
We don't use "workspace" anywhere else, either the term needs explanation, or rephrase.

2022-07-06 06:45 UTC, DominikaK commented on docs/guide/user_management/user_management.md
> +`users` are backend users that are involved in creating the page such as editors and `customers` are frontend users.
```suggestion
`users` are Back Office users that are involved in creating the page such as editors, and `customers` are frontend users.
```

2022-07-06 06:45 UTC, DominikaK commented on docs/guide/user_management/user_management.md
> +        <siteaccess>:
```suggestion
        <scope>:
```

2022-07-06 06:45 UTC, DominikaK commented on docs/guide/user_management/user_management.md
> +        <siteaccess>:
```suggestion
        <scope>:
```

2022-07-06 06:45 UTC, DominikaK commented on docs/guide/user_management/user_management.md
> +To modify the registration form template add or remove fields under `allowed_field_definitions_identifiers`:
```suggestion
To modify the registration form template, add or remove fields under `allowed_field_definitions_identifiers`:
```

2022-07-06 06:45 UTC, DominikaK commented on docs/guide/user_management/user_management.md
> +You can also modify form templates in this way:
```suggestion
You can also modify form templates in the following way:
```

2022-07-06 10:52 UTC, merged