IBX-2854: Product variants and assets
ezsystems/developer-documentation pull request #1680
Opened 2022-07-14 09:49 UTC by DominikaK

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-2854
| Versions      | master (4.2)

2022-07-27 12:44 UTC, adamwojs approved these changes

2022-07-29 09:50 UTC, juskora requested changes

2022-07-29 09:50 UTC, juskora commented on docs/guide/catalog/catalog.md
> +
I think it needs to be rewritten.

2022-07-29 10:19 UTC, juskora approved these changes

2022-08-01 11:05 UTC, merged