IBX-2886: Help message fields
ezsystems/developer-documentation pull request #1763
Opened 2022-09-22 13:53 UTC by juskora

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-2886
| Versions      | master, 4.2

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2022-09-23 09:50 UTC, ciastektk requested changes

2022-09-23 09:50 UTC, ciastektk commented on docs/content_management/pages/page_block_attributes.md
> +- `help_html` - default value: `false`, if set to `true`, the help text is rendered.
For `help_html` option I will suggest to use similar description as in the official Symfony documentation e.g.: https://symfony.com/doc/current/reference/forms/types/text.html#help-html

2022-09-27 06:18 UTC, ciastektk approved these changes

2022-09-27 06:18 UTC, ciastektk commented on docs/content_management/pages/page_block_attributes.md
> +- `help_html` - set this option to `true` to not to escape the contents of the `help` option from rendering them in the template.
```suggestion
- `help_html` - set this option to `true` to not escape the contents of the `help` option from rendering them in the template.
```

2022-09-30 07:08 UTC, DominikaK approved these changes

2022-09-30 07:08 UTC, DominikaK commented on docs/content_management/pages/page_block_attributes.md
> +With the `help`, `help_attr` and `help_html` field options, you can define help messages for fields in the Page block.
```suggestion
With the `help`, `help_attr`, and `help_html` field options, you can define help messages for fields in the Page block.
```

2022-09-30 07:08 UTC, DominikaK commented on docs/content_management/pages/page_block_attributes.md
> +                            text: 'Some exemplary text'
```suggestion
                            text: 'Some example text'
```

2022-09-30 07:08 UTC, DominikaK commented on docs/content_management/pages/page_block_attributes.md
> +- `help_html` - set this option to `true` to not escape the contents of the `help` option from rendering them in the template.
```suggestion
- `help_html` - set this option to `true` to disable escaping the contents of the `help` option when rendering in the template.
```

2022-09-30 07:08 UTC, DominikaK commented on docs/content_management/pages/page_block_attributes.md
> +You can set the options for root or nested attribute, see the exemplary configuration:
```suggestion
You can set the options for root or nested attribute, see the example configuration:
```

2022-09-30 07:41 UTC, merged