Corporate Portal Customisation of an approval process
ezsystems/developer-documentation pull request #1820
Opened 2022-11-28 15:01 UTC by MagdalenaZuba

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-3279
| Versions      | 4.3

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2022-12-01 09:42 UTC, MagdalenaZuba commented on docs/customer_management/cp_applications.md
> +[[= include_file('code_samples/customer_portal/src/Form/VerifyType.php', 20, 21) =]]
```suggestion
[[= include_file('code_samples/customer_portal/src/Form/VerifyType.php', 28, 20, 21) =]]
```

2022-12-01 09:56 UTC, DominikaK requested changes

2022-12-01 09:56 UTC, DominikaK commented on docs/customer_management/cp_applications.md
> +If they are accepted, the business partner will receive an invitation link to the Customer Portal,
```suggestion
If they are accepted, the business partner receives an invitation link to the Customer Portal,
```

2022-12-01 09:56 UTC, DominikaK commented on docs/customer_management/cp_applications.md
> +New business customers can apply for a company account by themselves.
```suggestion
New business customers can apply for a company account.
```

2022-12-01 09:56 UTC, DominikaK commented on docs/customer_management/cp_applications.md
> +Any user can become application approver, as long as they have `Company Application/Workflow` Policy assigned to their Role.
```suggestion
Any user can become application approver, as long as they have the `Company Application/Workflow` Policy assigned to their Role.
```

2022-12-01 09:56 UTC, DominikaK commented on docs/customer_management/cp_applications.md
> +There, it can be defined from which states to which states the user may move applications.
```suggestion
There, you can define from which states to which states the user may move applications.
```

```suggestion
There, you can define between which states the user may move applications.
```

2022-12-01 09:56 UTC, DominikaK commented on docs/customer_management/cp_applications.md
> +## Customer Portal applications configuration
```suggestion
## Customer Portal application configuration
```

2022-12-01 09:56 UTC, DominikaK commented on docs/customer_management/cp_applications.md
> +## Reasons for rejecting application
```suggestion
### Reasons for rejecting application
```

2022-12-01 09:56 UTC, DominikaK commented on docs/customer_management/cp_applications.md
> +First, go to `config/packages/ibexa.yaml` and add `verify` status to the configuration:
```suggestion
First, go to `config/packages/ibexa.yaml` and add a `verify` status to the configuration:
```

2022-12-01 09:56 UTC, DominikaK commented on docs/customer_management/cp_applications.md
> +[[= include_file('code_samples/customer_portal/src/Form/VerifyType.php', 28, 20, 21) =]]
```suggestion
``` php hl_lines="20 21 28"
[[= include_file('code_samples/customer_portal/src/Form/VerifyType.php') =]]
```
I guess

2022-12-01 09:56 UTC, DominikaK commented on docs/customer_management/cp_applications.md
> +Add event subscriber that will pass a new form type to the frontend.
```suggestion
Add an event subscriber that passes a new form type to the frontend.
```

2022-12-01 09:56 UTC, DominikaK commented on docs/customer_management/cp_applications.md
> +Create `src/Corporate/EventSubscriber/ApplicationDetailsViewSubscriber.php` following below example:
```suggestion
Create `src/Corporate/EventSubscriber/ApplicationDetailsViewSubscriber.php` following the example below:
```

2022-12-01 09:56 UTC, DominikaK commented on docs/customer_management/cp_applications.md
> +[[= include_file('code_samples/customer_portal/src/Corporate/EventSubscriber/ApplicationDetailsViewSubscriber.php', 39) =]]
```suggestion
``` php hl_lines="39"
[[= include_file('code_samples/customer_portal/src/Corporate/EventSubscriber/ApplicationDetailsViewSubscriber.php') =]]
```

2022-12-01 09:56 UTC, DominikaK commented on docs/customer_management/cp_applications.md
> +In line 39, you can see `verify_form` parameter that passes the `verify` form to the application review view.
```suggestion
In line 39, you can see the `verify_form` parameter that passes the `verify` form to the application review view.
```

2022-12-01 09:56 UTC, DominikaK commented on docs/customer_management/cp_applications.md
> +It will overwrite the default view and add **Verify** button to the review view.
```suggestion
It overrides the default view and adds a **Verify** button to the review view.
```

2022-12-01 09:56 UTC, DominikaK commented on docs/customer_management/cp_applications.md
> +Create another event subscriber that will pass the information
```suggestion
Create another event subscriber that passes the information
```

2022-12-01 09:56 UTC, DominikaK commented on docs/customer_management/cp_applications.md
> +[[= include_file('code_samples/customer_portal/src/Corporate/EventSubscriber/VerifyStateEventSubscriber.php', 46) =]]
```suggestion
``` php hl_lines="46"
[[= include_file('code_samples/customer_portal/src/Corporate/EventSubscriber/VerifyStateEventSubscriber.php') =]]
```

2022-12-01 10:13 UTC, MagdalenaZuba commented on docs/customer_management/cp_applications.md
> +To change or add reasons for not accepting Corporate Portal application go to
You can put application on hold, or send it for further review, it doesn't always refer to rejecting

2022-12-01 11:08 UTC, DominikaK approved these changes
The highlight lines are still off by one (I think they count from 0)

2022-12-02 07:45 UTC, Nattfarinn approved these changes

2022-12-02 09:19 UTC, merged