Create Form attribute added
ezsystems/developer-documentation pull request #1842
Opened 2022-12-27 13:34 UTC by julitafalcondusza

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | (https://issues.ibexa.co/browse/IBX-3133)
| Versions      | 3.3+

Procedure how to create Form Builder Form attribute added.

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [x] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [x] Added link to this PR in relevant JIRA ticket or code PR

2023-02-02 11:24 UTC, Nattfarinn approved these changes

2023-02-03 11:03 UTC, MagdalenaZuba commented
Add create_form_attribute.md to mkdocs.yml, so we can see your work on the doc website :)

2023-02-03 11:03 UTC, MagdalenaZuba requested changes

2023-02-03 11:03 UTC, MagdalenaZuba commented on docs/content_management/forms/create_form_attribute
> +Now you can go to Back Office and build a new form.
Please add a path, where exactly the user should go

2023-02-03 11:37 UTC, MagdalenaZuba commented on mkdocs.yml
> +            - Create Form attribute: content_management/forms/create_form_attribute.md'
```suggestion
            - Create Form attribute: content_management/forms/create_form_attribute.md
```

2023-02-03 12:41 UTC, MagdalenaZuba approved these changes

2023-02-03 13:49 UTC, merged