IBX-3962: Introduced ModifyFieldDefinitionFieldsSubscriber
ezsystems/developer-documentation pull request #1844
Opened 2023-01-03 14:13 UTC by DominikaK

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-3962
| Versions      | 4.2+

Adds option to disable some metadata/details such a "required" for a Field Type.

#### Checklist

- [x] Text renders correctly
- [x] Text has been checked with vale
- [x] Description metadata is up to date
- [x] Code samples are working
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-03-10 08:17 UTC, ciastektk requested changes

2023-03-10 08:17 UTC, ciastektk commented on docs/content_management/content_model.md
> +    You can disable editing specific Field details per Field Type by [listening to a subscriber](customize_field_type_metadata.md).
```suggestion
    You can disable editing specific Field details per Field Type by [adding custom service definition for `ModifyFieldDefinitionsCollectionTypeExtension`](customize_field_type_metadata.md).
```

2023-03-23 07:14 UTC, ciastektk approved these changes

2023-03-29 06:09 UTC, MagdalenaZuba approved these changes

2023-03-29 10:25 UTC, DominikaK commented on docs/content_management/content_model.md
> +    You can disable editing specific Field details per Field Type by [adding custom service definition for `ModifyFieldDefinitionsCollectionTypeExtension`](customize_field_type_metadata.md).
```suggestion
    You can disable the possibility to edit specific Field details per Field Type by [adding custom service definition for `ModifyFieldDefinitionsCollectionTypeExtension`](customize_field_type_metadata.md).
```
I don't think we can do "edition" as "act of editing".

2023-03-31 06:17 UTC, merged