Update installation instruction for PHP 7.4
ezsystems/developer-documentation pull request #1850
Opened 2023-01-11 15:00 UTC by DominikaK

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | n/a
| Versions      | all

Note: for 3.3 merge after 3.3.30 and update to replace the current note (switching php 8.0 with 7.4).

#### Checklist

- [x] Text renders correctly
- [x] Text has been checked with vale

2023-01-11 16:55 UTC, MagdalenaZuba approved these changes

2023-01-17 08:38 UTC, webhdx requested changes
According to @vidarl's (investigation)[https://issues.ibexa.co/browse/IBX-4773] the same steps should be used when installing on PHP 8.0.

2023-02-03 07:23 UTC, webhdx approved these changes

2023-02-03 07:41 UTC, konradoboza approved these changes

2023-02-03 07:45 UTC, merged