IBX-4759: Twig function to fetch current User
ezsystems/developer-documentation pull request #1856
Opened 2023-01-13 09:46 UTC by DominikaK

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-4759
| Versions      | master (4.4)

#### Checklist

- [x] Text renders correctly
- [x] Text has been checked with vale
- [x] Code samples are working
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-01-13 09:50 UTC, Steveb-p commented on docs/templating/twig_function_reference/other_twig_filters.md
> +`ibexa_user_get_current()` returns the User object of the current user.
Specifically, what type of `User` object is returned? What is it's fully qualified class name?

2023-01-13 10:18 UTC, DominikaK commented on docs/templating/twig_function_reference/other_twig_filters.md
> +`ibexa_user_get_current()` returns the User object of the current user.
```suggestion
`ibexa_user_get_current()` returns the User object (`Ibexa\Core\Repository\Values\User\User`) of the current user.
```

2023-01-13 10:57 UTC, MagdalenaZuba approved these changes

2023-01-13 10:57 UTC, MagdalenaZuba commented on docs/templating/twig_function_reference/other_twig_filters.md
> +You can get the underlying Content item, including among other the user's name,
```suggestion
You can get the underlying Content item, for example the user's name,
```

2023-01-30 07:19 UTC, adamwojs requested changes

2023-01-30 07:19 UTC, adamwojs commented on docs/templating/twig_function_reference/other_twig_filters.md
> +`ibexa_user_get_current()` returns the User object (`Ibexa\Core\Repository\Values\User\User`) of the current user.
```suggestion
`ibexa_user_get_current()` returns the User object (`Ibexa\Contracts\Core\Repository\Values\User\User`) of the current user.
```

2023-01-30 07:40 UTC, adamwojs approved these changes

2023-02-01 13:07 UTC, merged