Added Media section permission for anonymous user to be able to visua…
ezsystems/developer-documentation pull request #1862
Opened 2023-01-16 19:02 UTC by zjabibexa

A default installation of Ibexa DXP does not include `Media` section in `Anonymous` role permissions.
Following the tutorial we will have this error : 

`
An exception has been thrown during the rendering of a template ("Error when rendering "http://localhost:8000/_fragment?_path=_format%3Dhtml%26_locale%3Den_GB%26_controller%3Dibexa_content%253A%253AviewAction" (Status code is 302).") in "@standard/ui/field_type/preview/ezdam.html.twig".
`
We see clearly a redirection ( 302 ) due to a request made to a protected resource.

If we add the permission, the exception disappears and we see the photo without problems.

| Question      | Answer
| ------------- | ---
| JIRA Ticket   |  N/A 
| Versions      |  4.3+

#### Checklist

- [x] Text renders correctly
- [x] Text has been checked with vale

2023-01-19 07:50 UTC, DominikaK commented
@zjabibexa, are you testing this on an Ibexa Content installation? Then I think this is related to this bug: https://issues.ibexa.co/browse/IBX-2298

2023-01-30 14:46 UTC, zjabibexa commented
Yes exactly, I tested on an Ibexa Content Installation, on Experience Installation I see the roles but on the Content no.

2023-02-03 07:58 UTC, DominikaK requested changes
Just a few cosmetic fixes to fit out style guide.

2023-02-03 07:58 UTC, DominikaK commented on docs/tutorials/beginner_tutorial/5_display_a_list_of_content_items.md
> +To be able to visualise the `photo` field you have to add `read` permission to `Media` section.
```suggestion
To be able to view the `photo` Field you have to add a `read` permission to `Media` section.
```

2023-02-03 07:58 UTC, DominikaK commented on docs/tutorials/beginner_tutorial/5_display_a_list_of_content_items.md
> +From **Admin** (gear icon) in the left menu, go to the **Roles** management screen and click on the **Anonymous** Role.
```suggestion
From **Admin** (gear icon) in the left menu, go to the **Roles** management screen and click the **Anonymous** Role.
```

2023-02-03 07:58 UTC, DominikaK commented on docs/tutorials/beginner_tutorial/5_display_a_list_of_content_items.md
> +Edit the **Content/Read** policy line to add `Media` section to **Limitation** along with the `Standard` section.
```suggestion
Edit the **Content/Read** Policy line to add the `Media` section to **Limitation** along with the `Standard` section.
```

2023-02-16 06:46 UTC, DominikaK approved these changes

2023-02-20 12:26 UTC, merged