IBX-4642: Storefront config
ezsystems/developer-documentation pull request #1875
Opened 2023-02-01 11:05 UTC by juskora

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-4642
| Versions      | master, 4.4

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-02-01 11:59 UTC, dabrt commented on docs/commerce/storefront/storefront.md
> +It is a set of basic components that serves as a basis, which developers can
```suggestion
It is a set of components that serves as a basis, which developers can 
```

2023-02-01 12:49 UTC, DominikaK requested changes

2023-02-01 12:49 UTC, DominikaK commented on docs/commerce/storefront/configure_storefront.md
> +description: Configure Storefront
```suggestion
description: Configure Storefront, including catalogs used, customer groups and user accounts.
```

2023-02-01 12:49 UTC, DominikaK commented on docs/commerce/storefront/configure_storefront.md
> +The Storefront is accesible under the `<yourdomain>/product-catalog`.
```suggestion
The Storefront is accessible under the `<yourdomain>/product-catalog`.
```

2023-02-01 12:49 UTC, DominikaK commented on docs/commerce/storefront/configure_storefront.md
> +Before you start configuring the Storefront, make sure you have cerated and configured [catalogs](https://doc.ibexa.co/projects/userguide/en/latest/pim/work_with_catalogs/#create-catalogs) in the Bac
```suggestion
Before you start configuring the Storefront, make sure you have created and configured [catalogs](https://doc.ibexa.co/projects/userguide/en/latest/pim/work_with_catalogs/#create-catalogs) in the Back Office.
```

2023-02-01 12:49 UTC, DominikaK commented on docs/commerce/storefront/configure_storefront.md
> +The configuration is avaible under the `ibexa.system.<scope>.storefront.catalog` key.
```suggestion
The configuration is available under the `ibexa.system.<scope>.storefront.catalog` key.
```

2023-02-01 12:49 UTC, DominikaK commented on docs/commerce/storefront/configure_storefront.md
> +If the `null` as a key value is provided, the Storefront makes the main product catalog (with all products) visibile for all users.
```suggestion

If `null`is provided as the value, the Storefront makes the main product catalog (with all products) visible for all users.
```

2023-02-01 12:49 UTC, DominikaK commented on docs/commerce/storefront/configure_storefront.md
> +2\. To expose a single catalog with an identifier to all users only a catalog, provide a `string` value under the key:
```suggestion
2\. To expose a single catalog with an identifier to all users, provide a string value of the catalog identifier:
```

2023-02-01 12:49 UTC, DominikaK commented on docs/commerce/storefront/configure_storefront.md
> +First, create catalogs in the Back Office.
```suggestion
```
This is repetition of an earlier step

2023-02-01 12:49 UTC, DominikaK commented on docs/commerce/storefront/configure_storefront.md
> +Next, provide the following configuration:
```suggestion
To do it, provide the following configuration:
```

2023-02-01 12:49 UTC, DominikaK commented on docs/commerce/storefront/configure_storefront.md
> +The basic configuration of the Storefront can look as the following:
```suggestion
The basic configuration of the Storefront can look as follows:
```

2023-02-01 12:49 UTC, DominikaK commented on docs/commerce/storefront/configure_storefront.md
> +`null` stands for the current user
```suggestion
```

2023-02-01 12:49 UTC, DominikaK commented on docs/commerce/storefront/configure_storefront.md
> +
```suggestion
`null` stands for the current user.

```

2023-02-01 12:49 UTC, DominikaK commented on docs/commerce/storefront/configure_storefront.md
> +The `\Ibexa\Contracts\Storefront\Repository\CatalogResolverInterface` service allows to retrieve product catalog available for a specific user.
```suggestion
The `\Ibexa\Contracts\Storefront\Repository\CatalogResolverInterface` interface allows retrieving the product catalog available for a specific user.
```

2023-02-01 12:49 UTC, DominikaK commented on docs/commerce/storefront/configure_storefront.md
> +- [change password feature](../../users/user_management.md)
```suggestion
- [change password feature](user_management.md)
```

2023-02-01 12:49 UTC, DominikaK commented on docs/commerce/storefront/extend_storefront.md
> +description: Extend Storefront configuration
```suggestion
description: Extend Storefront with new menus
```

2023-02-01 12:49 UTC, DominikaK commented on docs/commerce/storefront/extend_storefront.md
> +| Currency| `currency_menu` | Renders a menu to change the active currency |
```suggestion
```

2023-02-01 12:49 UTC, DominikaK commented on docs/commerce/storefront/extend_storefront.md
> +| Language| `langauge_menu` | Renders a menu to change the active language |
```suggestion
| Language| `language_menu` | Renders a menu to change the active language |
```

2023-02-01 12:49 UTC, DominikaK commented on docs/commerce/storefront/extend_storefront.md
> +| Region  | `region_menu`  | Renders a menu to change thr active region |
```suggestion
| Region  | `region_menu`  | Renders a menu to change the active region |
```

2023-02-01 12:49 UTC, DominikaK commented on docs/commerce/storefront/extend_storefront.md
> +Create an event subscriber in the `src/EventSubscriber/BreadcrumbsMenuSubscriber.php`:
```suggestion
Create an event subscriber in `src/EventSubscriber/BreadcrumbsMenuSubscriber.php`:
```

2023-02-01 12:49 UTC, DominikaK commented on docs/commerce/storefront/extend_storefront.md
> +Create an event subscriber in the `src/EventSubscriber/BreadcrumbsMenuSubscriber.php`:
Actually, it's not that way. Too add the menu you need only the templates below. You need the subscriber to modify the items in the menu

2023-02-01 12:49 UTC, DominikaK commented on docs/commerce/storefront/extend_storefront.md
> +Next, extend the `templates/themes/storefront/storefront/product.html.twig` template:
```suggestion
Next, extend the `templates/themes/storefront/storefront/product.html.twig` template to include the breadcrumbs:
```

2023-02-01 12:49 UTC, DominikaK commented on docs/commerce/storefront/storefront.md
> +Storefront package provides a starting kit for the developers.
```suggestion
The Storefront package provides a starting kit for the developers.
```

2023-02-01 12:49 UTC, DominikaK commented on docs/commerce/storefront/storefront.md
> +    For information about roles and permissions that control access to various components of the purchase process, see [Permission use cases](../../permissions/permission_use_cases.md#commerce).
```suggestion
    For information about roles and permissions that control access to various components of the purchase process, see [Permission use cases](permission_use_cases.md#commerce).
```

2023-02-01 13:16 UTC, DominikaK approved these changes

2023-02-01 20:56 UTC, adamwojs reviewed
It's good starting point but we need cover all storefront features .

2023-02-01 20:56 UTC, adamwojs commented on code_samples/front/shop/catalog_custom_logic/CatalogResolveEvent.php
> +}
New line is missing

2023-02-01 20:56 UTC, adamwojs commented on docs/commerce/storefront/extend_storefront.md
> +- Product
```suggestion
## Create menu items

`\Ibexa\Contracts\Storefront\Menu\ItemFactoryInterface` provides convenient methods to build menu item based on repository objects, including:

- Content
- Content ID
- Location
- Location ID
- Taxonomy Entry
- Product
```

In current shape this section mixes two unrelated topics

2023-02-02 08:01 UTC, juskora commented
@adamwojs So far it's a MVP but we will gradually add Storefront features from the scope.

2023-02-02 08:25 UTC, DominikaK approved these changes

2023-02-02 08:53 UTC, adamwojs approved these changes

2023-02-02 08:53 UTC, adamwojs commented on code_samples/front/shop/storefront/templates/themes/storefront/storefront/product.html.twig
> +{% endblock %}
```suggestion
{% block content %}
    {% set breadcrumbs_menu = knp_menu_get('ibexa_storefront.menu.breadcrumbs.product', [], {
        'product': product        
    }) %}
    
    {{ knp_menu_render(breadcrumbs_menu, {
        template: '@ibexadesign/storefront/knp_menu/breadcrumbs.html.twig',
    }) }}
    
    {% include '@ibexadesign/storefront/component/product_view.html.twig' %}
{% endblock %}
```

2023-02-02 08:53 UTC, adamwojs commented on docs/commerce/storefront/configure_storefront.md
> +```
```suggestion
```php
namespace Ibexa\Contracts\Storefront\Repository;

use Ibexa\Contracts\Core\Repository\Values\User\User;
use Ibexa\Contracts\ProductCatalog\Values\CatalogInterface;

interface CatalogResolverInterface
{
    public function resolveCatalog(?User $user = null): ?CatalogInterface;
}
```
```

This should fix a syntax highlighting on GH

2023-02-02 09:08 UTC, merged