IBX-4168 - Unified search reference
ezsystems/developer-documentation pull request #1881
Opened 2023-02-08 12:09 UTC by julitafalcondusza

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | (https://issues.ibexa.co/browse/IBX-4168)
| Versions      | 4.4+
Unified search reference: pages in TOC reorganized, content updated, information verified.

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-02-16 20:23 UTC, adamwojs commented on docs/snippets/aggregation_arguments.md
> +- `name` - name of the Aggregation object
```suggestion
- `name` - name of the Aggregation
```

You can use simply `name of the aggregation` or `name of the aggregation definition`

2023-02-16 20:23 UTC, adamwojs commented on docs/snippets/aggregation_arguments.md
> +- `fieldDefinitionIdentifier` - string representing the Field identifier
```suggestion
- `fieldDefinitionIdentifier` - string representing the Field Definition identifier
```

2023-02-17 09:50 UTC, MagdalenaZuba requested changes

2023-02-17 09:50 UTC, MagdalenaZuba commented on docs/search/criteria_reference/customprice_criterion.md
> +If you do not provide a customer group, the query uses the group related to the current user
```suggestion
If you do not provide a customer group, the query uses the group related to the current user.
```

2023-02-17 09:50 UTC, MagdalenaZuba commented on docs/search/criteria_reference/customprice_criterion.md
> +- (optional) `customerGroup` - a `CustomerGroupInterface` object representing the customer group to prices prices for
```suggestion
- (optional) `customerGroup` - a `CustomerGroupInterface` object representing the customer group to show prices for.
```

2023-02-17 09:50 UTC, MagdalenaZuba commented on docs/search/criteria_reference/product_search_criteria.md
> +|[ProductCategory](productcategory_criterion.md)|Product category assigned to product|P
```suggestion
|[ProductCategory](productcategory_criterion.md)|Product category assigned to product|
```

2023-02-17 09:50 UTC, MagdalenaZuba commented on docs/search/criteria_reference/simplemeasurementattribute_criterion.md
> +- `value` - `\Ibexa\Contracts\Measurement\Value\SimpleValueInterface` object representing the attribute value
```suggestion
- `value` - `Ibexa\Contracts\Measurement\Value\SimpleValueInterface` object representing the attribute value
```

2023-02-17 09:50 UTC, MagdalenaZuba commented on docs/search/sort_clause_reference/customprice_sort_clause.md
> +If you do not provide a customer group, the query uses the group related to the current user
```suggestion
- (optional) `customerGroup` - a `CustomerGroupInterface` object representing the customer group to check prices for.
If you do not provide a customer group, the query uses the group related to the current user.
```

2023-02-17 09:50 UTC, MagdalenaZuba commented on docs/search/criteria_reference/search_criteria_reference.md
> +|[IsCurrencyEnabledCriterion](iscurrencyenabled_criterion.md)|Whethe a specificed currency is enabled in the system| | | |
```suggestion
|[IsCurrencyEnabledCriterion](iscurrencyenabled_criterion.md)|Whether a specified currency is enabled in the system| | | |
```

2023-02-17 09:57 UTC, MagdalenaZuba approved these changes

2023-02-17 16:45 UTC, adamwojs approved these changes

2023-02-22 11:40 UTC, merged