v4.3.5 RNs
ezsystems/developer-documentation pull request #1909
Opened 2023-03-02 14:19 UTC by DominikaK

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-3972
| Versions      | all
| Edition       | all

Note: merge the same note to the next 3.3 and 4.4 releases.

#### Checklist

- [x] Text renders correctly
- [x] Text has been checked with vale
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-03-02 14:24 UTC, alongosz requested changes

2023-03-02 14:24 UTC, alongosz commented on docs/release_notes/ibexa_dxp_v4.3.md
> +array<<int fieldId>, array<<string language code>, array<ValidationError>>
Whoops, my mistake:
```suggestion
array<<int fieldId>, array<<string language code>, array<\Ibexa\Contracts\Core\FieldType\ValidationError>>>
```

2023-03-02 14:24 UTC, alongosz commented on docs/release_notes/ibexa_dxp_v4.3.md
> +The format of the returned array is:
I would actually rephrase it to emphasize that the format has changed. Sounds too much like completely new exception.

_Background: The method always threw that exception on error, but the array structure/shape was incorrect._

2023-03-02 14:36 UTC, alongosz approved these changes

2023-03-09 07:18 UTC, MagdalenaZuba approved these changes

2023-03-09 07:41 UTC, merged