IBX-5273 - Order management API
ezsystems/developer-documentation pull request #1922
Opened 2023-03-10 15:33 UTC by dabrt

| Question      | Answer |
| ------------- | --- |
| JIRA Ticket   | IBX-5273 |
| Versions      | 4.5 |
| Edition       | Commerce |

Add a description of the API used to manage order information.

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-03-16 12:08 UTC, DominikaK requested changes
Additionally please run cs-fixer and verify that the command works as a whole

2023-03-16 12:08 UTC, DominikaK commented on docs/commerce/order_management/order_management.md
> +description: The order management component covers creating orders, and managing their lifecycle.
```suggestion
description: The order management component covers creating orders and managing their lifecycle.
```

2023-03-16 12:08 UTC, DominikaK commented on docs/commerce/order_management/order_management.md
> +/ ...
Something missing here

2023-03-16 12:08 UTC, DominikaK commented on docs/commerce/order_management/order_management.md
> +The order management component enables users to search for orders, and filter search results.
```suggestion
The order management component enables users to search for orders and filter search results. 
```

2023-03-16 12:08 UTC, DominikaK commented on docs/commerce/order_management/order_management.md
> +From the development perspective, the component enables customization of the order management workflow, integration with external systems to exchange order information.
```suggestion
From the development perspective, the component enables customization of the order management workflow and integration with external systems to exchange order information.
```

2023-03-16 12:08 UTC, DominikaK commented on docs/commerce/order_management/order_management.md
> +The Cart package provides `Ibexa\Contracts\OrderManagement\OrderServiceInterface` Symfony service,
```suggestion
The Cart package provides the `Ibexa\Contracts\OrderManagement\OrderServiceInterface` service, 
```

2023-03-16 12:08 UTC, DominikaK commented on docs/commerce/order_management/order_management_api.md
> +### Get single order by id
```suggestion
### Get single order by ID
```

2023-03-16 12:08 UTC, DominikaK commented on docs/commerce/order_management/order_management_api.md
> +To access a single order by using its numerical id, use the `OrderService::getOrder` method:
```suggestion
To access a single order by using its numerical ID, use the `OrderService::getOrder` method:
```

2023-03-16 12:08 UTC, DominikaK commented on docs/commerce/order_management/order_management_api.md
> +It follows the same search Query pattern as other APIs:
```suggestion
It follows the same search query pattern as other APIs:
```

2023-03-16 12:08 UTC, DominikaK commented on docs/commerce/order_management/order_management_api.md
> +To create an order, use the `orderServiceInterface::createOrder` method and provide
```suggestion
To create an order, use the `OrderService::createOrder` method and provide 
```

2023-03-16 12:08 UTC, DominikaK commented on docs/commerce/order_management/order_management_api.md
> +You can update order after the order is created.
```suggestion
You can update an order after it is created. 
```

2023-03-17 07:25 UTC, konradoboza requested changes

2023-03-17 07:25 UTC, konradoboza commented on code_samples/api/commerce/src/Command/OrderCommand.php
> +use Ibexa\Contracts\Security\Permission\PermissionResolver;
```suggestion
use Ibexa\Contracts\Core\Repository\PermissionResolver;
```

2023-03-17 07:25 UTC, konradoboza commented on code_samples/api/commerce/src/Command/OrderCommand.php
> +use Ibexa\Contracts\Security\User\UserService;
```suggestion
use Ibexa\Contracts\Core\Repository\UserService;
```

2023-03-17 07:25 UTC, konradoboza commented on docs/commerce/order_management/order_management.md
> +The order management component enables users to search for orders,and filter search results.
```suggestion
The order management component enables users to search for orders and filter search results. 
```

2023-03-17 07:25 UTC, konradoboza commented on docs/commerce/order_management/order_management.md
> +The Cart package provides the `Ibexa\Contracts\OrderManagement\OrderServiceInterface` service,
Wrong case of copy&paste.
```suggestion
The Order Management package provides the `Ibexa\Contracts\OrderManagement\OrderServiceInterface` service, 
```

2023-03-17 08:24 UTC, konradoboza approved these changes

2023-03-17 16:07 UTC, merged