IBX-2667 - Anchor menu configuration
ezsystems/developer-documentation pull request #1926
Opened 2023-03-15 16:43 UTC by dabrt

| Question      | Answer |
| ------------- | --- |
| JIRA Ticket   | IBX-2667 |
| Versions      | 4.4 and up |
| Edition       |  |

#### Checklist

- [x] Text renders correctly
- [x] Text has been checked with vale
- [x] Description metadata is up to date
- [x] Code samples are working
- [x] Added link to this PR in relevant JIRA ticket or code PR

2023-03-17 12:12 UTC, juskora requested changes

2023-03-17 12:12 UTC, juskora commented on docs/administration/back_office/content_type_anchor_menu.md
> +Additionally, setting `meta` to `true` adds a toggle for enabling or disabling the Field Type. In this case, it adds the **Enable Taxonomy Entry Assignment for this content type** toggle.
```suggestion
Additionally, setting `meta` to `true` adds a toggle to turn on or off the Field Type. In this case, it adds the **Enable Taxonomy Entry Assignment for this content type** toggle.
```

2023-03-17 12:12 UTC, juskora commented on docs/administration/back_office/content_type_anchor_menu.md
> +Additionally, setting `meta` to `true` adds a toggle for enabling or disabling the Field Type. In this case, it adds the **Enable Taxonomy Entry Assignment for this content type** toggle.
I think it would be nice to add a screenshot with this toggle here.

2023-03-17 12:12 UTC, juskora commented on docs/administration/back_office/content_type_anchor_menu.md
> +With the anchor menu you can promote certain [Field Types](field_types.md), which provide more complex functionality, by detaching them from the [Field definitions](content_model.md#field-definitions
I'm not sure if the word promote suits here, I'd opt for sth like display, etc.

2023-03-22 08:07 UTC, juskora approved these changes
Please add a screenshot to help users see the result.

2023-03-22 08:07 UTC, juskora commented on docs/administration/back_office/content_type_anchor_menu.md
> +In a YAML configuration file, for example, in `config/packages/ibexa_admin_ui.yaml`, the following configuration is made:
```suggestion
In a YAML configuration file, for example, in `config/packages/ibexa_admin_ui.yaml`, add:
```

2023-03-23 07:12 UTC, ciastektk approved these changes
@webhdx, could you confirm please if we can mention Taxonomy here.

2023-03-24 11:08 UTC, merged