IBX-5282 Order management permissions
ezsystems/developer-documentation pull request #1933
Opened 2023-03-23 15:05 UTC by dabrt

| Question      | Answer |
| ------------- | --- |
| JIRA Ticket   | [IBX-5282](https://issues.ibexa.co/browse/IBX-5282) |
| Versions      | 4.5 |
| Edition       | Commerce |

Add a list of persmissions

#### Checklist

- [x] Text renders correctly
- [x] Text has been checked with vale
- [x] Added link to this PR in relevant JIRA ticket or code PR

2023-03-23 17:15 UTC, konradoboza approved these changes

2023-03-24 08:02 UTC, juskora requested changes
Small modifications to keep the permission descriptions consistent.

2023-03-24 08:02 UTC, juskora commented on docs/permissions/permission_use_cases.md
> +- `order/cancel` - to control whether the user can cancel an existing order
```suggestion
- `order/cancel` - to allows user to cancel an existing order 
```

2023-03-24 11:56 UTC, juskora approved these changes

2023-03-24 12:06 UTC, merged