IBX-5190 Missing object types in REST API reference
ezsystems/developer-documentation pull request #1939
Opened 2023-03-30 09:09 UTC by MagdalenaZuba

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-5190
| Versions      | all
| Edition       | 4.4

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-03-31 08:46 UTC, DominikaK approved these changes

2023-03-31 08:46 UTC, DominikaK commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +    description: 'This class is used to update a version.'
```suggestion
    description: 'This class is used to update a content version.'
```
?

2023-03-31 08:46 UTC, DominikaK commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +            description: 'Specifies which property the child locations should be sorted on by default when created.'
```suggestion
            description: 'Specifies which property the child Locations should be sorted on by default when created.'
```

2023-03-31 08:46 UTC, DominikaK commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +            description: 'If set this value overrides the current user as creator.'
```suggestion
            description: 'If set, this value overrides the current user as creator.'
```

2023-03-31 08:46 UTC, DominikaK commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +            description: 'Specifies which property the child locations should be sorted on by default when updated.'
```suggestion
            description: 'Specifies which property the child Locations should be sorted on by default when updated.'
```

2023-03-31 08:46 UTC, DominikaK commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +            description: 'If set this value overrides the current user as creator.'
```suggestion
            description: 'If set, this value overrides the current user as creator.'
```

2023-03-31 08:46 UTC, DominikaK commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +            description: 'The unique ID of the role assignment.'
```suggestion
            description: 'The unique ID of the Role assignment.'
```

2023-03-31 08:46 UTC, DominikaK commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +            description: 'Returns the role to which the user or user group is assigned to.'
```suggestion
            description: 'Returns the Role to which the user or user group is assigned to.'
```

2023-03-31 08:46 UTC, DominikaK commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +            description: 'Returns the limitation of the role assignment.'
```suggestion
            description: 'Returns the Limitation of the Role assignment.'
```

2023-03-31 08:46 UTC, DominikaK commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +            description: 'The update structure for the profile meta data.'
```suggestion
            description: 'The update structure for the profile metadata.'
```

2023-03-31 08:46 UTC, DominikaK commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +            description: 'Name of module, associated with the Policy. For example, content.'
```suggestion
            description: 'Name of module associated with the Policy. For example, content.'
```

2023-03-31 08:46 UTC, DominikaK commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +            description: 'Name of the module function Or all functions with '*'. For example, read.'
```suggestion
            description: 'Name of the module function, or all functions with '*'. For example, read.'
```

2023-03-31 08:46 UTC, DominikaK commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +    description: 'This class is used to creat an attribute group.'
```suggestion
    description: 'This class is used to create an attribute group.'
```

2023-03-31 08:46 UTC, DominikaK commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +    description: 'This class is used to creat a product type.'
```suggestion
    description: 'This class is used to create a product type.'
```

2023-03-31 08:46 UTC, DominikaK commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +    description: 'This class represents a Product type.'
```suggestion
    description: 'This class represents a product type.'
```

2023-03-31 08:46 UTC, DominikaK commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +    description: 'This class is used to unassign taxonomy entry to Content.'
```suggestion
    description: 'This class is used to unassign taxonomy entry from content.'
```

2023-03-31 08:46 UTC, DominikaK commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +    description: 'This class is used to assign taxonomy entry to Content.'
```suggestion
    description: 'This class is used to assign taxonomy entry to content.'
```

2023-03-31 14:38 UTC, adriendupuis requested changes
There is few YAML/RAML syntax errors, see suggestions.

The type `mixed` isn't supported. When the type can't be more precise, [`any`](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#the-any-type) is the RAML keyword to use.

The type [`array`](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#array-type) should be precised with its items type. It will become mandatory with #1871
There is two syntaxes:
```yaml
type: aType[]
```
```yaml
type: array
items: aType
```

2023-03-31 14:38 UTC, adriendupuis commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +            description: 'Name of the module function, or all functions with '*'. For example, read.'
`Unexpected characters near "*'. For example, read.'" at line 2311 (near "description: 'Name of the module function, or all functions with '*'. For example, read.'").`

In YAML (and RAML by extension), to escape a single quote, just double it:

```suggestion
            description: 'Name of the module function, or all functions with ''*''. For example, read.'
```

2023-03-31 14:38 UTC, adriendupuis commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +                type: string
`A colon cannot be used in an unquoted mapping value at line 2330 (near "            type: string").`

Just fix indent error:

```suggestion
    properties:
        login:
            type: string
        password:
            type: string
```

2023-03-31 14:38 UTC, adriendupuis commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +        attributeTypes
`Mapping values are not allowed in multi-line blocks at line 2747 (near "attributeTypes").`

Missing colon:

```suggestion
        attributeTypes:
```

2023-03-31 14:38 UTC, adriendupuis commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +                type: object
`A colon cannot be used in an unquoted mapping value at line 2886 (near "            type: object").`

Indent error fix:
```suggestion
    properties:
        ProductTypeQuery:
            type: object
```

2023-03-31 14:38 UTC, adriendupuis commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +        assignments
`Unable to parse at line 3111 (near "assignments").`

Missing colon:
```suggestion
        assignments:
```

2023-03-31 14:38 UTC, adriendupuis commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +TaxonomyEntryUpdateStruct
`Unable to parse at line 3127 (near "TaxonomyEntryUpdateStruct").`

Missing colon:
```suggestion
TaxonomyEntryUpdateStruct:
```

2023-03-31 14:48 UTC, adriendupuis commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +            type: Parent
`No type found for name 'Parent'`

```suggestion
            type: TaxonomyEntry
```

Probably the same thing for `TaxonomyEntryCreateStruct` and `TaxonomyEntryUpdateStruct`

2023-03-31 14:50 UTC, adriendupuis commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +            type: Entry
`No type found for name 'Entry'`

```suggestion
            type: TaxonomyEntry
```

2023-03-31 14:52 UTC, adriendupuis commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +            type: numeric-string
`No type found for name 'numeric-string'`

```suggestion
            description: 'A numeric string'
            type: string
```

2023-03-31 14:55 UTC, adriendupuis commented
After applying localy all my suggestions, I still have to declare few more types at the end, quick and dirty:

```yaml
DateTime:
    description: https://www.php.net/manual/en/class.datetime.php
    type: object

ContentUpdate:
    type: object

ContentMetadataUpdate:
    type: object

SummaryEntryCollection:
    type: object

Price:
    type: object

VatCategorySummary:
    type: object

Thumbnail:
    type: object

AttributesList:
    type: object
```

2023-04-04 09:13 UTC, adriendupuis commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +             type: string
```suggestion
            type: string
```

2023-04-04 09:25 UTC, adriendupuis commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +             type: string
Done in 24b325688faeab5bf25cfebda159072385718518

2023-04-04 09:32 UTC, adriendupuis approved these changes

2023-04-05 06:20 UTC, merged