IBX-4962: React App page block added
ezsystems/developer-documentation pull request #1947
Opened 2023-04-05 09:56 UTC by julitafalcondusza

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | (https://issues.ibexa.co/browse/IBX-4962)
| Versions      |master
| Edition       | Commerce

React App page block added in Pages.

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-04-11 13:32 UTC, Gengar-i approved these changes

2023-04-11 13:32 UTC, Gengar-i commented on docs/content_management/pages/react_app_block.md
> +description: Create a block that allows an editor to embed a preconfigured React application into a page.
I am not sure if we want to use React application or just React component, but maybe it is just synonym

2023-04-11 13:32 UTC, Gengar-i commented on docs/content_management/pages/react_app_block.md
> +
```suggestion
```

2023-04-13 11:10 UTC, Gengar-i commented on docs/content_management/pages/react_app_block.md
> +          name: Calculator (React)
We have to describe for user that this name should be the same as Component name in /page-builder/react/blocks

2023-04-13 13:43 UTC, dew326 commented on docs/content_management/pages/react_app_block.md
> +In the following example, create `Calculator.jsx` file in `../../../vendor/ibexa/page-builder/components/` directory:
I'm not sure if this is a good idea to write in our documentation to modify files in vendor

2023-04-13 13:45 UTC, dew326 commented on docs/content_management/pages/react_app_block.md
> +Apps that are used as blocks are defined by default in `react/controllers` direction.
it is?

2023-04-13 13:45 UTC, dew326 commented on docs/content_management/pages/react_app_block.md
> +The `assets/apps.js` file is pre-configured with this path.
I think it is separate file

2023-04-19 11:17 UTC, dew326 requested changes

2023-04-19 11:17 UTC, dew326 commented on docs/content_management/pages/react_app_block.md
> +Apps that are used as blocks are defined by default in `react/controllers` direction.
no? Don't know what this folder is?

2023-04-19 11:17 UTC, dew326 commented on docs/content_management/pages/react_app_block.md
> +The `assets/apps.js` file is pre-configured with this path.
we don't have apps.js file?

2023-04-19 11:17 UTC, dew326 commented on docs/content_management/pages/react_app_block.md
> +ibexa_fieldtype_page:
Shouldn't we mention about adding block config from JSON file? @kisztof

2023-04-20 10:56 UTC, dew326 approved these changes

2023-04-20 12:15 UTC, MagdalenaZuba requested changes

2023-04-20 12:15 UTC, MagdalenaZuba commented on docs/content_management/pages/react_app_block.md
> +    }
Where is the opening one: '{'?
Can you double-check code indentation, it looks uneven.

2023-04-20 12:15 UTC, MagdalenaZuba commented on docs/content_management/pages/react_app_block.md
> +You can create the file at any location.
```suggestion
You can place it in any location.
```

2023-04-20 12:17 UTC, MagdalenaZuba commented on docs/content_management/pages/react_app_block.md
> +File has exactly the same structure as regular YAML [block configuration](create_custom_page_block/#configure-block), except:
broken link

2023-04-20 12:17 UTC, MagdalenaZuba commented on docs/content_management/pages/react_app_block.md
> +Sub-keys can be used to specify any of the usual [attributes configuration](page_block_attributes/#page-block-attributes) key:
broken link

2023-04-21 06:02 UTC, MagdalenaZuba approved these changes

2023-04-21 06:13 UTC, merged