IBX 5283 - Describe shipping management
ezsystems/developer-documentation pull request #1950
Opened 2023-04-07 17:16 UTC by dabrt

| Question      | Answer |
| ------------- | --- |
| JIRA Ticket   | IBX 5283 | 
| Versions      | 4.5 |
| Edition       | Commerce |

Describe shipping management

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-04-20 09:35 UTC, mikadamczyk commented on code_samples/api/commerce/src/Command/ShipmentCommand.php
> +            new UpdatedAtCriterion('2023-03-25 09:00:15'),
We have `\Ibexa\Contracts\Checkout\Shipment\Query\Criterion\ShippingMethod`, `\Ibexa\Contracts\Checkout\Shipment\Query\Criterion\CreatedAt`, `\Ibexa\Contracts\Checkout\Shipment\Query\Criterion\UpdatedAt`. If want to use them with such names they need to be imported with an alias

2023-04-20 09:35 UTC, mikadamczyk commented on code_samples/api/commerce/src/Command/ShippingMethodCommand.php
> +        $
something is missing here

2023-04-20 09:35 UTC, mikadamczyk commented on code_samples/api/commerce/src/Command/ShippingMethodCommand.php
> +}
No newline at end of file

2023-04-20 09:35 UTC, mikadamczyk commented on code_samples/front/shop/shipping_management/config/packages/ibexa.yaml
> +                    to: delivered
No newline at end of file

2023-04-20 09:35 UTC, mikadamczyk commented on code_samples/front/shop/shipping_management/config/packages/ibexa.yaml
> +        ibexa_shipment:
Current version https://github.com/ibexa/checkout/blob/58c6f477a5145da117cdff8201824739ca701d6e/src/bundle/Resources/config/workflow.yaml#L60

2023-04-20 09:35 UTC, mikadamczyk commented on code_samples/front/shop/shipping_management/config/packages/ibexa.yaml
> +                        translation_domain: "shipment"
Shipping methods are fetched from the database only

2023-04-21 09:59 UTC, mikadamczyk reviewed
Two types of shipping methods are available by default: flat rate and free shipping. The flat rate method has a fixed price. In the free shipping method, a minimum price of a cart is defined. Based on them, the user can create concrete shipping methods. If the shipping method is enabled in the admin panel and is available for a given basket, then it will be displayed on the list of available shipping methods, during checkout. For example, the currency or the value of the basket for free methods is checked.

2023-04-21 09:59 UTC, mikadamczyk commented on code_samples/api/commerce/src/Command/ShipmentCommand.php
> +use Ibexa\Contracts\Shipping\ShipmentServiceInterface;
```suggestion
use Ibexa\Contracts\Checkout\ShipmentServiceInterface;
```
Currently, namespaces are not `Shipping` but `Checkout`

2023-04-21 09:59 UTC, mikadamczyk commented on code_samples/api/commerce/src/Command/ShipmentCommand.php
> +use Ibexa\Contracts\Shipping\Value\ShipmentCreateStruct;
```suggestion
use Ibexa\Contracts\Checkout\Shipment\ShipmentCreateStruct;
```

2023-04-21 09:59 UTC, mikadamczyk commented on code_samples/api/commerce/src/Command/ShipmentCommand.php
> +use Ibexa\Contracts\Shipping\Value\ShipmentMetadataUpdateStruct;
```suggestion
```
No such class in `Shipment` code base

2023-04-21 09:59 UTC, mikadamczyk commented on code_samples/api/commerce/src/Command/ShipmentCommand.php
> +use Ibexa\Contracts\Shipping\Value\ShipmentQuery;
```suggestion
use Ibexa\Contracts\Checkout\Shipment\ShipmentQuery;
```

2023-04-21 09:59 UTC, mikadamczyk commented on code_samples/api/commerce/src/Command/ShipmentCommand.php
> +use Ibexa\Contracts\Shipping\Value\ShipmentUpdateStruct;
```suggestion
use Ibexa\Contracts\Checkout\Shipment\ShipmentUpdateStruct;
```

2023-04-21 09:59 UTC, mikadamczyk commented on code_samples/api/commerce/src/Command/ShipmentCommand.php
> +      UserService $userService,
```
use \Ibexa\Contracts\Core\Repository\UserService;
```

2023-04-21 09:59 UTC, mikadamczyk commented on code_samples/api/commerce/src/Command/ShipmentCommand.php
> +      ShippingServiceInterface $shipmentService
```suggestion
      ShipmentServiceInterface $shipmentService
```

2023-04-21 09:59 UTC, mikadamczyk commented on code_samples/api/commerce/src/Command/ShipmentCommand.php
> +    private ShippingServiceInterface $shipmentService;
```suggestion
    private ShipmentServiceInterface $shipmentService;
```

2023-04-21 09:59 UTC, mikadamczyk commented on code_samples/api/commerce/src/Command/ShipmentCommand.php
> +            new ShippingMethodCriterion(1),
`use Ibexa\Contracts\Checkout\Shipment\Query\Criterion\ShippingMethod;` import is needed and then we can use it here 

```
new ShippingMethod(1),
```
or 
`use Ibexa\Contracts\Checkout\Shipment\Query\Criterion\ShippingMethod as ShippingMethodCriterion;`
and then 
```
new ShippingMethodCriterion(1),
```

2023-04-21 09:59 UTC, mikadamczyk commented on code_samples/api/commerce/src/Command/ShipmentCommand.php
> +        $shipmentQuery = new ShipmentQuery(new LogicalOr(...$shipmentCriterions));
```
use Ibexa\Contracts\Checkout\Shipment\Query\Criterion\LogicalOr;
```
import is missing

2023-04-21 09:59 UTC, mikadamczyk commented on code_samples/api/commerce/src/Command/ShipmentCommand.php
> +        $shipmentCreateStruct = new ShipmentCreateStruct();
`ShipmentCreateStruct` has 3 mandatory parameters
```
    public function __construct(
        ShippingMethodInterface $method,
        OrderInterface $order,
        Money $amount
    )
```

2023-04-21 09:59 UTC, mikadamczyk commented on code_samples/api/commerce/src/Command/ShipmentCommand.php
> +        $updatedShipment = $this->shipmentService->updateShipment($shipment, $shipmentUpdateStruct);
`Ibexa\Contracts\Core\Collection\ArrayMap`
import is missing

2023-04-21 09:59 UTC, mikadamczyk commented on code_samples/api/commerce/src/Command/ShippingMethodCommand.php
> +use Ibexa\Contracts\Checkout\Value\ShippingMethod\ShippingMethodCreateStruct;
import is not used
```suggestion
```

2023-04-21 09:59 UTC, mikadamczyk commented on code_samples/api/commerce/src/Command/ShippingMethodCommand.php
> +use Ibexa\Contracts\Checkout\Value\ShippingMethod\ShippingMethodUpdateStruct;
```suggestion
```

2023-04-21 09:59 UTC, mikadamczyk commented on code_samples/api/commerce/src/Command/ShippingMethodCommand.php
> +    private PermissionResolver $permissionResolver;
`use Ibexa\Contracts\Core\Repository\PermissionResolver;`
import is missing

2023-04-21 09:59 UTC, mikadamczyk commented on code_samples/api/commerce/src/Command/ShippingMethodCommand.php
> +        $query->orderBy('name', 'ASC');
Method 'orderBy' not found in \Ibexa\Contracts\Checkout\Value\ShippingMethod\ShippingMethodQuery

2023-04-21 09:59 UTC, mikadamczyk commented on code_samples/api/commerce/src/Command/ShippingMethodCommand.php
> +        $deleteTranslationStruct = new ShippingMethodDeleteTranslationStruct();
class `ShippingMethodDeleteTranslationStruct` has mandatory constructor parameters: `$shippingMethod` and `$languageCode`

2023-04-24 10:38 UTC, DominikaK requested changes

2023-04-24 10:38 UTC, DominikaK commented on docs/commerce/shipping_management/shipping_method_api.md
> +To delete shipping method translation, use the `ShippingMethodServiceInterface::deleteShippingMethod` method.
```suggestion
To delete shipping method translation, use the `ShippingMethodServiceInterface::deleteShippingMethodTranslation` method.
```

2023-04-24 10:38 UTC, DominikaK commented on docs/commerce/shipping_management/configure_shipment.md
> +    When you modify the workflow configuration, make sure you properly set user [permissions](permission_use_cases.md#commerce) to the shipping management component.
```suggestion
    When you modify the workflow configuration, make sure you properly set user [permissions](permission_use_cases.md#commerce) for the shipping management component.
```

2023-04-24 10:38 UTC, DominikaK commented on docs/commerce/shipping_management/configure_shipment.md
> +The default shipment workflow configuration looks as follows. `ibexa_shipment` key is used by default, you can replace it with your custom workflow identifier if needed.
Like in payment, I'd avoid quoting the default workflow here, instead, later give an example under Custom workflows

2023-04-24 10:38 UTC, DominikaK commented on docs/commerce/shipping_management/configure_shipment.md
> +You can define the shipping methods [in the UI]([[= user_doc =]]/commerce/shipping_management/configure_shipping_method.md).
```suggestion
You can define the shipping methods [in the UI]([[= user_doc =]]/commerce/shipping_management/configure_shipping_method/).
```

2023-04-24 10:38 UTC, DominikaK commented on docs/commerce/shipping_management/shipment_api.md
> +description: Use PHP API to manage shipments n Commerce: create, update and delete shipments.
```suggestion
description: Use PHP API to manage shipments in Commerce to create, update and delete shipments.
```

2023-04-24 10:38 UTC, DominikaK commented on docs/commerce/shipping_management/shipment_api.md
> +the `Ibexa\Contracts\Checkout\Value\ShipmentCreateStruct` object that passes two parameters, the `shippingMethod` string and `Money` object.
```suggestion
an `Ibexa\Contracts\Checkout\Value\ShipmentCreateStruct` object that takes two parameters, a `shippingMethod` string and a `Money` object.
```

2023-04-24 10:38 UTC, DominikaK commented on docs/commerce/shipping_management/shipment_api.md
> +To delete a shipment from the system, use the ``ShipmentService::deleteShipment` method:
```suggestion
To delete a shipment from the system, use the `ShipmentService::deleteShipment` method:
```

2023-04-24 10:38 UTC, DominikaK commented on docs/commerce/shipping_management/shipping_management.md
> +    Two types of shipping methods are available by default: "flat rate" and "free".
```suggestion
    Two types of shipping methods are available by default: `flat rate` and `free`.
```

2023-04-24 10:38 UTC, DominikaK commented on docs/commerce/shipping_management/shipping_method_api.md
> +To access a shipping method  by using its identifier, use the `ShippingMethodServiceInterface::getShippingMethod` method.
```suggestion
To access a shipping method by using its identifier, use the `ShippingMethodServiceInterface::getShippingMethod` method.
```

2023-04-25 06:41 UTC, DominikaK approved these changes

2023-04-25 07:03 UTC, DominikaK approved these changes

2023-04-25 07:26 UTC, mikadamczyk commented on code_samples/api/commerce/src/Command/ShipmentCommand.php
> +            new ShippingMethod($this->shippingMethodService->getShippingMethod('free'), ),
```suggestion
            new ShippingMethod($this->shippingMethodService->getShippingMethod('free')),
```

2023-04-25 07:26 UTC, mikadamczyk commented on code_samples/api/commerce/src/Command/ShipmentCommand.php
> +        $shipmentCriterions = [
```suggestion
        $shipmentCriteria = [
```

2023-04-25 07:26 UTC, mikadamczyk commented on code_samples/api/commerce/src/Command/ShippingMethodCommand.php
> +        $output->writeln(sprintf('Got shipping method by identifier "%s" and type "%s".', $shippingMethodIdentifier, $shippingMethod->getType()->getIdentifier()));
```suggestion
        $output->writeln(
            sprintf(
                'Got shipping method by identifier "%s" and type "%s".', 
                $shippingMethodIdentifier, 
                $shippingMethod->getType()->getIdentifier()
            )
        );
```

2023-04-25 07:26 UTC, mikadamczyk commented on code_samples/api/commerce/src/Command/ShippingMethodCommand.php
> +            $output->writeln($shippingMethod->getIdentifier() . ': ' . $shippingMethod->getName() . '- ' . $shippingMethod->getDescription());
```suggestion
            $output->writeln(
                sprintf(
                    '%s: %s- %s',
                    $shippingMethod->getIdentifier(),
                    $shippingMethod->getName(),
                    $shippingMethod->getDescription()
                )
            );
```

2023-04-25 07:26 UTC, mikadamczyk commented on code_samples/api/commerce/src/Command/ShipmentCommand.php
> +    protected function execute(InputInterface $input, OutputInterface $output)
```suggestion
    protected function execute(InputInterface $input, OutputInterface $output): int
```

2023-04-25 07:26 UTC, mikadamczyk commented on code_samples/api/commerce/src/Command/ShipmentCommand.php
> +use Ibexa\Contracts\Checkout\Shipment\Query\Criterion\CreatedAt;
```suggestion
use DateTime;
use Ibexa\Contracts\Checkout\Shipment\Query\Criterion\CreatedAt;
```

2023-04-25 09:17 UTC, mikadamczyk approved these changes

2023-04-25 09:17 UTC, mikadamczyk commented on code_samples/api/commerce/src/Command/ShipmentCommand.php
> +            new UpdatedAt(new \DateTime('2023-03-25 09:00:15')),
why is this class not imported?

2023-04-25 09:59 UTC, dabrt commented on code_samples/api/commerce/src/Command/ShipmentCommand.php
> +            new UpdatedAt(new \DateTime('2023-03-25 09:00:15')),
It is, in line 19

2023-04-25 10:03 UTC, merged