IBX-5309 - Search criteria and sort clauses doc
ezsystems/developer-documentation pull request #1955
Opened 2023-04-14 07:59 UTC by dabrt

| Question      | Answer |
| ------------- | --- |
| JIRA Ticket   | [IBX-5309](https://issues.ibexa.co/browse/IBX-5309) |
| Versions      | 4.5 |
| Edition       | Commerce |

Document search criteria and sort clauses used in Payment management

#### Checklist

- [x] Text renders correctly
- [x] Text has been checked with vale
- [x] Description metadata is up to date

2023-04-17 10:24 UTC, juskora submitted a review, later dismissed

2023-04-18 08:35 UTC, dabrt commented on docs/search/criteria_reference/payment_createdat_criterion.md
> +The `CreatedAtCriterion` Search Criterion searches for payments based on the date when they were initiated.
Let's see what Adam says, ok?

2023-04-19 05:34 UTC, adamwojs requested changes
I'm sorry but current state of this PR is unacceptable: 

- Code snippets contains references to non existing classes or other symbols
- Code snippets are inconsistent. Sometimes we refer to criteria using  FQCN sometime we do not. Formatting is no applied  
- Arguments passed to criteria have invalid type e.g. CreatedAt criterion expects DateTimeInterface but we are passing string

This needs to be fixed before we proceed to next step of code review. 

You find correct usage examples in integration tests
* https://github.com/ibexa/payment/blob/65cfb7a8caf20fea1898300a1fe6dcec7b4ab06b/tests/integration/PaymentServiceTest.php#L300-L495
* https://github.com/ibexa/payment/blob/c51cfdf22311af8b593e8a76d12d8d07fb7fe71d/tests/integration/PaymentMethodServiceTest.php#L251-L455

2023-04-19 05:34 UTC, adamwojs commented on docs/search/criteria_reference/payment_createdat_criterion.md
> +    Ibexa\Contracts\Payment\Value\Payment\Query\Criterion\Operator::GTE
There is no such class as `Ibexa\Contracts\Payment\Value\Payment\Query\Criterion\Operator`

2023-04-19 05:34 UTC, adamwojs commented on docs/search/criteria_reference/payment_currency_criterion.md
> +$query->query = new Ibexa\Contracts\Payment\Value\Payment\Query\Criterion\Currency('EUR');
```suggestion
$query->query = new \Ibexa\Contracts\Payment\Payment\Query\Criterion\Currency('EUR');
```

2023-04-19 09:32 UTC, DominikaK commented
It seems the incorrect datetime examples were based on https://doc.ibexa.co/en/master/search/criteria_reference/createdat_criterion/#example, which contains the same error, will be fixed, but outside the scope of this PR.

2023-04-19 13:10 UTC, dabrt commented on docs/search/criteria_reference/payment_createdat_criterion.md
> +The `CreatedAtCriterion` Search Criterion searches for payments based on the date when they were initiated.
@adamwojs Would you say initiated or created?

2023-04-19 13:12 UTC, dabrt commented
@adamwojs please re-review the PR

Another question, out of the blue - don't we want to sort payments by their value? Being a financial manager I might find it useful to be able to filter out payments for a certain amount.

2023-04-19 14:45 UTC, dabrt commented on docs/search/criteria_reference/payment_createdat_criterion.md
> +- `operator` - optional operator constant (EQ, GT, GTE, LT, LTE)
```suggestion
- `operator` - optional operator string (EQ, GT, GTE, LT, LTE)
```

2023-04-19 14:45 UTC, dabrt commented on docs/search/criteria_reference/payment_method_createdat_criterion.md
> +- `operator` - optional operator constant (EQ, GT, GTE, LT, LTE)
```suggestion
- `operator` - optional operator string (EQ, GT, GTE, LT, LTE)
```

2023-04-19 14:46 UTC, dabrt commented on docs/search/criteria_reference/payment_method_updatedat_criterion.md
> +- `operator` - optional operator constant (EQ, GT, GTE, LT, LTE)
```suggestion
- `operator` - optional operator string (EQ, GT, GTE, LT, LTE)
```

2023-04-20 07:33 UTC, DominikaK approved these changes

2023-04-20 07:33 UTC, DominikaK commented on docs/search/criteria_reference/payment_method_search_criteria.md
> +With these criteria you can filter payment methods by their payment method identifier, payment method creation date, payment method type, status, and so on.
```suggestion
With these Criteria you can filter payment methods by their payment method identifier, payment method creation date, payment method type, status, and so on.
```

2023-04-20 07:33 UTC, DominikaK commented on docs/search/criteria_reference/payment_method_search_criteria.md
> +## Payment method search criteria
```suggestion
## Payment method Search Criteria
```

2023-04-20 07:33 UTC, DominikaK commented on docs/search/criteria_reference/payment_search_criteria.md
> +With these criteria you can filter payments by their payment identifier, payment creation date, payment status, payment method, order, and so on.
```suggestion
With these Criteria you can filter payments by their payment identifier, payment creation date, payment status, payment method, order, and so on.
```

2023-04-20 07:33 UTC, DominikaK commented on docs/search/criteria_reference/payment_search_criteria.md
> +## Payment search criteria
```suggestion
## Payment Search Criteria
```

2023-04-20 07:33 UTC, DominikaK commented on docs/search/sort_clause_reference/payment_method_sort_clauses.md
> +---
```suggestion
```

2023-04-20 07:33 UTC, DominikaK commented on docs/search/sort_clause_reference/payment_sort_clauses.md
> +---
```suggestion
```

2023-04-20 07:34 UTC, DominikaK commented on docs/search/criteria_reference/payment_createdat_criterion.md
> +The `CreatedAtCriterion` Search Criterion searches for payments based on the date when they were initiated.
I'd opt for "created" as well. To me "initiated" refers more to a payment in a banking system, but here we're talking about creating a payment (object) inside our system

2023-04-20 09:18 UTC, dabrt commented on docs/search/criteria_reference/payment_createdat_criterion.md
> +The `CreatedAt` Search Criterion searches for payments based on the date when they were initiated.
```suggestion
The `CreatedAt` Search Criterion searches for payments based on the date when they were created.
```

2023-04-20 09:19 UTC, dabrt commented on docs/search/criteria_reference/payment_search_criteria.md
> +|[CreatedAt](payment_createdat_criterion.md)|Date and time when payment was initiated|
```suggestion
|[CreatedAt](payment_createdat_criterion.md)|Date and time when payment was created|
```

2023-04-20 09:19 UTC, dabrt commented on docs/search/sort_clause_reference/payment_createdat_sort_clause.md
> +The `CreatedAt` Sort Clause sorts search results by the date and time when the payment was initiated.
```suggestion
The `CreatedAt` Sort Clause sorts search results by the date and time when the payment was created.
```

2023-04-20 09:19 UTC, dabrt commented on docs/search/sort_clause_reference/payment_sort_clauses.md
> +|[CreatedAt](payment_createdat_sort_clause.md)|Date and time when payment was initiated|
```suggestion
|[CreatedAt](payment_createdat_sort_clause.md)|Date and time when payment was created|
```

2023-04-28 19:04 UTC, merged