IBX-5281 - Describe order processing workflow
ezsystems/developer-documentation pull request #1973
Opened 2023-04-26 12:56 UTC by dabrt

| Question      | Answer |
| ------------- | --- |
| JIRA Ticket   | I[BX-5281](https://issues.ibexa.co/browse/IBX-5281) |
| Versions      | master, 4.5 |
| Edition       | Commerce |

Describe order processing workflow in ints current, simplified form

#### Checklist

- [x] Text renders correctly
- [x] Text has been checked with vale
- [x] Description metadata is up to date
- [x] Code samples are working
- [x] Added link to this PR in relevant JIRA ticket or code PR

2023-04-26 13:06 UTC, konradoboza approved these changes

2023-04-26 13:06 UTC, konradoboza commented on code_samples/front/shop/order-management/config/packages/ibexa.yaml
> +                workflow: custom_order_workflow
```suggestion
                workflow: custom_order_workflow

```

2023-04-27 07:03 UTC, juskora requested changes

2023-04-27 11:00 UTC, juskora approved these changes

2023-04-27 11:42 UTC, merged