IBX-5416 - Add ShipmentOwner OrderOwner limitation
ezsystems/developer-documentation pull request #1974
Opened 2023-04-27 11:29 UTC by dabrt

| Question      | Answer |
| ------------- | --- |
| JIRA Ticket   | [IBX-5416](https://issues.ibexa.co/browse/IBX-5416) |
| Versions      | 4.5, master |
| Edition       | Commerce |

Add a description of two new limitations:  ShipmentOwner and OrderOwner 

https://github.com/ibexa/checkout/pull/100
https://github.com/ibexa/order-management/pull/52

#### Checklist

- [x] Text renders correctly
- [x] Text has been checked with vale
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-04-27 12:08 UTC, DominikaK approved these changes

2023-04-27 12:20 UTC, konradoboza requested changes

2023-04-27 12:20 UTC, konradoboza commented on docs/permissions/limitation_reference.md
> +|"all"| none |Users can access all orders.|
This isn't the case. We don't need that limitation as it's basically an equivalent of adding `Order/*` policy without any limitations.

2023-04-27 12:20 UTC, konradoboza commented on docs/permissions/limitation_reference.md
> +|"all"| none |Users can access all shipments.|
I believe the above remark stands here as well, ping @mikadamczyk.

2023-04-28 06:48 UTC, konradoboza approved these changes

2023-04-28 08:41 UTC, merged