IBX-5973: Virtual Products checkout added in 'Checkout' page
ezsystems/developer-documentation pull request #2034
Opened 2023-06-27 12:15 UTC by julitafalcondusza

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | (https://issues.ibexa.co/browse/IBX-5973)
| Versions      | master
| Edition       | Commerce

Virtual Products checkout added in 'Checkout' page.

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-06-28 16:41 UTC, radzyu requested changes
Should we also mention somewhere how we deal with payment method filtering? @ciastektk ?

2023-06-28 16:41 UTC, radzyu commented on docs/commerce/checkout/checkout.md
> +Virtual product is a special type of a [Product](products.md). Virtual products are a non-tangible items such as memberships, services, warranties.
without "a" as you used items that is plural

2023-06-28 16:41 UTC, radzyu commented on docs/commerce/checkout/checkout.md
> +While purchasing virtual product, you only have to fill in Billing address.
and select relevant payment method.

2023-06-28 16:41 UTC, radzyu commented on docs/pim/products.md
> +- `Physical` - a tangible products with assigned stock.
do we need "a" here?

2023-06-30 08:52 UTC, radzyu approved these changes

2023-07-05 07:57 UTC, ciastektk approved these changes

2023-07-05 09:09 UTC, MagdalenaZuba approved these changes

2023-07-05 09:09 UTC, MagdalenaZuba commented on docs/commerce/checkout/checkout.md
> +Virtual product is a special type of a [Product](products.md). Virtual products are non-tangible items such as memberships, services, warranties.
```suggestion
Virtual product is a special type of a [product](products.md). Virtual products are non-tangible items such as memberships, services, warranties. 
```

2023-07-05 09:09 UTC, MagdalenaZuba commented on docs/commerce/checkout/checkout.md
> +While purchasing virtual product, you only have to fill in Billing address and select relevant payment method.
```suggestion
While purchasing virtual product, you only have to fill in the billing address and select relevant payment method. 
```

2023-07-10 08:44 UTC, merged