IBX-6043: Owner criterion added in Shipment and Order search criteria
ezsystems/developer-documentation pull request #2054
Opened 2023-07-10 13:27 UTC by julitafalcondusza

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | (https://issues.ibexa.co/browse/IBX-5994)
| Versions      | master
| Edition       | Commerce

Owner criterion added in Shipment and Order search criteria

#### Checklist

- [x] Text renders correctly
- [x] Text has been checked with vale
- [x] Description metadata is up to date
- [x] Code samples are working
- [x] PHP code samples have been fixed with PHP CS fixer
- [x] Added link to this PR in relevant JIRA ticket or code PR

2023-07-11 12:04 UTC, konradoboza requested changes

2023-07-11 12:04 UTC, konradoboza commented on docs/search/criteria_reference/order_owner_criterion.md
> +The `Owner` Criterion searches for orders based on the user reference.
Name is slightly different than in Shipments/Payments:
```suggestion
The `OwnerCriterion` Criterion searches for orders based on the user reference.
```

2023-07-11 12:04 UTC, konradoboza commented on docs/search/criteria_reference/order_owner_criterion.md
> +- `user reference` - \Ibexa\Contracts\Core\Repository\Values\User\UserReference(int $userId)
```suggestion
- `UserReference` object - \Ibexa\Contracts\Core\Repository\Values\User\UserReference(int $userId)
```

2023-07-11 12:04 UTC, konradoboza commented on docs/search/criteria_reference/order_owner_criterion.md
> +Owner Criterion accepts also owners board:
```suggestion
`OwnerCriterion` accepts also multiple values:
```

2023-07-11 12:04 UTC, konradoboza commented on docs/search/criteria_reference/order_search_criteria.md
> +|[OwnerCriterion](order_owner_criterion.md)|Owner identifier based on the user reference|
```suggestion
|[OwnerCriterion](order_owner_criterion.md)|Owner based on the user reference|
```

2023-07-11 12:04 UTC, konradoboza commented on docs/search/criteria_reference/shipment_owner_criterion.md
> +- `user reference` - \Ibexa\Contracts\Core\Repository\Values\User\UserReference(int $userId)
Same as above.

2023-07-11 12:04 UTC, konradoboza commented on docs/search/criteria_reference/shipment_owner_criterion.md
> +Owner Criterion accepts also owners board:
```suggestion
Owner Criterion accepts also multiple values:
```

2023-07-11 12:04 UTC, konradoboza commented on docs/search/criteria_reference/shipment_search_criteria.md
> +|[Owner](shipment_owner_criterion.md)|Owner identifier based on the user reference|
```suggestion
|[Owner](shipment_owner_criterion.md)|Owner based on the user reference|
```

2023-07-11 12:15 UTC, konradoboza approved these changes

2023-07-11 12:50 UTC, radzyu approved these changes

2023-07-12 06:12 UTC, adamwojs approved these changes

2023-07-12 06:22 UTC, juskora approved these changes

2023-07-12 06:31 UTC, merged