IBX-5948: 'Create Custom Name Schema strategy' page added in PIM
ezsystems/developer-documentation pull request #2056
Opened 2023-07-11 13:03 UTC by julitafalcondusza

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | (https://issues.ibexa.co/browse/IBX-5948)
| Versions      | master
| Edition       | Content

'Create Custom Name Schema strategy' page added in PIM

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-07-13 04:29 UTC, adamwojs commented on code_samples/catalog/custom_name_schema_strategy/NameSchema/NameSchemaStrategyInterface.php
> +<?php declare(strict_types=1);
```suggestion
<?php 

declare(strict_types=1);
```

2023-07-13 04:29 UTC, adamwojs commented on code_samples/catalog/custom_name_schema_strategy/NameSchema/NameSchemaStrategyInterface.php
> +final class NameSchemaStrategyInterface implements NameSchemaStrategyInterface
```suggestion
final class CustomNameSchemaStrategy implements NameSchemaStrategyInterface
```

2023-07-13 04:29 UTC, adamwojs commented on code_samples/catalog/custom_name_schema_strategy/src/bundle/Resources/config/services/name_schema.yaml
> +    App\Attribute\NameSchema\CustomNameSchemaStrategy: ~
```suggestion
    App\Attribute\NameSchema\CustomNameSchemaStrategy: ~
    
```

2023-07-13 04:29 UTC, adamwojs commented on docs/pim/create_custom_name_schema_strategy.md
> +Start by creating a `CustomNameSchemaStrategy` class, which implements `\Ibexa\ProductCatalog\NameSchema\NameSchemaStrategyInterface`. This class is responsible for converting attribute values into a
If `\Ibexa\ProductCatalog\NameSchema\NameSchemaStrategyInterface` is extension point (it should be) then it needs to be moved to contracts // cc @kisztof

2023-07-13 04:29 UTC, adamwojs commented on mkdocs.yml
> +        - Create Custom Name Schema strategy: pim/create_custom_name_schema_strategy.md
Capitalization is inconsistent

2023-07-28 06:47 UTC, adamwojs approved these changes

2023-07-28 06:47 UTC, adamwojs commented on code_samples/catalog/percent_name_schema_strategy/NameSchema/NameSchemaStrategyInterface.php
> +final class NameSchemaStrategyInterface implements NameSchemaStrategyInterface
```suggestion
final class PercentNameSchemaStrategy implements NameSchemaStrategyInterface
```

2023-08-03 08:07 UTC, MagdalenaZuba requested changes

2023-08-03 08:07 UTC, MagdalenaZuba commented on docs/pim/create_custom_name_schema_strategy.md
> +Make sure you the attributes are configured correctly. Each attribute that you want to include in the URL alias must have a name schema strategy.
```suggestion
Make sure the attributes are configured correctly.
Each attribute that you want to include in the URL alias must have a name schema strategy.
```

2023-08-03 08:07 UTC, MagdalenaZuba commented on docs/pim/create_custom_name_schema_strategy.md
> +# Create custom Name Schema strategy
```suggestion
# Create custom name schema strategy
```

2023-08-03 08:07 UTC, MagdalenaZuba commented on docs/pim/create_custom_name_schema_strategy.md
> +description: Create custom Name Schema strategy to generate URL aliases based on attribute values.
```suggestion
description: Create custom name schema strategy to generate URL aliases based on attribute values.
```

2023-08-03 08:07 UTC, MagdalenaZuba commented on docs/pim/create_custom_name_schema_strategy.md
> +This ensures that the custom Name Schema strategy is available for use in generating URL aliases based on attribute values.
```suggestion
This ensures that the custom name schema strategy is available for use in generating URL aliases based on attribute values.
```

2023-08-03 09:38 UTC, dabrt commented on docs/pim/create_custom_name_schema_strategy.md
> +Make sure the attributes are configured correctly.
Why are we doing it? What problem are we solving or what improvement implementing?

2023-08-04 09:27 UTC, MagdalenaZuba commented on mkdocs.yml
> +        - Create custom Name Schema strategy: pim/create_custom_name_schema_strategy.md
```suggestion
        - Create custom name schema: pim/create_custom_name_schema_strategy.md
```

2023-08-04 09:28 UTC, MagdalenaZuba approved these changes

2023-08-04 09:54 UTC, dabrt approved these changes

2023-08-04 11:47 UTC, merged