IBX-6185: Add file upload blocklist to security checklist
ezsystems/developer-documentation pull request #2059
Opened 2023-07-13 14:32 UTC by glye

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-6185
| Versions      | All supported
| Edition       | All

Note: The setting is called `ezsettings.default.io.file_storage.file_type_blacklist` in v2.5 and is there located in the file `eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml` of ezpublish-kernel.

#### See also
PR for adding more file types to this setting: https://github.com/ezsystems/ezpublish-kernel/pull/3153

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [x] ~Code samples are working~
- [x] ~PHP code samples have been fixed with PHP CS fixer~
- [x] Added link to this PR in relevant JIRA ticket or code PR

2023-07-14 06:42 UTC, MagdalenaZuba approved these changes

2023-07-17 07:32 UTC, adamwojs requested changes
1) List of blocked file extensions should be placed in documentation
2) Instructions on how to configure blacklist is missing 

Let's try to make this checklist more convenient for a reader :wink:

2023-07-17 07:54 UTC, glye commented
@adamwojs I'll add the list of current defaults, good idea. As for instructions, I don't really see what to add..? Maybe the doc team can help see what's missing?

2023-07-17 08:51 UTC, glye commented
@adamwojs Improved explanation, and default list added: https://github.com/ezsystems/developer-documentation/pull/2059/commits/084513e14eedceef6fc58b0340cdf3ab6f2c60f9

2023-07-21 06:46 UTC, MagdalenaZuba requested changes

2023-07-21 06:46 UTC, MagdalenaZuba commented on docs/infrastructure_and_maintenance/security/security_checklist.md
> +You should adapt this list to your needs. Note that `svg` images are blocked because they may contain JavaScript code. If you opt to allow them, make sure you take steps to mitigate this risk.
```suggestion
You should adapt this list to your needs. Note that `svg` images are blocked because they may contain JavaScript code.
If you opt to allow them, make sure you take steps to mitigate the risk.
```

2023-07-21 06:46 UTC, MagdalenaZuba commented on docs/infrastructure_and_maintenance/security/security_checklist.md
> +The default list of blocked file types contains: `hta htm html jar js jse pgif phar php php3 php4 php5 phps phpt pht phtml svg swf xhtm xhtml`
```suggestion
The default list of blocked file types contains: `hta htm html jar js jse pgif phar php php3 php4 php5 phps phpt pht phtml svg swf xhtm xhtml`.
```

2023-07-21 06:46 UTC, MagdalenaZuba commented on docs/infrastructure_and_maintenance/security/security_checklist.md
> +The `ibexa.site_access.config.default.io.file_storage.file_type_blacklist` setting defined in the config file `src/bundle/Core/Resources/config/default_settings.yml` in the Core bundle lists filename
```suggestion
The `ibexa.site_access.config.default.io.file_storage.file_type_blacklist` setting is defined in the config file `src/bundle/Core/Resources/config/default_settings.yml` in the Core bundle.
It prevents uploading files that might be executed on the server, a Remote Code Execution (RCE) vulnerability by listing filename extensions for files that shouldn't be uploaded.
Attempting to upload files from the list results in an error message.
There are also other safety measures in place, like using the web server configuration to block execution of uploaded scripts, see the next point.
```

2023-07-21 10:37 UTC, MagdalenaZuba commented on docs/infrastructure_and_maintenance/security/security_checklist.md
> +The `ibexa.site_access.config.default.io.file_storage.file_type_blacklist` setting defined in the config file `src/bundle/Core/Resources/config/default_settings.yml` in the Core bundle lists filename
Perfect 😄

2023-07-21 12:59 UTC, MagdalenaZuba approved these changes

2023-07-21 13:05 UTC, merged