JS events fired by Page Builder
ezsystems/developer-documentation pull request #2060
Opened 2023-07-13 15:55 UTC by adriendupuis

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | 
| Versions      | 
| Edition       | 

How have custom block's JS also working in the Page Builder preview

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-07-24 12:43 UTC, dew326 approved these changes

2023-07-25 07:02 UTC, MagdalenaZuba requested changes

2023-07-25 07:02 UTC, MagdalenaZuba commented on docs/content_management/pages/create_custom_page_block.md
> +One to call it when a block is added or configured in the Page Builder.
```suggestion
The other one to call it when a block is added or configured in the Page Builder.
```

2023-07-25 08:10 UTC, adriendupuis commented on docs/content_management/pages/create_custom_page_block.md
> +    If you considere using React JavaScript library, see [React App block](react_app_block.md).
```suggestion
!!! note

    For the addition of your custom block's JS and CSS files, see [Assets](assets.md).
    
    If you consider using React JavaScript library, see [React App block](react_app_block.md).
```

2023-07-25 09:15 UTC, MagdalenaZuba approved these changes

2023-07-25 14:54 UTC, merged