Changes to triggers doc
ezsystems/developer-documentation pull request #2063
Opened 2023-07-17 13:48 UTC by dabrt

| Question      | Answer |
| ------------- | --- |
| JIRA Ticket   | none |
| Versions      | master |
| Edition       | all |

Implement changes requested in #2022 

#### Checklist

- [x] Text renders correctly
- [x] Text has been checked with vale

2023-07-18 07:54 UTC, adamwojs commented on docs/personalization/integrate_recommendation_service.md
> +- a number of repetitionsEmail triggers are then processed on the Personalization server and responses are delivered to a dedicated endpoint.
```suggestion
- a number of repetitions

Email triggers are then processed on the Personalization server and responses are delivered to a dedicated endpoint.
```

missing new line ?

2023-07-18 09:29 UTC, juskora requested changes

2023-07-18 09:29 UTC, juskora commented on docs/personalization/integrate_recommendation_service.md
> +- a number of repetitionsEmail triggers are then processed on the Personalization server and responses are delivered to a dedicated endpoint.
I think it should be this way?

2023-07-19 07:24 UTC, juskora approved these changes

2023-07-20 06:26 UTC, MagdalenaZuba approved these changes

2023-07-20 06:28 UTC, MagdalenaZuba approved these changes

2023-07-20 06:28 UTC, MagdalenaZuba commented on docs/personalization/integrate_recommendation_service.md
> +- content types and attributes that are included in a response
```suggestion
- Content Types and attributes that are included in a response
```

2023-07-20 07:36 UTC, merged