Extend shipping example need region
ezsystems/developer-documentation pull request #2099
Opened 2023-08-07 12:46 UTC by adriendupuis

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | 
| Versions      | 
| Edition       | 

To create the custom shipping method from "Extend shipping" example, it is mandatory to select a region (see [IBX-6284](https://issues.ibexa.co/browse/IBX-6284) for not being notified about this), so the example should notice about that and link to the region creation doc.

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-09-08 10:17 UTC, MagdalenaZuba requested changes

2023-09-08 10:17 UTC, MagdalenaZuba commented on docs/commerce/shipping_management/extend_shipping.md
> +!!! notice
```suggestion
!!! note
```
we don't have notice :)

2023-09-08 10:17 UTC, MagdalenaZuba commented on docs/commerce/shipping_management/extend_shipping.md
> +    You must have regions to use this example. If you haven't, look at [Enable purchasing products](enable_purchasing_products.md) to create regions.
```suggestion
    To use this example, you must have regions. If you don't have them, refer to [Enable purchasing products](enable_purchasing_products.md) for instructions on how to add them..
```

2023-10-17 13:51 UTC, dabrt approved these changes

2023-10-18 05:52 UTC, MagdalenaZuba approved these changes

2023-10-18 07:18 UTC, merged