Reorder documentation
ezsystems/developer-documentation pull request #2126
Opened 2023-09-04 10:38 UTC by MagdalenaZuba

| Question      | Answer
| ------------- | ---
| JIRA Ticket   |https://issues.ibexa.co/browse/IBX-5860 and https://issues.ibexa.co/browse/IBX-5974
| Versions      | 4.6
| Edition       | Commerce

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-09-18 08:09 UTC, ViniTou commented on code_samples/api/commerce/src/Command/CartCommand.php
> +        // Get the target cart
This is not target cart, this is order with items that should be reordered

2023-09-18 08:09 UTC, ViniTou commented on code_samples/api/commerce/src/Command/CartCommand.php
> +        // Get the carts to merge
```suggestion
        // Get the cart to merge
```

2023-09-18 08:09 UTC, ViniTou commented on docs/commerce/checkout/reorder.md
> +The next example shows how to hide a step during checkout in reorder workflow.
Not sure that this should be documented here, as it is not related to reorder process, even more it is not used in current configuration.

2023-09-18 08:09 UTC, ViniTou commented on docs/commerce/checkout/reorder.md
> +You can use it to manage reorders in your project.
There is no managing when it comes to reorders, those are just normal orders and are by that you use OrderService to manipulate them. 
ReorderService just have some helpers method/facades over existing API to ease the process.

2023-09-19 10:23 UTC, ViniTou approved these changes

2023-09-19 10:23 UTC, ViniTou commented on code_samples/api/commerce/src/Command/CartCommand.php
> +        $reorderCart = $this->cartService->mergeCarts($reorderCart, true, $existingCart);
just FYI, this part is optional, it is perfectly valid to checkout with just the reorderCart without merging it with existing one.

2023-09-20 12:19 UTC, juskora requested changes

2023-09-20 12:19 UTC, juskora commented on docs/commerce/checkout/reorder.md
> +It uses historic data from previously ordered items even if they are no longer available.
```suggestion
It uses historical data from previously ordered items even if they are no longer available.
```

2023-09-20 12:19 UTC, juskora commented on docs/commerce/order_management/configure_order_management.md
> +You can define a status and transition in which the order can be cancelled
```suggestion
You can define a status and transition in which the order can be canceled 
```

2023-09-20 12:19 UTC, juskora commented on docs/commerce/storefront/storefront.md
> +|Cancel order|Allows logged in users to cancel their orders in a pending status.|
```suggestion
|Cancel order|Allows logged-in users to cancel their orders in a pending status.|
```

2023-09-20 12:19 UTC, juskora commented on docs/commerce/storefront/storefront.md
> +| Reorder |Allows logged in users to repurchase previously bought items. |
```suggestion
| Reorder |Allows logged-in users to repurchase previously bought items. |
```

2023-09-20 12:19 UTC, juskora commented on docs/commerce/storefront/storefront.md
> +|Searching and filtering of orders| Allows logged in users to search and filter their past orders on the orders page.|
```suggestion
|Searching and filtering of orders| Allows logged-in users to search and filter their past orders on the orders page.|
```

2023-09-20 13:26 UTC, juskora approved these changes

2023-09-21 10:39 UTC, radzyu approved these changes
Great work @MagdalenaZuba, thank you!

2023-09-21 11:18 UTC, merged