Changelog August 2023
ezsystems/developer-documentation pull request #2129
Opened 2023-09-05 09:52 UTC by MagdalenaZuba

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | N/A
| Versions      | 3.3+
| Edition       | N/A

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-09-05 11:18 UTC, juskora requested changes

2023-09-05 11:18 UTC, juskora commented on docs/resources/new_in_doc.md
> +    - [Filter payment methods](https://doc.ibexa.co/projects/userguide/en/master/commerce/payment/work_with_payment_methods/#edit-existing-payment-method)
```suggestion
    - [Filter payment methods](https://doc.ibexa.co/projects/userguide/en/master/commerce/payment/work_with_payment_methods/#filter-payment-methods)
```

2023-09-05 13:33 UTC, adamwojs approved these changes

2023-09-06 07:39 UTC, juskora approved these changes

2023-09-06 08:32 UTC, merged