Minor REST API improvements
ezsystems/developer-documentation pull request #2131
Opened 2023-09-06 09:45 UTC by MagdalenaZuba

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | Slack request
| Versions      | 4.5+
| Edition       | N/A

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-09-06 11:22 UTC, juskora approved these changes

2023-09-06 11:46 UTC, adriendupuis commented on docs/api/rest_api/rest_api_reference/input/examples/product/catalog/product/POST/ProductCreate.json.example
>              }
Fix indent:
```suggestion
            "attr1": "fffffff"
        }
```

2023-09-06 11:48 UTC, adriendupuis commented on docs/api/rest_api/rest_api_reference/input/ez-orders.raml
> +                displayName: Load order by ID
It doesn't make much sense that `/orders/order/cancel/{id}` loads an order.

2023-09-06 11:53 UTC, adriendupuis commented on docs/api/rest_api/rest_api_reference/input/ez-orders.raml
> +                displayName: Load order by ID
[`/orders/order/{id}`](https://github.com/ibexa/order-management/blob/main/src/bundle/Resources/config/routing_rest.yaml#L9) should be kept.

[`/orders/order/cancel/{id}`](https://github.com/ibexa/order-management/blob/main/src/bundle/Resources/config/routing_rest.yaml#L39) is a whole new route.

2023-09-06 11:59 UTC, adriendupuis commented on docs/api/rest_api/rest_api_reference/input/ez-orders.raml
> +                displayName: Load order by ID
It should looks like
```yaml
displayName: Orders

/orders:
    post:
        …
    get:
        …
/order:
    /{identifier}:
        get:
            …

    /{id}:
        get:
            …
        patch:
            …
        post:
            …
    /cancel/{id}:
        post:
            displayName: Cancel order
            …
```

2023-09-06 12:01 UTC, adriendupuis commented on docs/api/rest_api/rest_api_reference/input/ez-orders.raml
> +                displayName: Load order by ID
In fact, it's just the insertion of `    /cancel/{id}:` at line 133

2023-09-06 12:02 UTC, adriendupuis requested changes
The insertion of `    /cancel/{id}` at line 133 without any indentation change should keep every existing routes and just fix the `Cancel order` one.

2023-09-07 07:08 UTC, adriendupuis approved these changes
Everything looks good
* https://ez-systems-developer-documentation--2131.com.readthedocs.build/en/2131/api/rest_api/rest_api_reference/rest_api_reference.html#product-catalog-create-product
* https://ez-systems-developer-documentation--2131.com.readthedocs.build/en/2131/api/rest_api/rest_api_reference/rest_api_reference.html#orders-cancel-order

2023-09-07 07:25 UTC, merged