IBX-6500: Page Builder product guide added in developer documentation
ezsystems/developer-documentation pull request #2171
Opened 2023-10-12 09:52 UTC by julitafalcondusza

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | (https://issues.ibexa.co/browse/IBX-6500)
| Versions      | master

Page Builder product guide added in developer documentation.

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-10-31 10:43 UTC, adriendupuis commented on docs/content_management/pages/page_builder_guide.md
> +Page Builder comes with a Scheduler - is a tool that allows you to schedule content publication.
This one verb "is" sounds weird here as not in a definition list.
I would also avoid "publication" that could mislead to a confusion with "publish" concept.
```suggestion
Page Builder comes with a Scheduler - a tool that allows you to schedule content appearance.
```

2023-10-31 10:55 UTC, MagdalenaZuba requested changes

2023-10-31 10:55 UTC, MagdalenaZuba commented on docs/content_management/pages/page_builder_guide.md
> +3\. On the right-side toolbar, click **Create content** and from the list of Content items select Landing Page.
```suggestion
3\. On the right-side toolbar, click **Create content** and from the list of Content items select **Landing Page**.
```

2023-10-31 10:55 UTC, MagdalenaZuba commented on docs/content_management/pages/page_builder_guide.md
> +You can also add a new page in the Page Builder. Check 'Create page in Page Builder' section below.
```suggestion
You can also add a new page in the Page Builder. Check [Create page in Page Builder](#create-page-in-page-builder) section below.
```

2023-10-31 10:55 UTC, MagdalenaZuba commented on docs/content_management/pages/page_builder_guide.md
> +*To help you preserve your work, system saves drafts of Content items automatically. For more information, see [Autosave](https://doc.ibexa.co/projects/userguide/en/master/content_management/content_
```suggestion
*To help you preserve your work, system saves drafts of Content items automatically. For more information, see [Autosave]([[= user_doc =]]/content_management/content_versions/#autosave).
```

2023-10-31 10:55 UTC, MagdalenaZuba commented on docs/content_management/pages/page_builder_guide.md
> +- Structure view - shows a structure of the page, including its division into zones and the blocks that it contains. It follows the behavior of the content tree. Structure view has ability to reorder
```suggestion
- Structure view - shows a structure of the page, including its division into zones and the blocks that it contains. It follows the behavior of the Content Tree. Structure view has the ability to reorder blocks using drag and drop.
```

2023-10-31 10:55 UTC, MagdalenaZuba commented on docs/content_management/pages/page_builder_guide.md
> +On the Page Builder toolbar click the plus button and from the list select Landing Page.
```suggestion
On the Page Builder toolbar click the plus button and from the list select **Landing Page**.
```

2023-10-31 10:55 UTC, MagdalenaZuba commented on docs/content_management/pages/page_builder_guide.md
> +For newly created Page you can choose a [layout](https://doc.ibexa.co/projects/userguide/en/latest/content_management/configure_ct_field_settings/#available-page-layouts) which defines the available
```suggestion
For newly created Page you can choose a [layout]([[= user_doc =]]/content_management/configure_ct_field_settings/#available-page-layouts) which defines the available zones.
```

2023-10-31 10:55 UTC, MagdalenaZuba commented on docs/content_management/pages/page_builder_guide.md
> +For more information, see [Configure layout](https://doc.ibexa.co/en/latest/templating/render_content/render_page/#configure-layout).
```suggestion
For more information, see [Configure layout](render_page.md#configure-layout).
```

2023-10-31 10:55 UTC, MagdalenaZuba commented on docs/content_management/pages/page_builder_guide.md
> +You can check all ready-to-use blocks available in Page Builder in User Documentation, [Block reference page](https://doc.ibexa.co/projects/userguide/en/latest/content_management/block_reference/).
```suggestion
You can check all ready-to-use blocks available in Page Builder in User Documentation, [Block reference page]([[= user_doc =]]/content_management/block_reference/).
```

2023-10-31 10:55 UTC, MagdalenaZuba commented on docs/content_management/pages/page_builder_guide.md
> +Working with blocks is intuitive. You don't have to worry about placing blocks in the proper place from the start - you can reorder the at any time.
```suggestion
Working with blocks is intuitive. You don't have to worry about placing blocks in the proper place from the start - you can reorder them at any time.
```

2023-10-31 10:55 UTC, MagdalenaZuba commented on docs/content_management/pages/page_builder_guide.md
> +- Duplicate - duplicates existing block by creating its copy
blank copy or with settings?

2023-10-31 10:55 UTC, MagdalenaZuba commented on docs/content_management/pages/page_builder_guide.md
> +Page Builder comes with a Scheduler - is a tool that allows you to schedule content publication.
```suggestion
Page Builder comes with a Scheduler, it allows you to schedule content publication.
```

2023-10-31 10:55 UTC, MagdalenaZuba commented on docs/content_management/pages/page_builder_guide.md
> +For more information, see [Schedule publication](https://doc.ibexa.co/projects/userguide/en/latest/content_management/schedule_publishing/).
```suggestion
For more information, see [Schedule publication]([[= user_doc =]]/content_management/schedule_publishing/).
```

2023-10-31 10:55 UTC, MagdalenaZuba commented on docs/content_management/pages/page_builder_guide.md
> +One of the most important tool that Page Builder offers, is a Scheduler. It allows you to set and schedule specific date and time, when content has to be published. In result, you can plan timeline o
```suggestion
One of the most important tool that Page Builder offers, is a Scheduler. It allows you to set and schedule specific date and time, when content has to be published or hidden. In result, you can manage timeline of publications, without the need of manual publishing or hiding each of them.
```

2023-10-31 10:55 UTC, MagdalenaZuba commented on docs/content_management/pages/page_builder_guide.md
> +Anytime you can edit your page and change the position of specific block to make it more visible. What's more, Page Builder offers you ready-to-use page blocks that can help to create content tailore
```suggestion
Anytime you can edit your page and change the position of specific block to enhance visibility. Additionaly, Page Builder offers you a selection of ready-to-use page blocks that can help you to create content tailored to each individual customer:
```

2023-10-31 11:25 UTC, juskora requested changes

2023-10-31 11:25 UTC, juskora commented on docs/content_management/pages/page_builder_guide.md
> +Then, from the Content Tree choose the page that you want to edit and click **Edit**.
```suggestion
Then, from the Content Tree choose the page and click **Edit**.
```

2023-10-31 11:25 UTC, juskora commented on docs/content_management/pages/page_builder_guide.md
> +When you add a new block to the drop zone, before you drop it, a blue line appears  - it helps you see the position of the newly added block in relation to other, already added blocks.
Or maybe: drop it in the blue highlighted area? Instead of blue lines.

2023-10-31 12:11 UTC, dabrt reviewed
Please see my comments

2023-10-31 12:11 UTC, dabrt commented on docs/content_management/pages/page_builder_guide.md
> +Drag-and-drop elements toolbar, separated page zones and transparent sections - these are the elements that make working with Page Builder really intuitive and quick.
```suggestion
Drag-and-drop elements toolbar, separated page zones and transparent sections - these are the elements that make working with Page Builder really intuitive and quick.
```
Drag-and-drop elements toolbar - sounds a lot like a command. Maybe just "The **Elements** toolbar"
"separated" - as in "well defined" or "visible"?
"transparent sections" - in what sense? What do you mean by a section here?

2023-10-31 12:11 UTC, dabrt commented on docs/content_management/pages/page_builder_guide.md
> +One of the most important tool that Page Builder offers, is a Scheduler. It allows you to set and schedule specific date and time, when content has to be published. In result, you can plan timeline o
```suggestion
One of the most important tools that Page Builder offers, is a Scheduler. It allows you to set and schedule a specific date and time for the content to be published. As a result, you can create a timeline of your new publications, without having to publish each of them manually.
```

2023-10-31 12:11 UTC, dabrt commented on docs/content_management/pages/page_builder_guide.md
> +Page Builder allows you to create highly customizable websites. You can build modifiable and targeted landing pages, that meet your needs.
```suggestion
Page Builder allows you to create highly customizable websites. You can build modifiable and targeted landing pages that meet your needs.
```

2023-10-31 12:11 UTC, dabrt commented on docs/content_management/pages/page_builder_guide.md
> +Additionaly, if you feel comfortable with your technical skills, you can configure your own elements, for example, new customized layout, or block.
```suggestion
Additionaly, if you feel comfortable with your technical skills, you can configure your own elements, for example, a new customized layout, or block.
```

2023-10-31 12:11 UTC, dabrt commented on docs/content_management/pages/page_builder_guide.md
> +Personalized campaigns are one of the factors that can increase your sales. With Page Builder you can achieve it, by using customization and time Scheduler.
```suggestion
Personalized campaigns are one of the factors that can increase your sales. 
With Page Builder, you can achieve it by using customization and time Scheduler.
```

2023-10-31 12:11 UTC, dabrt commented on docs/content_management/pages/page_builder_guide.md
> +Anytime you can edit your page and change the position of specific block to make it more visible. What's more, Page Builder offers you ready-to-use page blocks that can help to create content tailore
```suggestion
Anytime you can edit your page and change a position of a block to make it more visible. 
What's more, Page Builder offers you ready-to-use page blocks that can help create content tailored to each individual customer:
```

2023-10-31 12:11 UTC, dabrt commented on docs/content_management/pages/page_builder_guide.md
> +- Targeting - embeds an Content item based on the Segment the user belongs to.
```suggestion
- Targeting - embeds a Content item based on the Segment the user belongs to.
```

2023-10-31 12:29 UTC, adriendupuis commented on docs/content_management/pages/page_builder_guide.md
> +You can schedule to be published, or hidden in Page Builder in two ways with:
Content are already "published" from a Repository point of view. They just appear then disappear from the block.
```suggestion
You can schedule content to be revealed, or hidden in Page Builder in two ways with:
```

2023-11-02 09:49 UTC, julitafalcondusza commented on docs/content_management/pages/page_builder_guide.md
> +1\. In the upper toolbar click **Content**.
1\. - fixed. 
My idea was: Page -> Page Builder. It makes sense to me.

2023-11-02 09:54 UTC, julitafalcondusza commented on docs/content_management/pages/page_builder_guide.md
> +It is also important to choose a layout - it determines the arrangement of drop zones that contain content elements.
It's just general description. Page Builder is mostly about adding blocks, that's why I described it in the beginning of this section. 
Looking at detailed sections, the order is correct - "Choose layout", then "Add blocks" and "Work with blocks".

2023-11-02 09:55 UTC, julitafalcondusza commented on docs/content_management/pages/page_builder_guide.md
> +For newly created Page you can choose a [layout](https://doc.ibexa.co/projects/userguide/en/latest/content_management/configure_ct_field_settings/#available-page-layouts) which defines the available
I'd rather keep current link.

2023-11-02 10:05 UTC, julitafalcondusza commented on docs/content_management/pages/page_builder_guide.md
> +To open the Page Builder, click **Site** and select a website from the list that appears next to the List icon.
Tested again, I deleted all the section as it's not clear.

2023-11-02 10:19 UTC, julitafalcondusza commented on docs/content_management/pages/page_builder_guide.md
> +- Duplicate - duplicates existing block by creating its copy
With settings :) info added

2023-11-02 10:24 UTC, julitafalcondusza commented on docs/content_management/img/create_page.png
Good point! Updated

2023-11-02 10:55 UTC, MagdalenaZuba approved these changes

2023-11-02 12:10 UTC, juskora approved these changes

2023-11-03 08:12 UTC, adriendupuis approved these changes

2023-11-03 08:21 UTC, merged