User product guide
ezsystems/developer-documentation pull request #2179
Opened 2023-10-17 09:20 UTC by MagdalenaZuba

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-6498
| Versions      | master
| Edition       | n/a

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-10-17 11:49 UTC, juskora requested changes

2023-10-17 11:49 UTC, juskora commented on docs/users/user_management_guide.md
> +- [OAuth](oauth_authentication.md) - integrating OAuth authentication allows users to log in using their existing social media or third-party credentials, streamlining the registration process.
I would rewrite it a little bit as it sounds like repetition from line: 82.

2023-10-17 11:49 UTC, juskora commented on docs/users/user_management_guide.md
> +Track user behavior, such as page views, search queries, and interactions, to create Segments and Segment Groups for users who share similar actions.
```suggestion
Track user behavior, such as page views, search queries, and interactions, to create Segments and Segment Groups for users who share similar behaviors.
```

2023-10-17 11:49 UTC, juskora commented on docs/users/user_management_guide.md
> +Set specific permissions for customer groups to control who can access and edit certain content ot get specific recommendations.
```suggestion
Set specific permissions for customer groups to control who can access and edit certain content to get respective recommendations.
```

2023-10-17 11:49 UTC, juskora commented on docs/users/user_management_guide.md
> +- targeted marketing campaigns - Segment users by demographics or behavior and deliver targeted marketing campaigns that resonate with specific groups.
Rewrite as it resembles lines: 108.

2023-10-17 11:49 UTC, juskora commented on docs/users/user_management_guide.md
> +- customer groups - organize users into customer groups, which helps in delivering tailored experiences and content to specific segments.
How about to begin with capital letter?

2023-10-17 11:49 UTC, juskora commented on docs/users/user_management_guide.md
> +- Preferences - Utilize user preferences to offer a customized experience, from language preferences to Content Type preferences.
Begin with capital letter, after hyphen, lower case.

2023-10-17 11:49 UTC, juskora commented on docs/users/user_management_guide.md
> +- targeted marketing campaigns - Segment users by demographics or behavior and deliver targeted marketing campaigns that resonate with specific groups.
Capital letter -> - -> lower case.

2023-10-17 12:30 UTC, juskora approved these changes

2023-10-18 11:07 UTC, julitafalcondusza commented on docs/users/user_management_guide.md
> +**Permission:**
Just an option to consider - list is more clear (in my opinion), and additionally, in the current form, when each sentence begins with "A" letter ('A Permission...', 'A Role...'), I see it as a letter numbered list.

Option:

- **Permission** - defines a specific action or access level that can be granted or denied within the system.

- **Role** - represents a collection of Permissions that can be assigned to users or user groups.
Roles streamline permission management by grouping related Permissions together.

- **Policy** - is a set of rules or conditions that determine under what circumstances a specific permission is granted or denied by applying Limitations.
Policies allow for fine-grained control of access based on various factors, such as user attributes or system states.

2023-10-18 11:08 UTC, julitafalcondusza approved these changes

2023-10-18 12:44 UTC, merged

2023-10-18 14:46 UTC, dabrt commented on docs/users/user_management_guide.md
> +![User's section](users_section.png)
```suggestion
![Users section](users_section.png "Users section")
```

2023-10-18 14:46 UTC, dabrt commented on docs/users/user_management_guide.md
> +- Invitations - invite users to join a platform streamlining an onboarding process, sending invitations for exclusive content or events.
```suggestion
- Invitations - invite users to join a platform, to streamline an onboarding process, or send exclusive content or event invitations.
```

2023-10-18 14:46 UTC, dabrt commented on docs/users/user_management_guide.md
> +[Tailor user access control](custom_policies.md) to your unique requirements using custom policies. Define complex rules and access criteria for different users or groups.
```suggestion
[Tailor user access control](custom_policies.md) to your unique requirements by creating custom policies. Define complex rules and access criteria for different users or groups.
```