IBX-5874: Allow to attach context data to Cart and Cart Entries
ezsystems/developer-documentation pull request #2186
Opened 2023-10-24 11:37 UTC by MagdalenaZuba

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | [IBX-5874](https://issues.ibexa.co/browse/IBX-5874)
| Versions      | 4.6
| Edition       | Commerce

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-10-26 07:16 UTC, adamwojs commented on docs/commerce/cart/extend_cart.md
> +# Extend cart
This doc should be part of the https://doc.ibexa.co/en/latest/commerce/cart/cart_api/ 😉

2023-10-28 09:08 UTC, adamwojs approved these changes

2023-10-30 08:12 UTC, julitafalcondusza approved these changes

2023-10-30 12:20 UTC, juskora requested changes

2023-10-30 12:20 UTC, juskora commented on docs/commerce/cart/cart_api.md
> +In this case, you've attached a "tshirt_text" attributed to the cart entry, which might represent custom text for a T-shirt.
```suggestion
In this case, you've attached a "tshirt_text" attribute to the cart entry, which might represent custom text for a T-shirt.
```

2023-10-30 12:49 UTC, juskora approved these changes

2023-10-31 07:47 UTC, merged