IBX-6626 Simplify user actions
ezsystems/developer-documentation pull request #2189
Opened 2023-10-26 10:00 UTC by dabrt

| Question      | Answer |
| ------------- | --- |
| JIRA Ticket   | IBX-6626 |
| Versions      | 4.6 |
| Edition       | all |

Make changes to text and illustrations to account for changed actions in the Back Office.

#### Checklist

- [x] Text renders correctly
- [x] Added link to this PR in relevant JIRA ticket or code PR

2023-10-28 09:08 UTC, adamwojs approved these changes

2023-11-06 10:28 UTC, tischsoic approved these changes

2023-11-06 13:34 UTC, julitafalcondusza approved these changes

2023-11-07 08:40 UTC, juskora requested changes

2023-11-07 08:40 UTC, juskora commented on docs/administration/back_office/back_office_menus/back_office_menus.md
> +For example, the following code changes the default icon for the "Create content" button in content view:
```suggestion
For example, the following code changes the default icon for the **Create content** button in content view:
```

2023-11-07 08:40 UTC, juskora commented on docs/administration/back_office/back_office_elements/reusable_components.md
> +- `show_close_btn` - by default set to `false`, if set to `true`, the "Close" button is displayed but requires additional JavaScript configuration on your side to work
```suggestion
- `show_close_btn` - by default set to `false`, if set to `true`, the **Close** button is displayed but requires additional JavaScript configuration on your side to work
```

2023-11-07 08:40 UTC, juskora commented on docs/tutorials/beginner_tutorial/2_create_the_content_model.md
> +Confirm the creation of the Content Type by selecting **Save and close**.
```suggestion
Confirm the creation of the Content Type by clicking **Save and close**.
```

2023-11-07 09:08 UTC, juskora approved these changes

2023-11-07 09:50 UTC, merged