IBX-5944: Expose shipping cost in REST order's value summary
ezsystems/developer-documentation pull request #2192
Opened 2023-10-27 10:45 UTC by MagdalenaZuba

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | [IBX-5944](https://issues.ibexa.co/browse/IBX-5944)
| Versions      | 4.6
| Edition       | N/A

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-10-27 12:49 UTC, konradoboza requested changes

2023-10-27 12:49 UTC, konradoboza commented on docs/api/rest_api/rest_api_reference/input/examples/orders/GET/Order.json.example
> +}
```suggestion
}

```

2023-10-27 12:49 UTC, konradoboza commented on docs/api/rest_api/rest_api_reference/input/ez-types.raml
> +            type: Currency
`shipping_cost_incl_vat` is part of the `context`.
```suggestion
```

2023-10-27 12:55 UTC, konradoboza approved these changes

2023-10-28 09:07 UTC, adamwojs approved these changes

2023-10-31 07:47 UTC, merged