Code update for Create custom Aggregation
ezsystems/developer-documentation pull request #2218
Opened 2023-11-08 08:37 UTC by MagdalenaZuba

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | N/A
| Versions      | 4.5+
| Edition       | N/A

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-11-08 09:07 UTC, papcio122 approved these changes

2023-11-09 05:44 UTC, adamwojs reviewed
@MagdalenaZuba Have you tried the steps provided on the edited documentation page on your machine?

2023-11-09 06:58 UTC, MagdalenaZuba commented
@adamwojs no, as I don't have Solr configured. That's why I asked the reporting developer to confirm whether the steps work.

2023-11-09 08:00 UTC, adamwojs commented
Then please install Solr and Elasticsearch on your local environment, follow the steps from the article and paste the results (as a comment to this PR) of the example aggregation 

```php
use App\Query\Aggregation\PriorityRangeAggregation;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Aggregation\Range;
// ...
$aggregation = new PriorityRangeAggregation('example', [
    Range::ofInt(0, 100),
]);
``` 

attached to both Content & Location query on clean `ibexa/commerce` data. If you stump upon any issue I'm here to help.

2023-11-09 14:30 UTC, adriendupuis commented
> attached to both Content & Location query on clean `ibexa/commerce` data. If you stump upon any issue I'm here to help.
@adamwojs On 4.5.3, the actual example is working only with Location as `priority_id` field is dedicated to Locations. Content items use `main_location_priority_i`.

2023-11-10 06:27 UTC, adamwojs commented
> @adamwojs On 4.5.3, the actual example is working only with Location as priority_id field is dedicated to Locations. Content items use main_location_priority_i.

Point for you @papcio122. @MagdalenaZuba Could you please adapt the article?

2023-11-15 17:09 UTC, papcio122 requested changes

2023-11-15 17:09 UTC, papcio122 commented on docs/search/extensibility/create_custom_aggregation.md
> +    App\Query\Aggregation\Solr\PriorityRangeAggregationVisitor:
I would change it to be consistent with elasticsearch tab
```suggestion
    app.search.solr.query.aggregation_visitor.priority_range_aggregation:
```

2023-11-15 17:09 UTC, papcio122 commented on docs/search/extensibility/create_custom_aggregation.md
>      App\Query\Aggregation\Solr\PriorityAggregationResultExtractor:
I would change it to be consistent with elasticsearch tab
```suggestion
    app.search.solr.query.aggregation_result_extractor.priority_range_aggregation:
```

2023-11-15 17:09 UTC, papcio122 commented on docs/search/extensibility/create_custom_aggregation.md
>              $aggregationClass: 'App\Query\Aggregation\PriorityRangeAggregation'
The service is missing an argument
```suggestion
            $aggregationClass: 'App\Query\Aggregation\PriorityRangeAggregation'
            $keyMapper: 'Ibexa\Solr\ResultExtractor\AggregationResultExtractor\RangeAggregationKeyMapper\IntRangeAggregationKeyMapper'
```

2023-11-16 08:23 UTC, papcio122 requested changes

2023-11-16 08:23 UTC, papcio122 commented on docs/search/extensibility/create_custom_aggregation.md
>              $aggregationClass: 'App\Query\Aggregation\PriorityRangeAggregation'
I tested again, but I am still getting some errors, sorry I missed this yesterday
```suggestion
            $aggregationClass: 'App\Query\Aggregation\Solr\PriorityRangeAggregation'
```

2023-11-16 08:23 UTC, papcio122 commented on docs/search/extensibility/create_custom_aggregation.md
>              $aggregationClass: 'App\Query\Aggregation\PriorityRangeAggregation'
I tested again, but I am still getting some errors, sorry I missed this yesterday, with these two changes everything works :)
```suggestion
            $aggregationClass: 'App\Query\Aggregation\Solr\PriorityRangeAggregation'
```

2023-11-16 08:31 UTC, papcio122 approved these changes

2023-11-16 12:09 UTC, merged