Added image search criteria
ezsystems/developer-documentation pull request #2225
Opened 2023-11-21 10:09 UTC by juskora

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-6620
| Versions      | master, 4.6
| Edition       | 

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-12-01 08:00 UTC, adamwojs commented on docs/search/criteria_reference/imagefilesize_criterion.md
> +- `max_size` - maximum file size expressed in MB
This list is incomplete

2023-12-01 08:01 UTC, adamwojs commented on docs/search/criteria_reference/imageorientation_criterion.md
> +- `orientation` - string or array. Allowed orientation types: `portrait`, `landscape`, `square`.
This list is incomplete

2023-12-01 08:01 UTC, adamwojs commented on docs/search/criteria_reference/imageorientation_criterion.md
> +$query = new MimeType(string $fieldDefIdentifier, $type);
Yet another invalid PHP code example

2023-12-01 08:01 UTC, adamwojs commented on docs/search/criteria_reference/imagewidth_criterion.md
> +$query = new Width(string $fieldDefIdentifier, int $minValue = 0, ?int $maxValue = null);
Same as above

2024-03-26 11:17 UTC, ciastektk requested changes

2024-03-26 11:17 UTC, ciastektk commented on docs/search/criteria_reference/image_criterion.md
> +The `MimeType` Search Criterion searches for image by specified image attributes.
```suggestion
The `Image` Search Criterion searches for image by specified image attributes.
```

2024-03-26 11:17 UTC, ciastektk commented on docs/search/criteria_reference/imagefilesize_criterion.md
> +    ```
Bad indentation

2024-03-26 11:17 UTC, ciastektk commented on docs/search/criteria_reference/imageorientation_criterion.md
> +The `Orientation` Search Criterion searches for image with specified mime orientation(s).
```suggestion
The `Orientation` Search Criterion searches for image with specified orientation(s).
```

2024-03-26 11:17 UTC, ciastektk commented on docs/search/criteria_reference/imageorientation_criterion.md
> +       }
```suggestion
            "ImageOrientationCriterion": {
                "fieldDefIdentifier": "image",
                "orientation": "landscape"
            }
        }
```

2024-03-26 11:17 UTC, ciastektk commented on docs/search/criteria_reference/search_criteria_reference.md
> +|[ImageWidth](imagewidth_criterion.md)|Image widht in pixels|||
Missing reference to Image criterion.

Each image criterion supports Content and Location search.

2024-03-26 11:17 UTC, ciastektk commented on docs/search/criteria_reference/imagedimensions_criterion.md
> +    </Query>
Bad indentation.

https://ez-systems-developer-documentation--2225.com.readthedocs.build/en/2225/search/criteria_reference/imagedimensions_criterion/

vs

https://ez-systems-developer-documentation--2225.com.readthedocs.build/en/2225/search/criteria_reference/imagefilesize_criterion/

2024-03-26 13:56 UTC, julitafalcondusza approved these changes

2024-03-26 14:12 UTC, dabrt approved these changes

2024-03-26 14:12 UTC, dabrt commented on docs/search/criteria_reference/search_criteria_reference.md
> +|[ImageWidth](imagewidth_criterion.md)|Image widht in pixels|&#10004;|&#10004;||
```suggestion
|[ImageWidth](imagewidth_criterion.md)|Image width in pixels|&#10004;|&#10004;||
```

2024-03-26 14:12 UTC, dabrt commented on docs/search/criteria_reference/search_criteria_reference.md
> +|[FullText](fulltext_criterion.md)|Full text content of a Content item's Fields|&#10004; |&#10004; | |
```suggestion
|[FullText](fulltext_criterion.md)|Full text content of a content item's Fields|&#10004; |&#10004; | |
```

2024-03-26 14:12 UTC, dabrt commented on docs/search/criteria_reference/image_criterion.md
> +
```suggestion
```

2024-03-26 14:12 UTC, dabrt commented on docs/search/criteria_reference/imagedimensions_criterion.md
> +
```suggestion
```

2024-03-26 14:12 UTC, dabrt commented on docs/search/criteria_reference/imagedimensions_criterion.md
> +
```suggestion
    ```

2024-03-26 14:12 UTC, dabrt commented on docs/search/criteria_reference/imagedimensions_criterion.md
> +
```suggestion
```

2024-03-26 14:12 UTC, dabrt commented on docs/search/criteria_reference/imagefilesize_criterion.md
> +
```suggestion
```

2024-03-26 14:12 UTC, dabrt commented on docs/search/criteria_reference/imagemimetype_criterion.md
> +
```suggestion
```

2024-03-26 14:12 UTC, dabrt commented on docs/search/criteria_reference/imageorientation_criterion.md
> +
```suggestion
```

2024-03-27 11:04 UTC, ciastektk approved these changes

2024-03-27 11:42 UTC, merged