Specify SiteAccess for translations data migrations
ezsystems/developer-documentation pull request #2247
Opened 2023-12-13 15:30 UTC by adriendupuis

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | [CS-11606](https://jsd.ez.no/browse/CS-11606)<small>/[support 11606](https://support.ibexa.co/ticket/view/11606)</small>
| Versions      | 4.6, 4.5, 3.3
| Edition       | All

Recommends `--siteaccess` option with a BO SiteAccess when using multiple languages to avoid loosing translations at export or import time.

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-12-13 19:58 UTC, adamwojs approved these changes

2023-12-13 19:59 UTC, adamwojs commented
> I found nothing in doc about configuring languages on admin SiteAccess or admin_group.
There might be something to add about this in another PR.

It works exactly the same as in case of other frontend accesses :wink:

2023-12-14 08:39 UTC, reithor approved these changes

2023-12-19 08:40 UTC, MagdalenaZuba requested changes

2023-12-19 08:40 UTC, MagdalenaZuba commented on docs/content_management/data_migration/exporting_data.md
> +    It is recommended to use the SiteAccess of the Back Office of the targeted repository.
```suggestion
    The `--siteaccess` option usage can be relevant for a multi-language repository.
    You must export with a SiteAccess that supports all languages, or the migration skips translations in non-supported languages. 
    It is recommended to use the SiteAccess from the Back Office of the targeted repository.
```

2023-12-19 08:40 UTC, MagdalenaZuba commented on docs/content_management/data_migration/importing_data.md
> +It's recommended to use the SiteAccess of the Back Office of the targeted repository.
```suggestion
You must import with a SiteAccess that supports all languages, or the migration skips translations in non-supported languages.
It's recommended to use the SiteAccess from the Back Office of the targeted repository.
```

2023-12-19 08:40 UTC, MagdalenaZuba commented on docs/content_management/data_migration/importing_data.md
> +Notice the `--siteaccess` option usage.
What should user notice about it, is there something specific they should look for?

2023-12-22 12:24 UTC, julitafalcondusza approved these changes

2023-12-22 12:43 UTC, adriendupuis commented on docs/content_management/data_migration/importing_data.md
> +This can be important, especially when several languages are used.
```suggestion
Notice that `--siteaccess` option usage can be important, especially when several languages are used.
```

2024-01-04 09:21 UTC, adriendupuis commented on docs/content_management/data_migration/exporting_data.md
> +    You must export with a SiteAccess that supports all languages, or the migration skips translations in non-supported languages.
```suggestion
    You must export with a SiteAccess that supports all languages, or the migration skips translations in non-supported languages.
```

2024-01-04 09:42 UTC, merged