User management
ezsystems/developer-documentation pull request #2250
Opened 2023-12-18 10:59 UTC by MagdalenaZuba

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | https://issues.ibexa.co/browse/IBX-6744
| Versions      | master
| Edition       | all

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-12-19 08:41 UTC, julitafalcondusza approved these changes

2023-12-19 10:07 UTC, juskora requested changes

2023-12-19 10:23 UTC, dabrt approved these changes
Consider linking from “Invitation and registration form templates” section to "Registration" article and its “Other templates” section and vice versa, or moving both these sections to “User management templates”.

2023-12-20 07:59 UTC, MagdalenaZuba commented on docs/update_and_migration/from_3.3/update_from_3.3.md
> +you should [revoke passwords](https://doc.ibexa.co/en/latest/users/passwords/#revoking-passwords) for all affected users.
The link doesn't work because it is a full link to the page in this PR, PR needs to be merged to the main doc for the link to work.

2023-12-20 08:06 UTC, juskora approved these changes

2023-12-22 09:28 UTC, merged