IBX-6702: BasePriceStatsAggregation and CustomPriceStatsAggregation described
ezsystems/developer-documentation pull request #2252
Opened 2023-12-18 12:30 UTC by julitafalcondusza

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | (https://github.com/ibexa/product-catalog/pull/1075)
| Versions      | master
| Edition       | Content/Headless, Experience, Commerce

BasePriceStatsAggregation and CustomPriceStatsAggregation described in Developer Documentation.

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2023-12-23 14:49 UTC, adamwojs requested changes

2023-12-23 14:49 UTC, adamwojs commented on docs/search/aggregation_reference/basepricestats_aggregation.md
> +- `currencyCode` - currency code of the price
`BasePriceStatsAggregation` expects `\Ibexa\Contracts\ProductCatalog\Values\CurrencyInterface` instance as second. arg

2023-12-23 14:49 UTC, adamwojs commented on docs/search/aggregation_reference/custompricestats_aggregation.md
> +- `currencyCode` - currency code of the price
`Ibexa\Contracts\ProductCatalog\Values\Product\Query\Aggregation\CustomPriceStatsAggregation` expects \Ibexa\Contracts\ProductCatalog\Values\CurrencyInterface instance as second. arg

2023-12-23 14:49 UTC, adamwojs commented on docs/search/aggregation_reference/custompricestats_aggregation.md
> +- `customerGroup` - customer group that defines custom pricing
Please add information about default value (customer group assigned to current user)

2024-01-04 09:17 UTC, adamwojs approved these changes

2024-01-04 09:17 UTC, adamwojs commented on docs/search/aggregation_reference/custompricestats_aggregation.md
> +- `customerGroup` - customer group that defines custom pricing, by default it is the one assigned to current user
```suggestion
- `\Ibexa\Contracts\ProductCatalog\Values\CustomerGroupInterface|null` - customer group that defines custom pricing, by default it is the one assigned to current user
```

2024-01-04 09:30 UTC, adriendupuis commented on docs/search/aggregation_reference/custompricestats_aggregation.md
> +- `\Ibexa\Contracts\ProductCatalog\Values\CustomerGroupInterface|null` - customer group that defines custom pricing, by default it is the one assigned to current user
```suggestion
- `name` (`string`) - name of the Aggregation
- `currency` (`\Ibexa\Contracts\ProductCatalog\Values\CurrencyInterface`) - currency of the price
- `customerGroup` (`\Ibexa\Contracts\ProductCatalog\Values\CustomerGroupInterface` or `null`) - customer group that defines custom pricing, by default it is the one assigned to current user
```

2024-01-04 09:31 UTC, adriendupuis commented on docs/search/aggregation_reference/basepricestats_aggregation.md
> +- `\Ibexa\Contracts\ProductCatalog\Values\CurrencyInterface` - currency of the price
```suggestion
- `name` (`string`) - name of the Aggregation
- `currency` (`\Ibexa\Contracts\ProductCatalog\Values\CurrencyInterface`) - currency of the price
```

2024-01-04 09:32 UTC, adriendupuis commented on docs/search/aggregation_reference/custompricestats_aggregation.md
> +- `\Ibexa\Contracts\ProductCatalog\Values\CustomerGroupInterface|null` - customer group that defines custom pricing, by default it is the one assigned to current user
@adamwojs What do you think of those changes to not mix arguments names and arguments types?

2024-01-05 11:04 UTC, juskora approved these changes

2024-01-08 08:29 UTC, merged