Mention the Composer repository change in 3.3 update/upgrade
ezsystems/developer-documentation pull request #2266
Opened 2024-01-09 15:11 UTC by adriendupuis

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | 
| Versions      | 3.3+
| Edition       | Content/Headless, Experience, Commerce

Some people migrating from old version don't know why their credential stops working.

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2024-01-10 12:17 UTC, dabrt requested changes

2024-01-10 12:17 UTC, dabrt commented on docs/update_and_migration/from_2.5/to_3.3.md
> +    See [Composer authentication documentation](https://getcomposer.org/doc/articles/authentication-for-private-packages.md) to find the precedure suiting the way you're passing credentials.
```suggestion
    See [Composer authentication documentation](https://getcomposer.org/doc/articles/authentication-for-private-packages.md) to find the precedure that suits the way you're passing credentials.
```

2024-01-10 13:19 UTC, adriendupuis commented on docs/update_and_migration/from_2.5/to_3.3.md
> +   ```
```suggestion
    In production, replace the old repository by the new one.
    But as a developer, you may need to go back to earlier version, and should keep the old repository as well.
    For example, your `auth.json` may look like this:

    ```json
    {
        "http-basic": {
            "updates.ibexa.co": {
                "username": "abcdefghijklmnopqrstuvwxyz012345",
                "password": "6789abcdefghijklmnopqrstuvwxyz01"
            },
            "updates.ez.no": {
                "username": "abcdefghijklmnopqrstuvwxyz012345",
                "password": "6789abcdefghijklmnopqrstuvwxyz01"
            }
        }
    }
    ```
```

2024-01-10 15:48 UTC, vidarl requested changes
Maybe also mention that user should ensure that `repository` in `composer.json` is also correct?

Definition in 2.5
```
    "repositories": [
        {
            "type": "composer",
            "url": "https://updates.ez.no/ttl"
        }
    ],
```

Definition in 3.3
```
    "repositories": {
        "ibexa": {
            "type": "composer",
            "url": "https://updates.ibexa.co"
        }
    },
```

2024-01-10 22:29 UTC, dabrt approved these changes

2024-01-11 09:32 UTC, adriendupuis commented on docs/update_and_migration/from_2.5/to_3.3.md
> +    ```
> Maybe also mention that user should ensure that `repository` in `composer.json` is also correct?

@vidarl I now mention it during composer.json merge.

2024-01-11 13:25 UTC, dabrt commented on docs/update_and_migration/from_2.5/to_3.3.md
> +    Make sure that composer.json has the following `repositories` entry:
```suggestion
    It is impossible to update an Enterprise edition (`ezsystems/ezplatform-ee`)
    to an [[= product_name_content =]] edition.

    Make sure that `composer.json` has the following `repositories` entry:
```

Are these two statements logically related? Or rather they are two separate cautions?

If they are not connected, I would add "Also, " before "make sure that ..."

2024-01-11 13:25 UTC, dabrt commented on docs/update_and_migration/from_2.5/to_3.3.md
> +    ```json
```suggestion

    ```json
```

2024-01-18 09:02 UTC, adamwojs approved these changes

2024-01-18 09:06 UTC, vidarl approved these changes

2024-01-19 14:30 UTC, julitafalcondusza approved these changes

2024-01-30 15:42 UTC, merged

2024-01-30 15:45 UTC, adriendupuis commented
Cherry picked to branches 4.6, 4.5, 3.3 and 2.5