Update enable_personalization.md
ezsystems/developer-documentation pull request #2293
Opened 2024-02-12 17:42 UTC by todomagichere

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | 
| Versions      | 
| Edition       | 

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2024-02-14 08:00 UTC, ciastektk commented on docs/personalization/enable_personalization.md
> +                        customer_id: '%env(FRA_CUSTOMER_ID)%'
```suggestion
                        customer_id: '%env(int:FRA_CUSTOMER_ID)%'
```

2024-02-14 08:01 UTC, ciastektk commented on docs/personalization/enable_personalization.md
> +                            description: 'sub_title'
```suggestion
                            title: 'name'
                            image: 'image'
                            description: 'description'   
```

2024-02-14 08:02 UTC, ciastektk commented on docs/personalization/enable_personalization.md
> +                                description: 'sub_title'
```suggestion
                                title: 'short_title'
                                image: 'primary_image'
                                description: 'sub_title'
```

2024-02-14 08:06 UTC, ciastektk commented
@todomagichere, thank you for your contribution! Please add requested changes, and we can merge this PR.

2024-02-14 09:24 UTC, todomagichere commented
@ciastektk it's all ok?

2024-02-14 12:53 UTC, ciastektk requested changes
Everything is ok except duplicate options

2024-02-14 12:53 UTC, ciastektk commented on docs/personalization/enable_personalization.md
> +    --license-key=<LICENSE_KEY>
These options are duplicated

```suggestion
    --customer-id=<CUSTOMER_ID>
    --license-key=<LICENSE_KEY>
```

2024-02-14 14:31 UTC, todomagichere commented on docs/personalization/enable_personalization.md
> +    --license-key=<LICENSE_KEY>
Dah, done right now :)

2024-02-15 07:11 UTC, ciastektk approved these changes

2024-02-15 07:18 UTC, juskora approved these changes

2024-02-15 07:59 UTC, merged