Add instructions for making block attribute required with custom vali…
ezsystems/developer-documentation pull request #2309
Opened 2024-02-20 13:21 UTC by ms2ad

…dator

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | 
| Versions      | 
| Edition       | 

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2024-04-04 00:56 UTC, Steveb-p approved these changes
Using form extension to work with custom options is the way to go :+1:

Note that this applies to Attribute Definitions, which as I understand it is slightly different from Attributes. Attribute Definition is a whole group which represents an Attribute (`value`), including it's `name` and `id`.

See `Ibexa\PageBuilder\Form\Type\Attribute\AttributeType::buildForm()`, which in turn creates specific Attribute value types (using a mapper).

To make this easier on developers (we should gauge the need for it), we could expose a configuration option to add more constraints that should be treated as marking the form field as required :thinking:

2024-04-04 04:53 UTC, ms2ad commented
@Steveb-p I see what you mean that whether using the whole `$builder` object might be the right case because all fields are children of it, including the name and id field, not just the value.

> To make this easier on developers (we should gauge the need for it), we could expose a configuration option to add more constraints that should be treated as marking the form field as required 🤔

Your current implementation might also benefit from it because while having two specific validators hard-coded in `AttributeType::buildForm()` works, but is not the most clean code imaginable :)

2024-04-09 07:24 UTC, mnocon approved these changes
Thank you for the contribution! 🙇

2024-04-11 07:53 UTC, dabrt approved these changes

2024-04-11 10:49 UTC, adriendupuis commented on docs/content_management/pages/page_block_validators.md
> +``` php
I would highlight `$builder->setRequired(true);`:
```suggestion
``` php hl_lines="16"
```

2024-04-11 10:55 UTC, adriendupuis commented on docs/content_management/pages/page_block_validators.md
> +By default, only `not_blank` and `not_blank_richtext` cause a block attribute to be marked as required.
Nice to have a list of validators automatically triggering the "required" mark. It justifies a new section by itself. I would also add a new paragraph separator:

```suggestion
By default, only `not_blank` and `not_blank_richtext` validators mark a block attribute as required.

```

2024-04-11 10:56 UTC, adriendupuis requested changes
~~See review comments~~ ✅ applied

2024-04-11 11:00 UTC, adriendupuis approved these changes

2024-04-11 11:09 UTC, adriendupuis commented on docs/content_management/pages/page_block_validators.md
> +If you create a custom validator `custom_not_blank` with attribute-specific logic, you can extend the `AttributeType` class with a Symfony form type extension to ensure that the attribute is also con
https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/e/ensure-insure-assure
```suggestion
If you create a custom validator `custom_not_blank` with attribute-specific logic, you can extend the `AttributeType` class with a Symfony form type extension to make sure that the attribute is also considered required:
```

2024-04-11 11:14 UTC, merged

2024-04-11 11:18 UTC, adriendupuis commented
@ms2ad Thank you!