IBX-5705: OAuth server
ezsystems/developer-documentation pull request #2314
Opened 2024-02-23 11:33 UTC by adriendupuis

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | [IBX-5705](https://issues.ibexa.co/browse/IBX-5705)
| Versions      | 4.6
| Edition       | All

Document the OAuth 2 server

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2024-03-21 13:32 UTC, Nattfarinn approved these changes

2024-03-26 11:32 UTC, dabrt requested changes

2024-03-26 11:32 UTC, dabrt commented on docs/users/oauth_server.md
> +you must define a firewall using the `Ibexa\OAuth2Server\Security\Guard\OAuth2Authenticator`.
```suggestion
you must define a firewall by using `Ibexa\OAuth2Server\Security\Guard\OAuth2Authenticator`.
```

2024-03-26 11:32 UTC, dabrt commented on docs/users/oauth_server.md
> +It must be before firewall with less restrictuve pattern like `ibexa_front`.
```suggestion
It must be placed before the firewall with a less restrictive pattern like `ibexa_front`.
```

2024-03-26 11:32 UTC, dabrt commented on docs/users/oauth_server.md
> +TODO: Can it break same-domain Back Office like with [HTTP basic authentication](rest_api_authentication.md#configuration)?
Add information here

2024-03-26 11:32 UTC, dabrt commented on docs/users/oauth_server.md
> +You need the client redirect URIs to create it.
```suggestion
You need the client redirect URIs to create a client.
```

2024-03-26 11:32 UTC, dabrt commented on docs/users/oauth_server.md
> +`--redirect-uri` can be used multiple time.
```suggestion
!!! note
   You can call `--redirect-uri` multiple times.
```

2024-03-26 11:32 UTC, dabrt commented on docs/users/oauth_server.md
> +Redirect URIs can be added after the creation with `league:oauth2-server:update-client` command.
```suggestion
Alternatively, you could add redirect URIs after you create a client, by using the `league:oauth2-server:update-client` command.
```

2024-03-26 11:32 UTC, dabrt commented on docs/users/oauth_server.md
> +or to delete a client (`league:oauth2-server:delete-client`).
```suggestion
Other commands let you list all the configured clients (`league:oauth2-server:list-clients`)
or delete a client (`league:oauth2-server:delete-client`).
```

2024-03-26 11:32 UTC, dabrt commented on docs/users/oauth_server.md
> +  Use `bin/console help <command>` to usage detail for each of them.
```suggestion
!!! note

    For a list of all the commands that you can use maintain your clients, in a terminal, run `bin/console list league:oauth2-server`.
    To see usage details for each of the commands, run `bin/console help <command>` . 
```

2024-03-26 11:32 UTC, dabrt commented on docs/users/oauth_server.md
> +
```suggestion
```
This information is duplicated in the next section

2024-03-26 11:32 UTC, dabrt commented on docs/users/oauth_server.md
> +- See [package's online documentation](https://github.com/thephpleague/oauth2-server-bundle/blob/master/docs/basic-setup.md).
```suggestion

    For more information, see the package's [online documentation](https://github.com/thephpleague/oauth2-server-bundle/blob/master/docs/basic-setup.md).
```

2024-03-28 08:55 UTC, adriendupuis commented on code_samples/user_management/oauth_google/config/packages/knpu_oauth2_client.yaml
> +        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
This is capitalized this way in the original file.

2024-03-28 09:45 UTC, adriendupuis commented on docs/users/oauth_client.md
> +# OAuth client
Done in e9d96fffd3f35921d0f6a446e4b610ce489cad4b

2024-03-28 09:46 UTC, adriendupuis commented on docs/users/oauth_server.md
> +# OAuth Server
Done in e9d96fffd3f35921d0f6a446e4b610ce489cad4b

2024-03-28 09:47 UTC, adriendupuis commented on docs/users/oauth_server.md
> +    php bin/console ibexa:doctrine:schema:dump-sql --force-platform=postgres vendor/ibexa/oauth2-server/src/bundle/Resources/config/schema.yaml | psql <database_name>
Fixed in 3f1b6595b860c630d4d1ae1b4333870b1efc67ad

2024-03-28 09:49 UTC, adriendupuis commented on docs/users/oauth_server.md
> +TODO: Can it break same-domain Back Office like with [HTTP basic authentication](rest_api_authentication.md#configuration)?
```suggestion
```

2024-03-28 09:54 UTC, adriendupuis commented on docs/users/oauth_client.md
> +``` yaml
Effectively, the firewall example is a tall one.

2024-03-28 10:27 UTC, adriendupuis commented on docs/users/oauth_client.md
> +``` yaml
@dabrt  I didn't manage to make it works
![2024-03-28_11-23-11](https://github.com/ibexa/documentation-developer/assets/61695653/75851312-5f67-40f6-bd32-4f8e5f830185)

2024-03-31 13:16 UTC, adriendupuis commented on docs/users/oauth_client.md
> +    When you implement your own mapper for external login,
```suggestion
    When you implement your own mapper for external login,
```

2024-04-04 10:42 UTC, julitafalcondusza requested changes
Please check my comments.

2024-04-04 10:42 UTC, julitafalcondusza commented on docs/users/oauth_client.md
> +(Missing package is, at least, indicated in an error message.)
```suggestion
Missing package isnindicated in an error message.
```

2024-04-04 10:42 UTC, julitafalcondusza commented on docs/users/oauth_client.md
> +The two environment variables `OAUTH_GOOGLE_CLIENT_ID` and `OAUTH_GOOGLE_CLIENT_SECRET`
```suggestion
Two environment variables, `OAUTH_GOOGLE_CLIENT_ID` and `OAUTH_GOOGLE_CLIENT_SECRET`,
```

2024-04-04 10:42 UTC, julitafalcondusza commented on docs/users/oauth_client.md
> +To use the `google` client type, you must install the following package:
```suggestion
To use the `google` client type, you need to install the following package:
```

2024-04-04 10:42 UTC, julitafalcondusza commented on docs/users/oauth_client.md
> +The client must be associated to a [SiteAccess scope](multisite_configuration.md#scope).
```suggestion
The client needs to be a part of the [SiteAccess scope](multisite_configuration.md#scope).
```

2024-04-04 10:42 UTC, julitafalcondusza commented on docs/users/oauth_client.md
> +    - `ResourceOwnerIdToUserMapper` doesn't create a new user, but loads a user (resource owner) based on their identifier.
```suggestion
    - `ResourceOwnerIdToUserMapper` - loads a user (resource owner) based on the identifier, but doesn't create a new user.
```

2024-04-04 10:42 UTC, julitafalcondusza commented on docs/users/oauth_client.md
> +    - `ResourceOwnerEmailToUserMapper` doesn't create a new user, but loads a user (resource owner) based on their email.
```suggestion
    - `ResourceOwnerEmailToUserMapper` - loads a user (resource owner) based on the email, but doesn't create a new user.
```

2024-04-04 10:42 UTC, julitafalcondusza commented on docs/users/oauth_client.md
> +- `ResourceOwnerToExistingOrNewUserMapper` checks if the user exists and loads them if they do.
```suggestion
- `ResourceOwnerToExistingOrNewUserMapper` - checks whether the user exists and loads the data if it does.  If not, creates a new user in the Repository.
```

2024-04-04 10:42 UTC, julitafalcondusza commented on docs/users/oauth_client.md
> +  If they don't, the mapper creates a new user in the Repository.
```suggestion
```

2024-04-04 10:42 UTC, julitafalcondusza commented on docs/users/oauth_client.md
> +    This is because users who register through an external service do not have a separate password in the system.
```suggestion
    The users who register through an external service do not have a separate password in the system.
```

2024-04-04 10:42 UTC, julitafalcondusza commented on docs/users/oauth_client.md
> +here is how to add a **Log in with Google** to the Back Office login form.
```suggestion
you need to add a **Log in with Google** to the Back Office login form.
```

2024-04-04 11:14 UTC, julitafalcondusza approved these changes

2024-04-04 11:21 UTC, merged