Custom block: UDW config
ezsystems/developer-documentation pull request #2331
Opened 2024-03-12 09:02 UTC by adriendupuis

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | [IBX-7565](https://issues.ibexa.co/browse/IBX-7565)
| Versions      | 4.6, 4.5
| Edition       | Experience, Commerce

Custom UWD config for custom block.

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2024-03-13 07:29 UTC, adriendupuis commented on docs/content_management/pages/page_block_attributes.md
> +For more information, see [Create custom page block / Add edit templates with custom UDW](create_custom_page_block.md#add-edit-template)
```suggestion
For more information, see [Create custom page block / Add edit template](create_custom_page_block.md#add-edit-template)
```

2024-03-14 07:25 UTC, vidarl requested changes

2024-03-14 07:55 UTC, vidarl approved these changes

2024-04-03 06:41 UTC, mnocon approved these changes
It works! 🎉 

One small thing: there's an additional quote in the `code_samples/page/custom_page_block/config/packages/page_blocks.yaml` file, could you please fix it as well? See screenshot below.

<img width="832" alt="Screenshot 2024-04-03 at 08 39 09" src="https://github.com/ibexa/documentation-developer/assets/10993858/52a54062-e828-4409-964e-1187b4d21aee">

2024-04-03 10:48 UTC, merged