Fixed links in new in docs
ezsystems/developer-documentation pull request #2375
Opened 2024-05-06 07:30 UTC by juskora

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | 
| Versions      | all
| Edition       | 

Fixed links in New in docs for April.

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2024-05-06 10:06 UTC, adriendupuis requested changes
March 2024's links should also be fixed

2024-05-06 12:54 UTC, julitafalcondusza approved these changes

2024-05-06 12:55 UTC, mnocon approved these changes
Thank you!

2024-05-06 12:55 UTC, mnocon commented on docs/resources/new_in_doc.md
> +- [v4.6.0 to v4.6.3 update instructions](https://doc.ibexa.co/en/master/update_and_migration/from_4.5/update_from_4.5/#v462)
```suggestion
- [v4.6.0 to v4.6.3 update instructions](https://doc.ibexa.co/en/master/update_and_migration/from_4.5/update_from_4.5/#v463)
```
Unless I'm missing something 😉

2024-05-06 13:08 UTC, dabrt approved these changes

2024-05-07 07:58 UTC, adriendupuis approved these changes

2024-05-07 10:22 UTC, merged