IBX-8493: Ibexa Experience Product guide
ezsystems/developer-documentation pull request #2448
Opened 2024-07-29 11:48 UTC by julitafalcondusza

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | (https://issues.ibexa.co/browse/IBX-8493)
| Versions      | 4.6+
| Edition       | Headless, Experience, Commerce

Ibexa Experience Product guide added in Developer documentation.

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2024-08-06 20:55 UTC, mnocon reviewed
I've left a couple of suggestions how I think we can expand some sections and include features that weren't mentioned so far, but overall I like it - and it's very promising!

2024-08-07 06:46 UTC, julitafalcondusza commented on docs/ibexa_products/editions.md
> +Three [[= product_name =]] product edtions are available to help you accelerate your digital transformation at the speed and cost that work best for you.
We didn't try it.

2024-08-07 06:50 UTC, julitafalcondusza commented on docs/ibexa_products/experience.md
> +description: Discover Ibexa Experience and its essential features, capabilities and benefits.
In my opinion, it won't look good if all three editions will have exactly the same description. 
Yes, it's the same message in another words. But unification won't look good in this situation.
I rewrote it in another way.

2024-08-07 07:04 UTC, julitafalcondusza commented on docs/ibexa_products/experience.md
> +You also need to select a layout. The layout that is selected has a significant impact on how the content pieces in the drop zones are arranged.
"Need" is not as _strong_ as "have to". Anyway, it's true that you need to do it - yes, it gives a lot of flexibility, but even if it's one-zone page, you still need to choose it.

2024-08-07 07:05 UTC, julitafalcondusza commented on docs/ibexa_products/experience.md
> +[[= product_name_exp =]] is built on [[[= product_name_headless =]]](headless.md). It means that Experience edition includes all bundles, APIs, and [features that comes with Headless](headless.md#cor
I'd put it higher, but after Symfony part.

2024-08-07 07:12 UTC, julitafalcondusza commented on docs/ibexa_products/experience.md
> +#### Customer Data Platform (CDP)
I've added a sentence saying that it's an add-on.
Regarding segmentation - "CDP helps you to improve engagement, (...) by **_segmenting_** your audience (...)" - I guess it's enough here, there is a link to CDP guide.

2024-08-07 07:17 UTC, julitafalcondusza commented on docs/ibexa_products/experience.md
> +#### Page Builder
I've changed the order, I'd keep them in separate sections.

2024-08-07 07:23 UTC, mnocon commented on docs/ibexa_products/experience.md
> +#### Page Builder
Yes, I didn't mean to create a single paragraph for them - thanks!

2024-08-07 08:08 UTC, mnocon commented on docs/ibexa_products/experience.md
> +#### Customer Data Platform (CDP)
I would still expand this into two sections: Segmentation and CDP.

- Segmentation allows you to segment the userbase, which you can later use directly in Page Builder (with Targeting block) and with Personalization (https://doc.ibexa.co/projects/userguide/en/latest/personalization/segment_management/) to tailor the content seen by visitors.

This is available ouf of the box, for everyone who uses the Experience edition.

Then, if someone decides to invest deeper into this area, CDP awaits with even more possibilities (but requires an additional deal)

2024-08-07 12:09 UTC, mnocon reviewed
1) I'd still introduce segmentation as something different from CDP (https://github.com/ibexa/documentation-developer/pull/2448#discussion_r1706572210)
2) ReadTheDocs build is failing and there are some minor issues

Don't mind the broken PHPStan build, I'm taking care of it (the code samples stopped being valid when we merged https://github.com/ibexa/admin-ui/pull/1313/files)

2024-08-08 11:20 UTC, mnocon approved these changes
One last comment, but I trust you will know how to resolve this 😄 

It looks very good now, thank you!

2024-08-08 11:20 UTC, mnocon commented on docs/ibexa_products/experience.md
> +Segments work also with the [Personalization](personalization_brochure.md), where you can assign users to different recommendation groups and create advanced logic with operators to get best segmenta
```suggestion
The Targeting block is available in the Page Builder and you can use it right out of the box.
Segments work also with the [Personalization](personalization_brochure.md), where you can assign users to different recommendation groups and create advanced logic with operators to devlier the best recommendations for your audience.
```
1) There are some words missing in the first sentence
1) The Dynamic targeting block requires the Personalization integration (which is mentioned a sentence later)
2) Personalization delivers recommendations and I'd focus on that- the segmentation has to be done before that (manually or with CDP)

2024-08-08 14:36 UTC, dabrt requested changes

2024-08-08 14:36 UTC, dabrt commented on docs/ibexa_products/experience.md
> +It makes it simpler than ever to create the different touchpoints that your customers have with your brand, giving you the ability to guide them through your significant business procedures.
```suggestion
With [[= product_name_exp =]], your customers are the main focus of all that you do.
It makes it simpler than ever to create the different touchpoints that your customers have with your brand, giving you the ability to guide them through your significant business procedures. 
```

2024-08-08 14:36 UTC, dabrt commented on docs/ibexa_products/experience.md
> +User interface of [[= product_name_exp =]] is intuitive and plain. With its new features - Page and Form Builder - you can build new pages or forms quickly. Page Builder comes with predefined layouts
```suggestion
[[= product_name_exp =]]'s user interface is intuitive and user-friendly.
With its new features, Page Builder and Form Builder, you can design pages and forms quickly and efficiently.
Page Builder comes with predefined layouts, blocks, and templates to streamline your design process, while Form Builder provides ready-to-use elements for easy form creation.
Once you've built your custom forms and surveys, you can integrate them into your website and reuse content from existing sites on new ones.
Plus, with Site Factory, you can publish as many sites as you like, there are no limits.
```

2024-08-08 14:36 UTC, dabrt commented on docs/ibexa_products/experience.md
> +Available add-ons give you even more possibilities - you can analyze customer behaviours, use interactive content, and collect important data.
```suggestion
To make your products attractive, you must remember each of your customers is unique and special, and tailor your marketing strategy to their needs and preferences. 
[[= product_name_exp =]] allows you to deliver personalized content and recommendations through different channels.
With segmentation, you can define audiences that you will reach with specific content through the right channels, at the right time.
And add-ons give you even more possibilities: you can analyze customer behaviours, use interactive content, and collect important data.
```

2024-08-08 14:36 UTC, dabrt commented on docs/ibexa_products/experience.md
> +Planning and scheduling is a part of management. With scheduling tools available in Experience edition, you can prepare content publishing timetables, schedule how your website can evolve, and test o
```suggestion
Planning and scheduling is a part of management.
With scheduling tools available in Experience edition, you can prepare content publishing timetables, plan the evolution of your website, and test or preview it before publication.
Additionally, you can use editorial calendars for an easier collaboration.
```

2024-08-09 06:11 UTC, julitafalcondusza commented on docs/ibexa_products/experience.md
> +It offers smooth consumer journey and great online experience. In everything you do, it places your clients first.
It's mentioned in 'Technical backstage' section.
Core features are described, no need to list the differences.

2024-08-09 06:14 UTC, julitafalcondusza commented on docs/ibexa_products/experience.md
> +With an active license, you can start [installation process](install_ibexa_dxp.md) through Composer.
I'd keep previous version.

2024-08-09 06:20 UTC, julitafalcondusza commented on docs/ibexa_products/experience.md
> +When creating a page you also need to select a layout. It has a significant impact on how the content pieces in the drop zones are arranged.
I don't like using 'Tip' in Product Guides. I'd keep previous version.

2024-08-09 06:25 UTC, julitafalcondusza commented on docs/ibexa_products/experience.md
> +You can create customized Dashboard using Dashboard Builder. Dashboard then can be tailored to your specific needs - it contains a set of widgets selected by the user. You can easily preview the sect
I'd keep previous version of the last sentence, "promote" doesn't fit here (in my opinion).

2024-08-09 09:01 UTC, dabrt approved these changes

2024-08-09 09:03 UTC, dabrt commented on docs/ibexa_products/experience.md
> +With an active license, you can start [installation process](install_ibexa_dxp.md) through Composer.
I specifically dislike "through Composer". Composer is a tool, so... "with"

2024-08-09 10:40 UTC, merged