Document hiding taxonomy menu item
ezsystems/developer-documentation pull request #2459
Opened 2024-08-05 07:27 UTC by ms2ad

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | 
| Versions      | 
| Edition       | 

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2024-08-08 13:54 UTC, mnocon approved these changes
Good catch, thank you!

2024-08-09 10:36 UTC, dabrt requested changes

2024-08-09 10:36 UTC, dabrt commented on docs/content_management/taxonomy/taxonomy.md
> +You can hide this menu item via the `register_main_menu` option:
```suggestion
You can hide this menu item by setting a value of the `register_main_menu` configuration key:
```

2024-08-09 10:37 UTC, dabrt approved these changes

2024-08-09 10:56 UTC, merged