Reorganize "Update and migration"
ezsystems/developer-documentation pull request #2519
Opened 2024-10-11 16:21 UTC by adriendupuis

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | 
| Versions      | 
| Edition       | 

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2024-10-15 09:49 UTC, vidarl requested changes
1.  There is one flaw in the upgrade doc that should also be addressed. 
In the `composer update` command, we always refer to the latest maintenance release. ie like [here](https://ez-systems-developer-documentation--2519.com.readthedocs.build/en/2519/update_and_migration/from_4.5/update_from_4.5/#update-from-v45latest-to-v46) we ATM refer to 4.6.12

2. Then we later run [migrations](https://ez-systems-developer-documentation--2519.com.readthedocs.build/en/2519/update_and_migration/from_4.5/update_from_4.5/#run-data-migration)

3. And after that we run schema updates like for [4.6.4](https://ez-systems-developer-documentation--2519.com.readthedocs.build/en/2519/update_and_migration/from_4.6/update_from_4.6/#v464)

Step 2 might fail since code may require the schema changes that are applied later

So, once you upgrade to latest maintenance release, the next step should always be to get schema up2date.. Then run remaining upgrade scripts in correct order

2024-10-18 09:31 UTC, mnocon approved these changes
It's much clearer, thank you! I agree that we can further improve this in a follow-up.

Good job spotting and deleting the outdated instructions for 3.3

2024-10-18 09:31 UTC, mnocon commented on docs/update_and_migration/from_4.6/update_from_4.6.md
> +Then execute the instructions below from the version you're upgrading from (or the closest superior) to the end of this page.
```suggestion
Then execute the instructions below starting from the version you're upgrading from.
```
Can we add the missing versions with a short "No additional steps needed" section, like we have for 4.6.9? To make it clearer

2024-10-18 09:31 UTC, mnocon commented on docs/update_and_migration/from_4.4/update_from_4.4.md
> +You can now continue with the application of the 4.5 patches instructions starting with [v4.5.2](update_from_4.5.md#v452).
```suggestion
You can now continue applying the instructions for the 4.5 patch releases, starting with [v4.5.2](update_from_4.5.md#v452).
```

2024-10-18 10:33 UTC, vidarl commented
> we can't propose to move to 4.6.0, execute migrations, and then upgrade to 4.6.latest, and run the database update.

I didn't propose that either. Upgrading code to latest 4.6.x is better ( and less work than go through 4.6.0 first).
I am just saying than upgrading schema should be the next step, not running migrations or other php scripts that might fail due to not-up2date-schema ...

> @vidarl I'm adding this issue to [IBX-9082](https://issues.ibexa.co/browse/IBX-9082) for later.

Ok, I am fine about addressing this later. But it should be addressed at some point

2024-10-18 10:34 UTC, vidarl approved these changes

2024-10-18 16:43 UTC, merged