IBX-9006: Collaborative editing - REST API documentation
ezsystems/developer-documentation pull request #2528
Opened 2024-10-29 09:47 UTC by julitafalcondusza

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | (https://issues.ibexa.co/browse/IBX-9006)
| Versions      | 4.6+

Before merging, please test as a doc review.

Collaborative editing - REST API documentation:
Doc preview: https://ez-systems-developer-documentation--2528.com.readthedocs.build/en/2528/api/rest_api/rest_api_reference/rest_api_reference.html#collaborative-editing 

- [REST] Endpoint for initiating collaboration session (https://issues.ibexa.co/browse/IBX-8739) 
- [REST] Endpoint for deleting collaboration session (https://issues.ibexa.co/browse/IBX-8744)
- [REST] Add input validation for create collaboration session endpoint (https://issues.ibexa.co/browse/IBX-9048)
- [REST] Endpoint for retrieving collaboration session details (https://issues.ibexa.co/browse/IBX-8745)
- [REST] Endpoint for updating participant scope (https://issues.ibexa.co/browse/IBX-8741)
- [REST] Endpoint for removing participant (https://issues.ibexa.co/browse/IBX-8742)
- [REST] Endpoint for listing participants (https://issues.ibexa.co/browse/IBX-8743)
- [REST] Endpoint for add participant (https://issues.ibexa.co/browse/IBX-9001)
- [REST] Endpoint for creating collaboration invitation (https://issues.ibexa.co/browse/IBX-8740)
- [REST] Endpoint to list users with their permissions to content item (https://issues.ibexa.co/browse/IBX-9002)

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2025-09-17 10:06 UTC, ciastektk requested changes

2025-09-17 10:06 UTC, ciastektk commented on docs/api/rest_api/rest_api_reference/input/examples/collaborative_editing/session/create/POST/CollaborationSessionCreate.json.example
> +}
```suggestion
{
    "ContentSessionCreate": {
        "Owner": {
            "_media-type": "application/vnd.ibexa.api.User+json",
            "_href": "/api/ibexa/v2/user/users/14"
        },
        "ParticipantListCreate": {
            "_media-type": "application\/vnd.ibexa.api.ParticipantListCreate+json",
            "ParticipantCreate": [
                {
                    "_media-type": "application\/vnd.ibexa.api.InternalParticipantCreate+json",
                    "User": {
                        "_media-type": "application/vnd.ibexa.api.User+json",
                        "_href": "/api/ibexa/v2/user/users/70"
                    },
                    "scope": "edit"
                },
                {
                    "_media-type": "application\/vnd.ibexa.api.ExternalParticipantCreate+json",
                    "email": "user@link.invalid",
                    "scope": "view"
                }
            ]
        },
        "contentId": 57,
        "versionNo": 1
    }
}
```

2025-09-17 10:06 UTC, ciastektk commented on docs/api/rest_api/rest_api_reference/input/examples/collaborative_editing/session/create/POST/CollaborationSessionCreate.xml.example
> +</CollaborationSessionCreate>
```suggestion
<?xml version="1.0" encoding="UTF-8"?>
<ContentSessionCreate>
    <Owner media-type="application/vnd.ibexa.api.User+xml"
           href="/api/ibexa/v2/user/users/14"
    >
    </Owner>
    <ParticipantListCreate media-type="application/vnd.ibexa.api.ParticipantListCreate+xml">
        <ParticipantCreate media-type="application/vnd.ibexa.api.InternalParticipantCreate+xml">
            <scope>edit</scope>
            <User media-type="application/vnd.ibexa.api.User+xml"
                  href="/api/ibexa/v2/user/users/1470
            >
            </User>
        </ParticipantCreate>
        <ParticipantCreate media-type="application/vnd.ibexa.api.ExternalParticipantCreate+xml">
            <email>user@link.invalid</email>
            <scope>view</scope>
        </ParticipantCreate>
    </ParticipantListCreate>
    <contentId>57</contentId>
    <versionNo>1</versionNo>
</ContentSessionCreate>
```

2025-09-17 10:06 UTC, ciastektk commented on docs/api/rest_api/rest_api_reference/input/examples/collaborative_editing/session/create/POST/CollaborationSession.json.example
> +                    },
```suggestion
                    "id": 50,
                    "name": "Editor",
                    "scope": "edit",
                    "User": {
                        "_media-type": "application/vnd.ibexa.api.User+json",
                        "_href": "/api/ibexa/v2/user/users/70"
                    },
```

2025-09-17 10:06 UTC, ciastektk commented on docs/api/rest_api/rest_api_reference/input/examples/collaborative_editing/session/create/POST/CollaborationSession.xml.example
> +            <User media-type="application/vnd.ibexa.api.User+xml" href="/api/ibexa/v2/user/users/14"/>
```suggestion
            <id>50</id>
            <name>Administrator User</name>
            <scope>edit</scope>
            <User media-type="application/vnd.ibexa.api.User+xml" href="/api/ibexa/v2/user/users/70"/>
```

2025-09-17 10:06 UTC, ciastektk commented on docs/api/rest_api/rest_api_reference/input/examples/collaborative_editing/session/GET/CollaborationSession.json.example
> +}
Example should be the same or similar as for created session: https://github.com/ibexa/documentation-developer/pull/2528/files#diff-25e1f334c5b6cc2004abf45ac3d81af5ce6e564c1d16152e39482f66011a5041

2025-09-17 10:06 UTC, ciastektk commented on docs/api/rest_api/rest_api_reference/input/examples/collaborative_editing/session/GET/CollaborationSession.xml.example
> +</CollaborationSession>
Example should be similar or the same as for created session: https://github.com/ibexa/documentation-developer/pull/2528/files#diff-5d777eb3dc258ddd7b3cc9399c7803cd06fe0153ef7ed6177f581f73f4092499

2025-09-17 10:06 UTC, ciastektk commented on docs/api/rest_api/rest_api_reference/input/examples/collaborative_editing/session/create/POST/CollaborationSession.json.example
> +        "token": "3dbddb0e-e8ac-44bf-9042-57ca0c027f51",
```suggestion
        "token": "3dbddb0e-e8ac-44bf-9042-57ca0c027f51",
        "isActive": true,
        "hasPublicLink": false,
```

2025-09-17 10:06 UTC, ciastektk commented on docs/api/rest_api/rest_api_reference/input/examples/collaborative_editing/session/create/POST/CollaborationSession.json.example
> +        "hasPublicLink": false,
```suggestion
```

2025-09-17 10:06 UTC, ciastektk commented on docs/api/rest_api/rest_api_reference/input/examples/collaborative_editing/session/create/POST/CollaborationSession.xml.example
> +    <token>899fdbd7-4449-4f48-ae0e-eae56758c51f</token>
```suggestion
    <token>899fdbd7-4449-4f48-ae0e-eae56758c51f</token>
    <isActive>true</isActive>
    <hasPublicLink>false</hasPublicLink>
```

2025-09-17 10:06 UTC, ciastektk commented on docs/api/rest_api/rest_api_reference/input/examples/collaborative_editing/session/create/POST/CollaborationSession.xml.example
> +    <hasPublicLink>false</hasPublicLink>
```suggestion
```

2025-09-17 10:19 UTC, ciastektk requested changes
Incorrect responses for internal participant update

2025-09-17 10:19 UTC, ciastektk commented on docs/api/rest_api/rest_api_reference/input/examples/collaborative_editing/participant/add/PATCH/InternalParticipant.json.example
> +}
This response is for external participant.

Correct response for internal participant is:
```json
{
    "Participant": {
        "_media-type": "application/vnd.ibexa.api.InternalParticipant+json",
        "id": "46",
        "scope": "view",
        "name": "Editor",
        "User": {
            "_media-type": "application/vnd.ibexa.api.User+json",
            "_href": "/api/ibexa/v2/user/users/70"
        },
        "createdAt": "2024-11-14T14:09:47+00:00",
        "updatedAt": "2024-11-15T13:13:22+00:00"
    }
}
```

2025-09-17 10:19 UTC, ciastektk commented on docs/api/rest_api/rest_api_reference/input/examples/collaborative_editing/participant/add/PATCH/InternalParticipant.xml.example
> +</Participant>
The same as for json. This response is for external participant not internal.

```xml
<?xml version="1.0"?>
<Participant media-type="application/vnd.ibexa.api.InternalParticipant+xml">
    <id>46</id>
    <name>Editor</name>
    <scope>view</scope>
    <User media-type="application/vnd.ibexa.api.User+xml" href="/api/ibexa/v2/user/users/70"/>
    <createdAt>2024-11-14T14:09:47+00:00</createdAt>
    <updatedAt>2024-11-15T12:50:03+00:00</updatedAt>
</Participant>
```

2025-09-17 10:26 UTC, ciastektk commented
Missing section about session updates:

Method: PATCH

```json
{
    "ContentSessionUpdate": {
        "hasPublicLink": true
    }
}
```


```xml
<?xml version="1.0" encoding="UTF-8"?>
<ContentSessionUpdate>
    <hasPublicLink>true</hasPublicLink>
</ContentSessionUpdate>
```

2025-09-17 10:32 UTC, ciastektk requested changes

2025-09-17 10:32 UTC, ciastektk commented on docs/api/rest_api/rest_api_reference/input/ibexa-collaborativeediting-session.raml
> +/{sessionId}:
Using sessionId is no longer supported. Use sessionToken instead.
```suggestion
/{sessionToken}:
```

2025-09-23 08:47 UTC, ciastektk requested changes

2025-09-23 08:47 UTC, ciastektk commented on docs/api/rest_api/rest_api_reference/input/ibexa-collaborativeediting-session.raml
> +>>>>>>> 4b9d881fa945112fde19d619e21bd8be8c3884ba
Seems that diffs from conflict resolving is added here and below.

2025-09-23 08:47 UTC, ciastektk commented on docs/api/rest_api/rest_api_reference/input/ibexa-collaborativeediting-session.raml
> +/{sessionId}/link:
As I mentioned, this is internal endpoint and it should not be presented.

2025-09-23 11:33 UTC, ciastektk commented on docs/api/rest_api/rest_api_reference/input/examples/collaborative_editing/session/create/POST/CollaborationSessionCreate.json.example
> +                        "_href": "/api/ibexa/v2/user/users/14"
```suggestion
                        "_href": "/api/ibexa/v2/user/users/70"
```

2025-09-23 11:33 UTC, ciastektk commented on docs/api/rest_api/rest_api_reference/input/examples/collaborative_editing/session/create/POST/CollaborationSessionCreate.xml.example
> +                  href="/api/ibexa/v2/user/users/1470
```suggestion
                  href="/api/ibexa/v2/user/users/70
```

2025-09-23 11:33 UTC, ciastektk commented on docs/api/rest_api/rest_api_reference/input/examples/collaborative_editing/session/create/POST/CollaborationSession.xml.example
> +        <Content media-type="application/vnd.ibexa.api.ContentInfo+xml" href="/api/ibexa/v2/content/objects/51"/>
```suggestion
        <Content media-type="application/vnd.ibexa.api.ContentInfo+xml" href="/api/ibexa/v2/content/objects/57"/>
```

2025-09-23 11:33 UTC, ciastektk commented on docs/api/rest_api/rest_api_reference/input/examples/collaborative_editing/session/create/POST/CollaborationSession.json.example
> +                "_href": "/api/ibexa/v2/content/objects/590"
```suggestion
                "_href": "/api/ibexa/v2/content/objects/57"
```

2025-09-23 11:33 UTC, ciastektk commented on docs/api/rest_api/rest_api_reference/input/ibexa-collaborativeediting-session.raml
> +            201:
Missing description

2025-09-23 11:34 UTC, ciastektk commented on docs/api/rest_api/rest_api_reference/input/ibexa-collaborativeediting-session.raml
> +                description: Retrieves the participant list for a given collaboration session ID.
```suggestion
            sessionToken:
                description: Retrieves the participant list for a given collaboration session token.
```

2025-09-23 12:32 UTC, ciastektk approved these changes

2025-10-01 11:45 UTC, julitafalcondusza commented
Checked and approved from my side (cannot approve as I'm the author of the PR) ✅

2025-10-02 08:08 UTC, merged