Enhance search doc
ezsystems/developer-documentation pull request #2540
Opened 2024-11-12 12:39 UTC by adriendupuis

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | 
| Versions      | 
| Edition       | 

Use `LocationList::getTotalCount()` instead of `LocationList::$totalCount` (see [getter addition circa v4.2.3](https://github.com/ibexa/core/commit/1f618c6be663b3109dfb035772c47d1f41d34cdf#diff-d03fbe835e478257bf6dfd1284084daeff385518889f6bbdddbb11e83d64daf8))

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2024-11-13 15:02 UTC, adriendupuis commented on docs/search/search_in_trash_reference.md
> +which can be used by `Ibexa\Contracts\Core\Repository\TrashService::findTrashItems`.
```suggestion
When you [search for content items that are held in trash](search_api.md#searching-in-trash), you can apply only a limited subset of Search Criteria and Sort Clauses
which can be used by `Ibexa\Contracts\Core\Repository\TrashService::findTrashItems`.
Some sort clauses are exclusive to trash search.
```

2025-02-20 12:58 UTC, barw4 requested changes
Trash also uses the `ContentName` criterion.

2025-02-21 11:30 UTC, adriendupuis commented
> Trash also uses the `ContentName` search criterion.

@barw4 Thank you for pointing me this one and showing me its handler tag.

Added in bc136a1e755e08b146032c4ef78583cd95aed8c2

I missed it because it wasn't marked a trash criterion. I propose to mark it in ibexa/core#486

2025-02-21 15:16 UTC, barw4 approved these changes

2025-02-24 10:12 UTC, mnocon requested changes
Thank you for covering this!

I think the `ContentName` criterion is missing here: https://ez-systems-developer-documentation--2540.com.readthedocs.build/en/2540/search/search_in_trash_reference/ , could you please check?

Optional, something we can think about in the future:

I like the addition of the `Trash` column for criterions and sort clauses, it's much more readable this way - the question for me is if we still need to list them explicitly in the dedicated Trash reference (maybe just linking to the expanded tables would be enough and would make it easier to maintain)

2025-02-24 10:12 UTC, mnocon commented on docs/search/search_in_trash_reference.md
>  - [ContentTypeId](contenttypeid_criterion.md)
Shouldn't Content Name be listed here as well?

2025-02-25 10:47 UTC, mnocon approved these changes
Thank you!

2025-02-26 09:06 UTC, adriendupuis commented on docs/search/search_in_trash_reference.md
>  - [ContentTypeId](contenttypeid_criterion.md)
Added in 01a03dddf6f2551a3168d8efe11606ae8d3e8b8b

2025-03-05 08:02 UTC, merged