5.0: Use RelationListIterator
ezsystems/developer-documentation pull request #2548
Opened 2024-11-20 22:46 UTC by adriendupuis

| Question      | Answer
| ------------- | ---
| JIRA Ticket   | 
| Versions      | 
| Edition       | 

To get all relations, use `RelationListIteratorAdapter` + `BatchIterator` instead of `ContentService::countRelations()` + `ContentService::loadRelationList()`

Follows #2544 and in particular [this comment](https://github.com/ibexa/documentation-developer/pull/2544/files#r1850120052).

#### Checklist

- [ ] Text renders correctly
- [ ] Text has been checked with vale
- [ ] Description metadata is up to date
- [ ] Redirects cover removed/moved pages
- [ ] Code samples are working
- [ ] PHP code samples have been fixed with PHP CS fixer
- [ ] Added link to this PR in relevant JIRA ticket or code PR

2024-11-27 09:48 UTC, adriendupuis commented on docs/api/php_api/php_api_reference/classes/Ibexa-Contracts-Core-Repository-Iterator-BatchIteratorAdapter-RelationListIteratorAdapter.html
Will be removed from this PR when PHP API Ref will be generated with first 5.0.0 stable release.

2025-05-20 09:21 UTC, adriendupuis commented on docs/api/php_api/php_api_reference/classes/Ibexa-Contracts-Core-Repository-Iterator-BatchIteratorAdapter-RelationListIteratorAdapter.html
Now that there is a 5.0 branch, this isn't an issue anymore.

2025-06-06 13:30 UTC, adriendupuis commented on code_samples/api/public_php_api/src/Command/ViewContentMetaDataCommand.php
> -        $relationCount = $this->contentService->countRelations($versionInfo);
Maybe this one should be kept.

2025-06-06 14:08 UTC, adriendupuis commented on code_samples/api/public_php_api/src/Command/ViewContentMetaDataCommand.php
> -        $relationCount = $this->contentService->countRelations($versionInfo);
Never displayed, it was only used to load the list. Reader can rediscover it in the PHP API Ref if needed.

2025-07-22 10:39 UTC, mnocon requested changes
No comments about the code, looks solid 💪 

Only one suggestion about the wording, as it's not clear to me right now.

2025-07-22 10:39 UTC, mnocon commented on docs/content_management/content_api/browsing_content.md
>  This method loads only the specified subset of relations to improve performance and was created with pagination in mind.
```suggestion
To list Relations to and from your content, you can to pass a `VersionInfo` object to the [`ContentService::loadRelationList`](/api/php_api/php_api_reference/classes/Ibexa-Contracts-Core-Repository-ContentService.html#method_loadRelationList) method.
This method loads only the specified subset of relations to improve performance and was created with pagination in mind.

Alternatively, use the [`RelationListIteratorAdapter`](../../api/php_api/php_api_reference/classes/Ibexa-Contracts-Core-Repository-Iterator-BatchIteratorAdapter-RelationListIteratorAdapter.html) within a [`BatchIterator`](../../api/php_api/php_api_reference/classes/Ibexa-Contracts-Core-Repository-Iterator-BatchIterator.html) to iterate over all relations.
```

I suggest to rewrite this part somehow.

First we mention the `loadRelationList`,then we mention `RelationListIteratorAdapter` object, only to start the next sentence with "This method` - so we're back to discussing loadRelationList?

2025-07-22 14:58 UTC, adriendupuis commented on docs/content_management/content_api/browsing_content.md
>  This method loads only the specified subset of relations to improve performance and was created with pagination in mind.
@mnocon Thank you for this highlight. That effectively doesn't make much sense. With the "you can to pass" grammar issue and this sentence about "pagination in mind" that doesn't sound like something I would write, there is clearly an issue here.

I rewrite this in d025c0cb4e69a013c9adb66cec2314b62866dd34
https://ez-systems-developer-documentation--2548.com.readthedocs.build/en/2548/content_management/content_api/browsing_content/#relations

2025-07-31 11:48 UTC, mnocon reviewed
I'd mention https://doc.ibexa.co/en/latest/search/search_api/#processing-large-result-sets for people not familiar with it (I've found this page only recently, when adjusting the code samples for v5)

2025-07-31 11:48 UTC, mnocon commented on docs/content_management/content_api/browsing_content.md
> +  within a [`BatchIterator`](/api/php_api/php_api_reference/classes/Ibexa-Contracts-Core-Repository-Iterator-BatchIterator.html) which allow traversing the relation list using one same object
```suggestion
  within a [`BatchIterator`](/api/php_api/php_api_reference/classes/Ibexa-Contracts-Core-Repository-Iterator-BatchIterator.html) which allows traversing the whole relation list
  
See [Processing large result sets](search_api.md#processing-large-result-sets) for more information about the BatchIterator.
```

Could you please add the RelationListAdapter to the list of Adapters on https://doc.ibexa.co/en/latest/search/search_api/#processing-large-result-sets ?

2026-08-25 10:34 UTC, adriendupuis commented on docs/content_management/content_api/browsing_content.md
> +  within a [`BatchIterator`](/api/php_api/php_api_reference/classes/Ibexa-Contracts-Core-Repository-Iterator-BatchIterator.html) which allow traversing the relation list using one same object
Done in 8cdb1ab2f0608f350fc80f6ce5f8ebf3e70784da

2026-08-25 14:08 UTC, mnocon commented on docs/content_management/content_api/browsing_content.md
>  `ContentInfo` is loaded from the [`ContentService`](/api/php_api/php_api_reference/classes/Ibexa-Contracts-Core-Repository-ContentService.html) (line 8).
```suggestion
`ContentInfo` is loaded from the [`ContentService`](/api/php_api/php_api_reference/classes/Ibexa-Contracts-Core-Repository-ContentService.html).
```
Either line 13, or let's just remove it - it's hard to maintain.

2026-08-25 14:08 UTC, mnocon commented on docs/content_management/content_api/browsing_content.md
> +``` php hl_lines="11"
```suggestion
``` php hl_lines="13"
```

2026-08-25 14:08 UTC, mnocon commented on docs/content_management/content_api/browsing_content.md
> +You can retrieve the content type of content item through the [`getContentType`](/api/php_api/php_api_reference/classes/Ibexa-Contracts-Core-Repository-Values-Content-ContentInfo.html#method_getConte
```suggestion
You can retrieve the content type of a content item through the [`getContentType`](/api/php_api/php_api_reference/classes/Ibexa-Contracts-Core-Repository-Values-Content-ContentInfo.html#method_getContentType) method of the ContentInfo object:
```
I think the `a` is correct here?

2026-08-25 14:08 UTC, mnocon commented on docs/content_management/content_api/browsing_content.md
> +[[= include_code('code_samples/api/public_php_api/src/Command/ViewContentMetaDataCommand.php', 114, 118, remove_indent=True) =]]
I think this one should include the one line above, to include:

```
        $stateGroups = $this->objectStateService->loadObjectStateGroups();
```

as well.

```suggestion
[[= include_code('code_samples/api/public_php_api/src/Command/ViewContentMetaDataCommand.php', 113, 118, remove_indent=True) =]]
```

2026-08-25 14:08 UTC, mnocon commented on docs/content_management/content_api/browsing_content.md
>  To retrieve the fields of the selected content item, you can use the following command:
I think the header and description are wrong, and make it sound as if you need 3 services to access the value of a content item.

For that, you'd just use https://doc.ibexa.co/en/5.0/api/php_api/php_api_reference/classes/Ibexa-Contracts-Core-Repository-Values-Content-Content.html#method_getFields and iterate on that.


```suggestion
## Viewing content type definition

To retrieve the content type's field definitions of a selected content item, you can use the following command:
```

2026-08-25 14:08 UTC, mnocon commented on docs/content_management/content_api/browsing_content.md
>  For each field they print out its identifier, and then using [`FieldTypeService`](/api/php_api/php_api_reference/classes/Ibexa-Contracts-Core-Repository-FieldTypeService.html) retrieve the field's va
```suggestion
For each field definition they print out its identifier, and then using [`FieldTypeService`](/api/php_api/php_api_reference/classes/Ibexa-Contracts-Core-Repository-FieldTypeService.html) retrieve the field definition's value and print it out to the console.
```

2026-08-25 14:18 UTC, adriendupuis commented on docs/content_management/content_api/browsing_content.md
>  `ContentInfo` is loaded from the [`ContentService`](/api/php_api/php_api_reference/classes/Ibexa-Contracts-Core-Repository-ContentService.html) (line 8).
Fixed in b324feb63d4081504ef8551602a5704ea9cfb76a

2026-08-25 14:18 UTC, adriendupuis commented on docs/content_management/content_api/browsing_content.md
> +``` php hl_lines="11"
Fixed in b324feb63d4081504ef8551602a5704ea9cfb76a

2026-08-25 14:20 UTC, adriendupuis commented on docs/content_management/content_api/browsing_content.md
> +[[= include_code('code_samples/api/public_php_api/src/Command/ViewContentMetaDataCommand.php', 114, 118, remove_indent=True) =]]
Was fixed in 19daab97b0d7cdb3ee47835073d00605d747a16e

2026-08-25 14:58 UTC, mnocon approved these changes
Thank you!

2026-08-26 07:06 UTC, merged