[CI] Added job adding preview links
ezsystems/developer-documentation pull request #2561
Opened 2024-11-29 23:01 UTC by mnocon

2024-12-04 10:54 UTC, adriendupuis commented on .github/workflows/preview_comment.yaml
> +                      comment="Preview of modified files:: no markdown files changed, no preview needed."
If I modify a code sample, a preview is needed. I would reword to stick to the scope.

```suggestion
                      comment="Preview of modified files:: no Markdown change to preview."
```

2024-12-04 11:00 UTC, adriendupuis requested changes

2024-12-04 11:00 UTC, adriendupuis commented on .github/workflows/preview_comment.yaml
> +                      comment="Preview of modified files:\n\n$comment"
```suggestion
                      comment="Preview of modified Markdown files:\n\n$comment"
```

2024-12-04 11:00 UTC, adriendupuis commented on .github/workflows/preview_comment.yaml
> +                    body-includes: 'Preview of modified files'
```suggestion
                    body-includes: 'Preview of modified Markdown files'
```

2024-12-04 11:40 UTC, adriendupuis commented on .github/workflows/preview_comment.yaml
> +                    number_of__changed_files=$(echo "$changed_files" | wc -l)
I manage to generate the whole link list in one go:
`git diff --name-only HEAD "origin/master" | grep -E "^docs\/.*\.md$" | sed -E "s|^docs/(.*)\.md$|- [\1.md](${build_url}\1/)|"`

2025-02-05 13:16 UTC, mnocon commented on .github/workflows/preview_comment.yaml
> +                    number_of__changed_files=$(echo "$changed_files" | wc -l)
Thank you, this is like magic 😄 

I've reworked it a bit to avoid harcoding `master` and added a new line as it didn't work in Github Actions (it didn't create a list):
```
                      comment=$(git diff --name-only HEAD "origin/$GITHUB_BASE_REF" | grep -E "^docs\/.*\.md$" | sed -E "s|^docs/(.*)\.md$|- [docs/\1.md](${build_url}\1/)\n|")
```

2025-02-06 12:36 UTC, adriendupuis commented on .github/workflows/preview_comment.yaml
> +                    body-includes: 'Preview of modified Markdown files'
I would fix singular/plural issues this way:
```suggestion
                      comment="Preview of modified Markdown: no Markdown change to preview."
                    elif [[ $change_count -gt $file_limit ]] ; then
                      comment="Preview of modified Markdown: Too many files modified in a single PR, preview link list is skipped. ($change_count files &gth; $file_limit)"
                    else
                      comment="Preview of modified Markdown:\n\n$change_list"
                    fi

                    echo -e "$comment" > comment.md

            -   name: Find comment
                id: find-comment
                uses: peter-evans/find-comment@v3
                with:
                    issue-number: ${{ github.event.pull_request.number }}
                    comment-author: 'github-actions[bot]'
                    body-includes: 'Preview of modified Markdown'
```

2025-02-06 13:52 UTC, adriendupuis approved these changes

2025-02-07 09:22 UTC, julitafalcondusza approved these changes

2025-02-11 08:22 UTC, merged